### PR TITLE
support install enclosed enve

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/995)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/995)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[core/algorithm-builder/environments/java/dockerfile/setting.xml, line 122 at r1](https://reviewable.io/reviews/kube-hpc/hkube/995#-MKV13Gx6vnEm3AnTxz9:-MKV13Gx6vnEm3AnTxzA:bn2ivpf) ([raw file](https://github.com/kube-hpc/hkube/blob/c57b05e150b99c7f3b3da1289b126fa12d2e61be/core/algorithm-builder/environments/java/dockerfile/setting.xml#L122)):*
> ```XML
>       <id>ossrh</id>
>       <username>golanlia</username>
>       <password>.67%67keJfpY3eh</password>
> ```

your password
___
*[core/algorithm-builder/environments/java/dockerfile/setting.xml, line 195 at r1](https://reviewable.io/reviews/kube-hpc/hkube/995#-MKV11JN6CpV6jv7kzhP:-MKV11JN6CpV6jv7kzhQ:bb7phvt) ([raw file](https://github.com/kube-hpc/hkube/blob/c57b05e150b99c7f3b3da1289b126fa12d2e61be/core/algorithm-builder/environments/java/dockerfile/setting.xml#L195)):*
> ```XML
>    -->
>     <profile>
>       <id>custormer</id>
> ```

typo

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/995)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-builder/environments/java/dockerfile/setting.xml, line 122 at r1](https://reviewable.io/reviews/kube-hpc/hkube/995#-MKV13Gx6vnEm3AnTxz9:-MKYnPBMCk-nwQchL75Q:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/c57b05e150b99c7f3b3da1289b126fa12d2e61be/core/algorithm-builder/environments/java/dockerfile/setting.xml#L122)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

your password
</blockquote></details>

Done.
___
*[core/algorithm-builder/environments/java/dockerfile/setting.xml, line 195 at r1](https://reviewable.io/reviews/kube-hpc/hkube/995#-MKV11JN6CpV6jv7kzhP:-MKYnOvz-WyM8KMq5o92:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/c57b05e150b99c7f3b3da1289b126fa12d2e61be/core/algorithm-builder/environments/java/dockerfile/setting.xml#L195)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/995#-:-MKYrWd61-5wyRs5uORi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/995)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 14 at r6](https://reviewable.io/reviews/kube-hpc/hkube/995#-MK_BSg-8LQDD6eUYe7d:-MK_BSg-8LQDD6eUYe7e:b-kxqdt9) ([raw file](https://github.com/kube-hpc/hkube/blob/79c57e629745e03268fcdb1304a4d202dc983b2d/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L14)):*
> ```
> COPY ./runJava.sh /hkube/algorithm-runner/
> WORKDIR /hkube/algorithm-runner/algorithm_unique_folder/
> RUN cat /root/.m2/settings.xml
> ```

don't forget to remove this

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/995#-:-MK_UsUE5pN8Nt-u8zbR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
