### PR TITLE
add healthcheks

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1263)

### CODE REVIEW

**Review by NassiHarel — APPROVED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1263)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/resource-manager/bootstrap.js, line 30 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1263#-M__e_1i2YXt8wjNsykd:-M__e_1i2YXt8wjNsyke:b7vm3dx) ([raw file](https://github.com/kube-hpc/hkube/blob/ee46f35c0ddb15e0dbc64ffbea6f7397233f0d55/core/resource-manager/bootstrap.js#L30)):*
> ```JavaScript
>                 await healthcheck.init({ port: main.healthchecks.port });
>                 healthcheck.start(main.healthchecks.path, () => runner.checkHealth(main.healthchecks.maxDiff), main.serviceName);
>             }
> ```

I think the healthcheck API should be simple

instead of:

```
if (main.healthchecks.enabled) {
     await healthcheck.init({ port: main.healthchecks.port });
     healthcheck.start(main.healthchecks.path, () => runner.checkHealth(main.healthchecks.maxDiff), main.serviceName);
 }

```

Just:
```
healthcheck.start(config.healthchecks , () => runner);
```

That's my opinion, maybe in the future...
___
*[core/resource-manager/lib/runner/runner.js, line 53 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1263#-M__faCFCIk8prqGLyyD:-M__faCG7P0Z2Bojr-P0:b-erkf07) ([raw file](https://github.com/kube-hpc/hkube/blob/ee46f35c0ddb15e0dbc64ffbea6f7397233f0d55/core/resource-manager/lib/runner/runner.js#L53)):*
> ```
> ····
> ```

Tabs...

**Review by NassiHarel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1263)* status: all files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/resource-manager/lib/runner/runner.js, line 44 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1263#-M__gK-U6A6pGPflWbEj:-M__gK-VEij5A2z_Y535:bc6bvhg) ([raw file](https://github.com/kube-hpc/hkube/blob/ee46f35c0ddb15e0dbc64ffbea6f7397233f0d55/core/resource-manager/lib/runner/runner.js#L44)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>     checkHealth(maxDiff) {
>         log.debug('health-checks');
>         if (!this._lastIntervalTime) {
>             return true;
>         }
>         const diff = Date.now() - this._lastIntervalTime;
>         log.debug(`diff = ${diff}`);
>         return (diff < maxDiff);
>     }
> ```
</details>


This code is repeated itself in every service, think about more generic way, 
maybe inherit some class, or emit an event `runner.emit('healthy')`

**Review by NassiHarel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1263)* status: all files reviewed, 4 unresolved discussions (waiting on @yehiyam)

Suggestion:

```

class Runner extends HealthCheck {     // inherit
    async init(options) {
        setInterval(async () => {
            if (this._working) {
                return;
            }
            try {
                this._working = true;
                await this._doWork();
                this.healty();   // implement
            }
            catch (e) {
                this._onError(e);
            }
            finally {
                this._working = false;
            }
        }, options.interval);
    }

```

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1263)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[core/resource-manager/bootstrap.js, line 30 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1263#-M__e_1i2YXt8wjNsykd:-Ma2Y0XAE1Q9zoecCGM5:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ee46f35c0ddb15e0dbc64ffbea6f7397233f0d55/core/resource-manager/bootstrap.js#L30)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I think the healthcheck API should be simple

instead of:

```
if (main.healthchecks.enabled) {
     await healthcheck.init({ port: main.healthchecks.port });
     healthcheck.start(main.healthchecks.path, () => runner.checkHealth(main.healthchecks.maxDiff), main.serviceName);
 }

```

Just:
healthcheck.start(config.healthchecks , () => runner.checkHealth());

That's my opinion, maybe in the future...

</blockquote></details>

Done.
___
*[core/resource-manager/lib/runner/runner.js, line 10 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1263#-M__hZUY5waO2zqLk0H9:-Ma2Y5z_AKNg-twGwbDG:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ee46f35c0ddb15e0dbc64ffbea6f7397233f0d55/core/resource-manager/lib/runner/runner.js#L10)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Suggestion:

```

class Runner extends HealthCheck {     // inherit
    async init(options) {
        setInterval(async () => {
            if (this._working) {
                return;
            }
            try {
                this._working = true;
                await this._doWork();
                this.healty();   // imlement
            }
            catch (e) {
                this._onError(e);
            }
            finally {
                this._working = false;
            }
        }, options.interval);
    }

```

</blockquote></details>

Done.
___
*[core/resource-manager/lib/runner/runner.js, line 44 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1263#-M__gK-U6A6pGPflWbEj:-Ma2Y7o0-tVOsRAG4Glh:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ee46f35c0ddb15e0dbc64ffbea6f7397233f0d55/core/resource-manager/lib/runner/runner.js#L44)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>     checkHealth(maxDiff) {
>         log.debug('health-checks');
>         if (!this._lastIntervalTime) {
>             return true;
>         }
>         const diff = Date.now() - this._lastIntervalTime;
>         log.debug(`diff = ${diff}`);
>         return (diff < maxDiff);
>     }
> ```

This code is repeated itself in every service, think about more generic way, 
maybe inherit some class, or emit an event `runner.emit('healthy')`
</blockquote></details>

Done.
___
*[core/resource-manager/lib/runner/runner.js, line 53 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1263#-M__faCFCIk8prqGLyyD:-Ma2YFRB4qBfsmi-JCMT:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ee46f35c0ddb15e0dbc64ffbea6f7397233f0d55/core/resource-manager/lib/runner/runner.js#L53)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> ····
> ```

Tabs...
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1263)* status: all files reviewed, 6 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/resource-manager/bootstrap.js, line 27 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1263#-Ma2cUijAM7U22nu6qFA:-Ma2cUijAM7U22nu6qFB:b8p8owt) ([raw file](https://github.com/kube-hpc/hkube/blob/f7b7a6c61858558a9f87674bfdfd5c72fa574754/core/resource-manager/bootstrap.js#L27)):*
> ```
> await healthchecks.initAndStart(main.healthchecks, () => runner.checkHealth(main.healthchecks.maxDiff), main.serviceName);
> ```

I think it should be just
```
await healthchecks.initAndStart(main.healthchecks, () => runner.checkHealth());
```

The config can be
```
config.healthchecks = {
    path: process.env.HEALTHCHECK_PATH || '/healthz',
    port: process.env.HEALTHCHECK_PORT || '5000',
    maxDiff: process.env.HEALTHCHECK_MAX_DIFF || '10000',
    enabled: formatter.parseBool(process.env.HEALTHCHECKS_ENABLE, true),
    name: config.serviceName
}

```
___
*[core/resource-manager/lib/runner/runner.js, line 29 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1263#-Ma2cGsrAW3bu5M-GgEX:-Ma2cGsrAW3bu5M-GgEY:b-23eudd) ([raw file](https://github.com/kube-hpc/hkube/blob/f7b7a6c61858558a9f87674bfdfd5c72fa574754/core/resource-manager/lib/runner/runner.js#L29)):*
> ```
> this.setHealthy();
> ```

`this` works, but use `super`

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1263#-:-Ma3FJ6Z0uPM6Yhq8z0u:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @NassiHarel and @yehiyam)

**Pull request merged**
