### PR TITLE
feat: add rerun

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1331)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1331)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel)

___
*[core/openapi-spec/swagger/definitions/exec/rerun.yaml, line 3 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1331#-MeULZCJAwNhoVdhbLwJ:-MeULZCJAwNhoVdhbLwK:b-5a9299) ([raw file](https://github.com/kube-hpc/hkube/blob/c4f4496566ae1a32173774c9a6affd3b2cbf3882/core/openapi-spec/swagger/definitions/exec/rerun.yaml#L3)):*
> ```YAML
> type: object
> properties:
>   jobId:
> ```

We can add `debugOverride` here to allow rerun-ing with debug
___
*[core/openapi-spec/swagger/paths/exec/rerun.yaml, line 18 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1331#-MeUMURYBgs_CDTtjLQY:-MeUMURYBgs_CDTtjLQZ:bcj0fc4) ([raw file](https://github.com/kube-hpc/hkube/blob/c4f4496566ae1a32173774c9a6affd3b2cbf3882/core/openapi-spec/swagger/paths/exec/rerun.yaml#L18)):*
> ```YAML
>         application/json:
>           schema:
>             $ref: "#/components/schemas/jobIdObject"
> ```

doesn't it also return the gateway if there is one?
___
*[core/openapi-spec/swagger/paths/exec/rerun.yaml, line 26 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1331#-MeULjPI02IKIioOfeEl:-MeULjPI02IKIioOfeEm:b-8anw1z) ([raw file](https://github.com/kube-hpc/hkube/blob/c4f4496566ae1a32173774c9a6affd3b2cbf3882/core/openapi-spec/swagger/paths/exec/rerun.yaml#L26)):*
> ```YAML
>             $ref: "#/components/schemas/error"
>     "404":
>       description: pipeline Not Found
> ```

should be `job not found`

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1331)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/openapi-spec/swagger/definitions/exec/rerun.yaml, line 3 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1331#-MeULZCJAwNhoVdhbLwJ:-MeUPDorCbeC8UsFkzFT:bbdx5n9) ([raw file](https://github.com/kube-hpc/hkube/blob/c4f4496566ae1a32173774c9a6affd3b2cbf3882/core/openapi-spec/swagger/definitions/exec/rerun.yaml#L3)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

We can add `debugOverride` here to allow rerun-ing with debug
</blockquote></details>

This is what I started with, but then I realized it can be complex if you rerun something that already ran with `debugOverride`.
So I decided to keep it simple, just rerun the exact same pipeline again. bli shtikim - bli trickim :)
___
*[core/openapi-spec/swagger/paths/exec/rerun.yaml, line 18 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1331#-MeUMURYBgs_CDTtjLQY:-MeUQU6EBoh7OIQw8SVM:b55qf2c) ([raw file](https://github.com/kube-hpc/hkube/blob/c4f4496566ae1a32173774c9a6affd3b2cbf3882/core/openapi-spec/swagger/paths/exec/rerun.yaml#L18)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

doesn't it also return the gateway if there is one?
</blockquote></details>

Yes, it's true for all `exec APIs specs`, it's not documented (also gateways is optional)
___
*[core/openapi-spec/swagger/paths/exec/rerun.yaml, line 26 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1331#-MeULjPI02IKIioOfeEl:-MeURVgXCJq3oytMITBa:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/c4f4496566ae1a32173774c9a6affd3b2cbf3882/core/openapi-spec/swagger/paths/exec/rerun.yaml#L26)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

should be `job not found`
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1331#-:-MeUUk6H7dD0cSDkXn7-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1331#-:-MeUdzdO-yw_pyb6oV2Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Pull request merged**
