### PR TITLE
Job aggregation api

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1493)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1493)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[core/pipeline-driver-queue/lib/service/managed.js, line 81 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1493#-MsUu_MEA1wxcU1DnvW8:-MsUu_MEA1wxcU1DnvW9:bpkey9o) ([raw file](https://github.com/kube-hpc/hkube/blob/92f7d4db0a630d3a0bd86f2e36600631721390a9/core/pipeline-driver-queue/lib/service/managed.js#L81)):*
> ```JavaScript
>                     aggregation.name = job.pipeline;
>                     aggregation.count = 1;
>                     groupByValue[job.pipeline] = aggregation;
> ```

This code looks duplicate, you can do something like:

```
function groupBy(array, property) {
    return array.reduce((acc, obj) => {
        const key = obj[property];
        if (!acc[key]) {
            acc[key] = { name: key, count: 0 };
        }
        acc[key].count += 1;
        return acc;
    }, {});
}
```

and call this function



_Code quote:_
```JavaScript
            if (propertyName === 'pipeline') {
                let aggregation = groupByValue[job.pipeline];
                if (!aggregation) {
                    aggregation = {};
                    aggregation.name = job.pipeline;
                    aggregation.count = 1;
                    groupByValue[job.pipeline] = aggregation;
                }
                else {
                    aggregation.count += 1;
                }
            }
            if (propertyName === 'tag') {
                job.tags.forEach((tag) => {
                    let aggregation = groupByValue[tag];
                    if (!aggregation) {
                        aggregation = {};
                        aggregation.name = tag;
                        aggregation.count = 1;
                    }
                    else {
                        aggregation.count += 1;
                    }
                });
            }
```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1493)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/pipeline-driver-queue/lib/service/managed.js, line 81 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1493#-MsUu_MEA1wxcU1DnvW8:-MsV9unZ8rg8hC0CBGbI:b-fvn18f) ([raw file](https://github.com/kube-hpc/hkube/blob/92f7d4db0a630d3a0bd86f2e36600631721390a9/core/pipeline-driver-queue/lib/service/managed.js#L81)):*
> function groupBy(array, property) {
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

>     return array.reduce((acc, obj) => {
>         const key = obj[property];
>         if (!acc[key]) {
>             acc[key] = { name: key, count: 0 };
>         }
>         acc[key].count += 1;
>         return acc;
>     }, {});
</details>
> }
  The tag has a set of values not only one, so I group by each tag separately , I merged some of the redundant code

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1493)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/pipeline-driver-queue/api/rest-api/routes/managed.js, line 12 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1493#-Mt8cTUXB378ekp4HMww:-Mt8cTUXB378ekp4HMwx:b2bza8h) ([raw file](https://github.com/kube-hpc/hkube/blob/e1f969dd89a0ff6df74a9b4dd0fe30df656c4e1c/core/pipeline-driver-queue/api/rest-api/routes/managed.js#L12)):*
> ```JavaScript
>         if (tag || pipelineName) {
>             filter = {};
>             filter.pipelineName = pipelineName;
> ```

add this logic to the  `lib/service/managed`
You can do 

```
filter = {
   pipelineName,
   tag
}
```



_Code quote:_
```JavaScript
        if (tag || pipelineName) {
            filter = {};
            filter.pipelineName = pipelineName;
            filter.tag = tag;
        }
```
___
*[core/pipeline-driver-queue/api/rest-api/routes/preferred.js, line 13 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1493#-Mt8ciOX5pBqqop2XwPJ:-Mt8ciOX5pBqqop2XwPK:bta2w7d) ([raw file](https://github.com/kube-hpc/hkube/blob/e1f969dd89a0ff6df74a9b4dd0fe30df656c4e1c/core/pipeline-driver-queue/api/rest-api/routes/preferred.js#L13)):*
> ```JavaScript
>         if (tag || pipelineName) {
>             filter = {};
>             filter.pipelineName = pipelineName;
> ```

Duplicate code here, like in routes/managed



_Code quote:_
```JavaScript
        if (tag || pipelineName) {
            filter = {};
            filter.pipelineName = pipelineName;
            filter.tag = tag;
        }
```
___
*[core/pipeline-driver-queue/tests/test.js, line 202 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1493#-Mt8d1Gr9l_mWoaDnrMk:-Mt8d1Gr9l_mWoaDnrMl:b4rs4rt) ([raw file](https://github.com/kube-hpc/hkube/blob/e1f969dd89a0ff6df74a9b4dd0fe30df656c4e1c/core/pipeline-driver-queue/tests/test.js#L202)):*
> ```JavaScript
> 
>     describe('managed tests', () => {
>         let jobs;
> ```

Please add tests to a separate file, the conflicts are trouble...

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1493)* status: 15 of 22 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/pipeline-driver-queue/api/rest-api/routes/managed.js, line 12 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1493#-Mt8cTUXB378ekp4HMww:-MtBljZfCwZcMXr2rzLL:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/e1f969dd89a0ff6df74a9b4dd0fe30df656c4e1c/core/pipeline-driver-queue/api/rest-api/routes/managed.js#L12)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

add this logic to the  `lib/service/managed`
You can do 

```
filter = {
   pipelineName,
   tag
}
```
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/api/rest-api/routes/preferred.js, line 13 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1493#-Mt8ciOX5pBqqop2XwPJ:-MtBllvr1yGdkC0vjJxD:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/e1f969dd89a0ff6df74a9b4dd0fe30df656c4e1c/core/pipeline-driver-queue/api/rest-api/routes/preferred.js#L13)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Duplicate code here, like in routes/managed
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/tests/test.js, line 202 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1493#-Mt8d1Gr9l_mWoaDnrMk:-MtCDU0A50ZKPEJfPgBs:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/e1f969dd89a0ff6df74a9b4dd0fe30df656c4e1c/core/pipeline-driver-queue/tests/test.js#L202)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Please add tests to a separate file, the conflicts are trouble...
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1493#-:-MtCXIZK4Tw8oPVCkXCK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
