### PR TITLE
user internal artifactory in java builder

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1048)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1048)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[core/algorithm-builder/dockerfile/get-deps-java.sh, line 4 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1048#-MOVdMDd3uCRe2crBver:-MOVdMDd3uCRe2crBves:bhgbeu) ([raw file](https://github.com/kube-hpc/hkube/blob/9d2914144b77806c877f39cb8b1505006bf0b2e1/core/algorithm-builder/dockerfile/get-deps-java.sh#L4)):*
> ```Shell
> set -eo pipefail
> SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
> mkdir -p $SCRIPTPATH/../environments/java/m2
> ```

I think this folder is not used
___
*[core/algorithm-builder/dockerfile/get-deps-java.sh, line 8 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1048#-MOVda4F0PsdEtyaPLwG:-MOVda4F0PsdEtyaPLwH:b-uzaucb) ([raw file](https://github.com/kube-hpc/hkube/blob/9d2914144b77806c877f39cb8b1505006bf0b2e1/core/algorithm-builder/dockerfile/get-deps-java.sh#L8)):*
> ```Shell
> mkdir -p $SCRIPTPATH/../environments/java/debs
> cd $SCRIPTPATH/../environments/java/debs
> docker run --rm --workdir /tmp/pkg -v $SCRIPTPATH/../environments/java/debs:/tmp/pkg\
> ```

Is this used? I remember that you created a base in hkube

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1048)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-builder/dockerfile/get-deps-java.sh, line 4 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1048#-MOVdMDd3uCRe2crBver:-MOWtIsg6-jV38uvUN3x:bvqc27h) ([raw file](https://github.com/kube-hpc/hkube/blob/9d2914144b77806c877f39cb8b1505006bf0b2e1/core/algorithm-builder/dockerfile/get-deps-java.sh#L4)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I think this folder is not used
</blockquote></details>

you are right it is not used removed.
___
*[core/algorithm-builder/dockerfile/get-deps-java.sh, line 8 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1048#-MOVda4F0PsdEtyaPLwG:-MOWt2Ng3oZTDYOu-Dn3:b-ldqbug) ([raw file](https://github.com/kube-hpc/hkube/blob/9d2914144b77806c877f39cb8b1505006bf0b2e1/core/algorithm-builder/dockerfile/get-deps-java.sh#L8)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is this used? I remember that you created a base in hkube
</blockquote></details>

The base is just jdk of specific image that won't fail upon the lib installation.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1048#-:-MOWwJJ21Jxalg4mnJ3a:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[core/algorithm-builder/dockerfile/get-deps-java.sh, line 8 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1048#-MOVda4F0PsdEtyaPLwG:-MOWvxnZ0gCHTDeEc71v:b-igrhzw) ([raw file](https://github.com/kube-hpc/hkube/blob/9d2914144b77806c877f39cb8b1505006bf0b2e1/core/algorithm-builder/dockerfile/get-deps-java.sh#L8)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

The base is just jdk of specific image that won't fail upon the lib installation.
</blockquote></details>

Don't need to do it right now, but why not create an image with the lib installed

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1048)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/algorithm-builder/dockerfile/get-deps-java.sh, line 8 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1048#-MOVda4F0PsdEtyaPLwG:-MO_29Ua6sBetR_JEngS:b-3ikak0) ([raw file](https://github.com/kube-hpc/hkube/blob/9d2914144b77806c877f39cb8b1505006bf0b2e1/core/algorithm-builder/dockerfile/get-deps-java.sh#L8)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Don't need to do it right now, but why not create an image with the lib installed
</blockquote></details>

You are right, I thought of that too at a certain point.

**Pull request merged**
