### PR TITLE
db migration

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1039)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 138 of 150 files at r1, 18 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1039)* status: all files reviewed, 7 unresolved discussions (waiting on @maty21 and @NassiHarel)

___
*[core/algorithm-operator/lib/reconcile/algorithm-debug.js, line 53 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDrVGG2t7ssAwlIa0R:-MPDrVGG2t7ssAwlIa0S:b2tyopv) ([raw file](https://github.com/kube-hpc/hkube/blob/e0a353381435fe5f76405c8ab32f0913bfd0c47c/core/algorithm-operator/lib/reconcile/algorithm-debug.js#L53)):*
> ```JavaScript
>     }
>     for (let algorithm of removed) { // eslint-disable-line
>         await etcd.removeAlgorithmData(algorithm.algorithmName); // eslint-disable-line
> ```

This is not needed anymore? is the data deleted from mongo in another place?
___
*[core/algorithm-operator/lib/reconcile/normalize.js, line 22 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDrelXB7vFJ12OcSFz:-MPDrelXB7vFJ12OcSG-:b-s3hmjs) ([raw file](https://github.com/kube-hpc/hkube/blob/e0a353381435fe5f76405c8ab32f0913bfd0c47c/core/algorithm-operator/lib/reconcile/normalize.js#L22)):*
> ```JavaScript
>         return [];
>     }
>     return algorithmsRaw.filter(a => a.options && !a.options.pending);
> ```

Not needed?
___
*[core/pipeline-driver-queue/lib/persistency/persistence.js, line 17 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDv5xtD1s8YXlauC4T:-MPDv5xu-DaLu7Cj4Iwo:b-9fruij) ([raw file](https://github.com/kube-hpc/hkube/blob/b6af38b697f061fbf9ccc8a1831576e763f6f1de/core/pipeline-driver-queue/lib/persistency/persistence.js#L17)):*
> ```JavaScript
>         const { etcd, persistence, serviceName } = options;
>         this.queueName = persistence.type;
>         this.client = new Client({ ...etcd, serviceName });
> ```

Change name to this._etcd?
___
*[core/resource-manager/lib/adapters/settings.js, line 23 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDvR0yCYbjNXpcZ86R:-MPDvR0yCYbjNXpcZ86S:bifpjn) ([raw file](https://github.com/kube-hpc/hkube/blob/b6af38b697f061fbf9ccc8a1831576e763f6f1de/core/resource-manager/lib/adapters/settings.js#L23)):*
> ```JavaScript
>             enable: true,
>             mandatory: true,
>             cacheTTL: 10
> ```

why did you change the TTL?
___
*[core/task-executor/lib/helpers/etcd.js, line 1 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDvkv_20DpNx4m6t7T:-MPDvkv_20DpNx4m6t7U:b467pt2) ([raw file](https://github.com/kube-hpc/hkube/blob/b6af38b697f061fbf9ccc8a1831576e763f6f1de/core/task-executor/lib/helpers/etcd.js#L1)):*
> ```JavaScript
> const EtcdClient = require('@hkube/etcd');
> ```

rename file?
___
*[core/trigger-service/config/main/config.base.js, line 6 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDwXSe6KZGqxDPQWjW:-MPDwXSe6KZGqxDPQWjX:b-93ftyw) ([raw file](https://github.com/kube-hpc/hkube/blob/b6af38b697f061fbf9ccc8a1831576e763f6f1de/core/trigger-service/config/main/config.base.js#L6)):*
> ```JavaScript
> 
> config.serviceName = pkg.name;
> config.checkCronsIntervalMs = formatter.parseInt(process.env.TRIGGER_SERVICE_CHECK_CRONS, 15000)
> ```

that's the interval to check if there are any crons to start? or just check if there are new pipelines with crons?
___
*[core/worker/lib/states/stateAdapter.js, line 48 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDxDL62LxzHcITeo5H:-MPDxDL62LxzHcITeo5I:bbtdfxo) ([raw file](https://github.com/kube-hpc/hkube/blob/b6af38b697f061fbf9ccc8a1831576e763f6f1de/core/worker/lib/states/stateAdapter.js#L48)):*
> ```
> this._db.config
> ```
I think it is better to not print username/password to log

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1039)* status: all files reviewed, 7 unresolved discussions (waiting on @maty21 and @yehiyam)

___
*[core/algorithm-operator/lib/reconcile/algorithm-debug.js, line 53 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDrVGG2t7ssAwlIa0R:-MPEC6d99Oc4_01-VQua:b5x7jzy) ([raw file](https://github.com/kube-hpc/hkube/blob/e0a353381435fe5f76405c8ab32f0913bfd0c47c/core/algorithm-operator/lib/reconcile/algorithm-debug.js#L53)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This is not needed anymore? is the data deleted from mongo in another place?
</blockquote></details>

1) This was deleting debug algorithm from etcd path `/algorithms/debug/`.
But algorithms are never stored there.

2) If there is a need to remove deployment because the algorithm has been deleted, why this was trying to delete the debug algorithm.... This is useless... maybe historic reasons....
___
*[core/algorithm-operator/lib/reconcile/normalize.js, line 22 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDrelXB7vFJ12OcSFz:-MPE1d0k2XyeqLUtkmux:b2yynbz) ([raw file](https://github.com/kube-hpc/hkube/blob/e0a353381435fe5f76405c8ab32f0913bfd0c47c/core/algorithm-operator/lib/reconcile/normalize.js#L22)):*
> ```
> .filter(a => a.options && !a.options.pending);
> ```
You are right, it is needed.
I added this to the Mongo query instead, but I got some issues, so I removed it.
___
*[core/pipeline-driver-queue/lib/persistency/persistence.js, line 17 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDv5xtD1s8YXlauC4T:-MPE8vONDzy9RqrnI7-S:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b6af38b697f061fbf9ccc8a1831576e763f6f1de/core/pipeline-driver-queue/lib/persistency/persistence.js#L17)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Change name to this._etcd?
</blockquote></details>

Done.
___
*[core/resource-manager/lib/adapters/settings.js, line 23 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDvR0yCYbjNXpcZ86R:-MPE9GAQ-uLo8Gc5L6ET:b1l4b4j) ([raw file](https://github.com/kube-hpc/hkube/blob/b6af38b697f061fbf9ccc8a1831576e763f6f1de/core/resource-manager/lib/adapters/settings.js#L23)):*
> ```
> cacheTTL: 10
> ```
Because the algorithms stored in a cache, and one of the triggers to update the cache is by watching the ETCD, and since I no longer store the algorithms in ETCD, I need to fetch more frequently.
___
*[core/task-executor/lib/helpers/etcd.js, line 1 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDvkv_20DpNx4m6t7T:-MPE9p1x42Yuz2Zzdlpw:b-io766c) ([raw file](https://github.com/kube-hpc/hkube/blob/b6af38b697f061fbf9ccc8a1831576e763f6f1de/core/task-executor/lib/helpers/etcd.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

rename file?
</blockquote></details>

If I was renaming the file, you wouldn't see the changes :-)
___
*[core/trigger-service/config/main/config.base.js, line 6 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDwXSe6KZGqxDPQWjW:-MPEAJI32d_IxOrrVrdH:buldxxz) ([raw file](https://github.com/kube-hpc/hkube/blob/b6af38b697f061fbf9ccc8a1831576e763f6f1de/core/trigger-service/config/main/config.base.js#L6)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

that's the interval to check if there are any crons to start? or just check if there are new pipelines with crons?
</blockquote></details>

Since I no longer watch ETCD pipelines, I need to do my own watch for add/change/delete pipelines, so I will add/change/stop crons.
___
*[core/worker/lib/states/stateAdapter.js, line 48 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1039#-MPDxDL62LxzHcITeo5H:-MPEAmiu47aaJ6Z6FdLw:b-junu17) ([raw file](https://github.com/kube-hpc/hkube/blob/b6af38b697f061fbf9ccc8a1831576e763f6f1de/core/worker/lib/states/stateAdapter.js#L48)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> this._db.config
> ```
I think it is better to not print username/password to log
</blockquote></details>

This is only host, port, dbName

**Review by yehiyam — APPROVED** [review]
> Reviewed 6 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1039)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maty21)

**Pull request merged**
