### PR TITLE
feat: handle algorithm serving state

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/923)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/923)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/worker/config/main/config.base.js, line 22 at r1](https://reviewable.io/reviews/kube-hpc/hkube/923#-MG7Zv5G8FyCqzkZcs17:-MG7Zv5G8FyCqzkZcs18:bipzpul) ([raw file](https://github.com/kube-hpc/hkube/blob/5db2e87f283df10761e69952881322edb15ba918/core/worker/config/main/config.base.js#L22)):*
> ```JavaScript
> 
> config.pollingInterval = process.env.POLLING_INTERVAL || 100;
> config.servingReportInterval = formatters.parseInt(process.env.DISCOVERY_SERVING_REPORT_INTERVAL, 5000);
> ```

we should remember to add this to the helm chart
Do we need to add it in task-executor, or it will add all envs from the configmap?
___
*[core/worker/lib/worker.js, line 143 at r1](https://reviewable.io/reviews/kube-hpc/hkube/923#-MG7Zf_k01qI6TbH4XhU:-MG7Zf_k01qI6TbH4XhV:b-dufeyx) ([raw file](https://github.com/kube-hpc/hkube/blob/5db2e87f283df10761e69952881322edb15ba918/core/worker/lib/worker.js#L143)):*
> ```
> Date.now() - last
> ```
put () for more readability

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/923)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/worker/config/main/config.base.js, line 22 at r1](https://reviewable.io/reviews/kube-hpc/hkube/923#-MG7Zv5G8FyCqzkZcs17:-MG7_gf63JXCd7nSHKvi:blqk9tn) ([raw file](https://github.com/kube-hpc/hkube/blob/5db2e87f283df10761e69952881322edb15ba918/core/worker/config/main/config.base.js#L22)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

we should remember to add this to the helm chart
Do we need to add it in task-executor, or it will add all envs from the configmap?
</blockquote></details>

We need to add it to the template in task-executor 
task-executor/lib/templates/worker.js

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/923)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/worker/config/main/config.base.js, line 22 at r1](https://reviewable.io/reviews/kube-hpc/hkube/923#-MG7Zv5G8FyCqzkZcs17:-MG7kSvR9d5ufMVidtfr:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/5db2e87f283df10761e69952881322edb15ba918/core/worker/config/main/config.base.js#L22)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

We need to add it to the template in task-executor 
task-executor/lib/templates/worker.js
</blockquote></details>

Done.
___
*[core/worker/lib/worker.js, line 143 at r1](https://reviewable.io/reviews/kube-hpc/hkube/923#-MG7Zf_k01qI6TbH4XhU:-MG7lA114w8A2WVzC2mt:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/5db2e87f283df10761e69952881322edb15ba918/core/worker/lib/worker.js#L143)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> Date.now() - last
> ```
put () for more readability
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
