### PR TITLE
feat: make versions work with id

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992)* status: all files reviewed, 9 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/api/rest-api/app-server.js, line 69 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYf8c99yNE3kRfSnF_:-MKYf8c99yNE3kRfSnFa:bw56gww) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/api/rest-api/app-server.js#L69)):*
> ```
> 🚀
> ```
really? :-)
___
*[core/api-server/api/rest-api/routes/v1/versions.js, line 21 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYfnfX8Huek13n3T8U:-MKYfnfX8Huek13n3T8V:b-6y827z) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/api/rest-api/routes/v1/versions.js#L21)):*
> ```
> id
> ```
id is the version or the tag?
___
*[core/api-server/api/rest-api/routes/v1/versions.js, line 37 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYftKbAe25nOzy0IZJ:-MKYftKbAe25nOzy0IZK:bh4ul3u) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/api/rest-api/routes/v1/versions.js#L37)):*
> ```JavaScript
>     router.delete('/algorithms/:name/:id', logger(), async (req, res, next) => {
>         const { id, name } = req.params;
>         const response = await versionsService.deleteVersion({ id, name });
> ```

Is this route used to delete version or algorithm?
___
*[core/api-server/lib/service/algorithms.js, line 35 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYmIz-EkzliHLn9ccy:-MKYmIz-EkzliHLn9ccz:b-dqiteo) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/lib/service/algorithms.js#L35)):*
> ```
> algorithmVersion
> ```
should be algorithmVersions
___
*[core/api-server/lib/service/algorithms.js, line 278 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYnecZ8QotNc7X5BRM:-MKYnecZ8QotNc7X5BRN:bsx9b9x) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/lib/service/algorithms.js#L278)):*
> ```
> algorithm.options.debug
> ```
I don't think we need a version for debug. 
___
*[core/api-server/lib/service/algorithms.js, line 278 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYoG4E6Pg_VdIVQhix:-MKYoG4E6Pg_VdIVQhiy:bsj3ax3) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/lib/service/algorithms.js#L278)):*
> ```
> !buildId
> ```
why not when there is a build? the version is created after the build is done?
___
*[core/api-server/lib/service/builds.js, line 183 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYptKg4yX92goCiwyJ:-MKYptKg4yX92goCiwyK:bhwl82u) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/lib/service/builds.js#L183)):*
> ```JavaScript
> 
>     _formatDiff(algorithm) {
>         const { fileInfo, env, gitRepository } = algorithm;
> ```

maybe add baseImage also?
___
*[core/api-server/tests/algorithms-store.js, line 1692 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYtFJY96jcI4Nd7A3a:-MKYtFJY96jcI4Nd7A3b:bm425x3) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/tests/algorithms-store.js#L1692)):*
> ```JavaScript
>                 const res3 = await request(req3);
>                 const res4 = await request(req4);
>                 const versions1 = res4.body.map(v => v.id).sort();
> ```

why do you need sort? versions are not returned in the order they were created?
___
*[core/api-server/tests/versions.js, line 295 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYtcA8DkzteZhplWAF:-MKYtcA8DkzteZhplWAG:bves7q6) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/tests/versions.js#L295)):*
> ```JavaScript
>             expect(res.body.error.message).to.equal(`version no-such Not Found`);
>         });
>         it('should succeed to tag version', async () => {
> ```

should add tests to delete tags and to change tags

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992)* status: 11 of 36 files reviewed, 9 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/api/rest-api/app-server.js, line 69 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYf8c99yNE3kRfSnF_:-MKYuK_P1sJOsyMY0mKu:b2nh4j5) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/api/rest-api/app-server.js#L69)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> 🚀
> ```
really? :-)

</blockquote></details>

:-)
___
*[core/api-server/api/rest-api/routes/v1/versions.js, line 21 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYfnfX8Huek13n3T8U:-MKYuQB2EEhVHi6wVt6b:bmb1cj4) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/api/rest-api/routes/v1/versions.js#L21)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> id
> ```
id is the version or the tag?
</blockquote></details>

version (uid length of 10)
___
*[core/api-server/api/rest-api/routes/v1/versions.js, line 37 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYftKbAe25nOzy0IZJ:-MKYuY-ZAQwPhrFplk40:b-tofikt) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/api/rest-api/routes/v1/versions.js#L37)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is this route used to delete version or algorithm?
</blockquote></details>

version
___
*[core/api-server/lib/service/algorithms.js, line 35 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYmIz-EkzliHLn9ccy:-MKZcPza86VVwz-1vtB_:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/lib/service/algorithms.js#L35)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> algorithmVersion
> ```
should be algorithmVersions
</blockquote></details>

Done.
___
*[core/api-server/lib/service/algorithms.js, line 278 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYnecZ8QotNc7X5BRM:-MKYxZxG4UFQqQQvzlXG:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/lib/service/algorithms.js#L278)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> algorithm.options.debug
> ```
I don't think we need a version for debug. 
</blockquote></details>

Done.
___
*[core/api-server/lib/service/algorithms.js, line 278 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYoG4E6Pg_VdIVQhix:-MKZcWrs38S_Te0UIjIT:b2nhswy) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/lib/service/algorithms.js#L278)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> !buildId
> ```
why not when there is a build? the version is created after the build is done?
</blockquote></details>

Yes
___
*[core/api-server/lib/service/builds.js, line 183 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYptKg4yX92goCiwyJ:-MKZcYjl9YWo5qn5ZAuS:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/lib/service/builds.js#L183)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

maybe add baseImage also?
</blockquote></details>

Done.
___
*[core/api-server/tests/algorithms-store.js, line 1692 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYtFJY96jcI4Nd7A3a:-MKZcweVEqkZvUesIhLU:b-yxrkau) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/tests/algorithms-store.js#L1692)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why do you need sort? versions are not returned in the order they were created?
</blockquote></details>

Yes, but desc... Done
___
*[core/api-server/tests/versions.js, line 295 at r1](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKYtcA8DkzteZhplWAF:-MKZfuvB09yf9mAJRDnc:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/8d79cc8289c4f019ecb6d93a438ae6883ec0a812/core/api-server/tests/versions.js#L295)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

should add tests to delete tags and to change tags
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/api/rest-api/swagger/definitions/algorithmApplyOptions.yaml, line 5 at r2](https://reviewable.io/reviews/kube-hpc/hkube/992#-MK_0ObU93i8cfZLqiqn:-MK_0ObU93i8cfZLqiqo:b-k0h5gs) ([raw file](https://github.com/kube-hpc/hkube/blob/a6f55f95fa14072abd0b5a5ab1d5a6bd59b4d576/core/api-server/api/rest-api/swagger/definitions/algorithmApplyOptions.yaml#L5)):*
> ```
> should replace the current image with this image
> ```
should set the newly created version as current
___
*[core/api-server/lib/service/versions.js, line 86 at r2](https://reviewable.io/reviews/kube-hpc/hkube/992#-MK_17qW1xP889LmdBr4:-MK_17qW1xP889LmdBr5:b213jbe) ([raw file](https://github.com/kube-hpc/hkube/blob/a6f55f95fa14072abd0b5a5ab1d5a6bd59b4d576/core/api-server/lib/service/versions.js#L86)):*
> ```
> versions && versions[0] && versions[0].version
> ```
versions?.[0]?.versions

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992)* status: 32 of 37 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/api/rest-api/swagger/definitions/algorithmApplyOptions.yaml, line 5 at r2](https://reviewable.io/reviews/kube-hpc/hkube/992#-MK_0ObU93i8cfZLqiqn:-MKd-cre3x09vF3BVvfU:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/a6f55f95fa14072abd0b5a5ab1d5a6bd59b4d576/core/api-server/api/rest-api/swagger/definitions/algorithmApplyOptions.yaml#L5)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> should replace the current image with this image
> ```
should set the newly created version as current
</blockquote></details>

Done.
___
*[core/api-server/lib/service/versions.js, line 86 at r2](https://reviewable.io/reviews/kube-hpc/hkube/992#-MK_17qW1xP889LmdBr4:-MKd-lx42S9Zw4hFQ7Pt:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/a6f55f95fa14072abd0b5a5ab1d5a6bd59b4d576/core/api-server/lib/service/versions.js#L86)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> versions && versions[0] && versions[0].version
> ```
versions?.[0]?.versions
</blockquote></details>

Done.

**Review by yehiyam — COMMENTED** [review]
> Reviewed 6 of 7 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992)* status: 38 of 39 files reviewed, all discussions resolved (waiting on @yehiyam)

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/lib/service/versions.js, line 98 at r5](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKiMwTtAsSliHIYsFGA:-MKiMwTtAsSliHIYsFGB:b2hfplu) ([raw file](https://github.com/kube-hpc/hkube/blob/7cd9f9fc7d5d30489ffcabb8815554c7985145d4/core/api-server/lib/service/versions.js#L98)):*
> ```JavaScript
> 
>         try {
>             semver = await this._lockSemver(name, semver);
> ```

what happens if not successful 3 times?
___
*[core/api-server/lib/service/versions.js, line 118 at r5](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKiN2R6DrNeLoWdDykf:-MKiN2R6DrNeLoWdDykg:b-nm9z8e) ([raw file](https://github.com/kube-hpc/hkube/blob/7cd9f9fc7d5d30489ffcabb8815554c7985145d4/core/api-server/lib/service/versions.js#L118)):*
> ```JavaScript
>     }
> 
>     async _lockSemver(name, semver) {
> ```

perhaps put this method in stateManager?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/lib/service/versions.js, line 98 at r5](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKiMwTtAsSliHIYsFGA:-MKiR0iH6IuBZrlTqEHG:b-93udc8) ([raw file](https://github.com/kube-hpc/hkube/blob/7cd9f9fc7d5d30489ffcabb8815554c7985145d4/core/api-server/lib/service/versions.js#L98)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

what happens if not successful 3 times?
</blockquote></details>

It gets the latest incremented semver.
If you will run the test `should create multiple versions in concurrent mode` you will see that happens. 
The test simulate 4 parallel requests, and gets ['1.0.3', '1.0.2', '1.0.1', '1.0.0']
If I will run 5 parallel requests I will get ['1.0.3', '1.0.3', '1.0.2', '1.0.1', '1.0.0'] which is not so good.

So I can change it to max 5 attempts, anyway, we have a rate-limiter of 5 requests...
___
*[core/api-server/lib/service/versions.js, line 118 at r5](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKiN2R6DrNeLoWdDykf:-MKiS4YD2IWkIvkM4Oxl:b-bi6vlr) ([raw file](https://github.com/kube-hpc/hkube/blob/7cd9f9fc7d5d30489ffcabb8815554c7985145d4/core/api-server/lib/service/versions.js#L118)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

perhaps put this method in stateManager?
</blockquote></details>

This method call inside to `_incSemver();` (I can use cb)
But anyway this is a specific logic to versions.

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992)* status: 36 of 38 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/lib/service/versions.js, line 98 at r5](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKiMwTtAsSliHIYsFGA:-MKiVarH8fBAg-aOwqgc:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/7cd9f9fc7d5d30489ffcabb8815554c7985145d4/core/api-server/lib/service/versions.js#L98)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

It gets the latest incremented semver.
If you will run the test `should create multiple versions in concurrent mode` you will see that happens. 
The test simulate 4 parallel requests, and gets ['1.0.3', '1.0.2', '1.0.1', '1.0.0']
If I will run 5 parallel requests I will get ['1.0.3', '1.0.3', '1.0.2', '1.0.1', '1.0.0'] which is not so good.

So I can change it to max 5 attempts, anyway, we have a rate-limiter of 5 requests...

</blockquote></details>

Done.
___
*[core/api-server/lib/service/versions.js, line 118 at r5](https://reviewable.io/reviews/kube-hpc/hkube/992#-MKiN2R6DrNeLoWdDykf:-MKiVgxkD-C6UjrEvUTk:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/7cd9f9fc7d5d30489ffcabb8815554c7985145d4/core/api-server/lib/service/versions.js#L118)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

This method call inside to `_incSemver();` (I can use cb)
But anyway this is a specific logic to versions.
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/992#-:-MKiWknIDNvNPbk6TyQT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
