### PR TITLE
restart on error

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1537)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1537)* status: all files reviewed, 6 unresolved discussions (waiting on @golanha)

___
*[core/algorithm-queue/config/main/config.base.js, line 8 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MwgEg3V6jiHv7ft8vBc:-MwgEg3W4mdQhBRxBjtJ:b-1lcjeh) ([raw file](https://github.com/kube-hpc/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/algorithm-queue/config/main/config.base.js#L8)):*
> ```JavaScript
> config.serviceName = packageJson.name;
> const useSentinel = !!process.env.REDIS_SENTINEL_SERVICE_HOST;
> config.queueId = process.env.QUEUE_ID || 'stam';
> ```

don't leave it here
___
*[core/pipeline-driver/lib/state/db.js, line 1 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MwgEuFG0xP5OldzgNI6:-MwgEuFG0xP5OldzgNI7:b797n5u) ([raw file](https://github.com/kube-hpc/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/state/db.js#L1)):*
> ```JavaScript
> const { MongoError } = require('mongodb/lib/core/error');
> ```

I think it is better to add this to the db package, and remove the direct reference to mongo
___
*[core/pipeline-driver/lib/state/db.js, line 17 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MwgF92VEYAVoWWqVxZ5:-MwgF92VEYAVoWWqVxZ6:b-2csxj) ([raw file](https://github.com/kube-hpc/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/state/db.js#L17)):*
> ```JavaScript
>     _exitOnConnectionError(error) {
>         if (error instanceof MongoError) {
>             log.error('db unreachable');
> ```

add `{component}` and error message to the log
___
*[core/pipeline-driver/lib/state/db.js, line 18 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MwgFm2T8Lepki3MpTJs:-MwgFm2T8Lepki3MpTJt:bh98ai7) ([raw file](https://github.com/kube-hpc/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/state/db.js#L18)):*
> ```JavaScript
>         if (error instanceof MongoError) {
>             log.error('db unreachable');
>             process.exit(1);
> ```

In 1.3 when there is an ETCD error first call some cleanup code
https://github.com/kube-HPC/hkube/blob/7d9caa201e4ad825344e4141be98a11249e015a8/core/pipeline-driver/lib/tasks/task-runner.js#L189
___
*[core/pipeline-driver/lib/state/state-manager.js, line 9 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MwgGPQc6axeMpsdvbQ-:-MwgGPQc6axeMpsdvbQ0:b-7v2v4d) ([raw file](https://github.com/kube-hpc/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/state/state-manager.js#L9)):*
> ```JavaScript
> const { pipelineStatuses } = require('@hkube/consts');
> const storageManager = require('@hkube/storage-manager');
> const { GRPCGenericError, EtcdError } = require('@hkube/etcd/node_modules/etcd3');
> ```

again, better to not reference ETCD directly
If you decide to leave it like this at least add it as a direct dependency and don't require in the package's node_modules
___
*[core/pipeline-driver/lib/state/state-manager.js, line 329 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MwgOybR3T14Rk9XW2ON:-MwgOybR3T14Rk9XW2OO:bovx1z0) ([raw file](https://github.com/kube-hpc/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/state/state-manager.js#L329)):*
> ```JavaScript
>         await db.createJob({ jobId, pipeline, status });
>         try {
>             await this._etcd.jobs.status.set({ jobId, ...status });
> ```

this code repeats itself. Maybe find a way to wrap the `_etcd.XXX` calls 



_Code quote:_
```JavaScript
        try {
            await this._etcd.jobs.status.set({ jobId, ...status });
        }
        catch (e) {
            this._exitOnEtcdProblem(e);
            throw e;
        }
```

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1537)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/pipeline-driver/lib/state/db.js, line 17 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MwgF92VEYAVoWWqVxZ5:-MxDkjmFDJFJ5w3kccbu:bks1y79) ([raw file](https://github.com/kube-hpc/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/state/db.js#L17)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

also add the `error` as additional parameter (like [here](https://github.com/kube-HPC/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/tasks/task-runner.js#L136))
___
*[core/pipeline-driver/lib/state/db.js, line 48 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxDl7yw69-Qu2a4M_Uh:-MxDl7yxBe24wnU49oWh:bd8idfn) ([raw file](https://github.com/kube-hpc/hkube/blob/172825a30582f0d6a292f8bb4a76ffd2c837bb91/core/pipeline-driver/lib/state/db.js#L48)):*
> ```JavaScript
> 
>     _wrapJobsService() {
>         Object.getOwnPropertyNames(Object.getPrototypeOf(this._db.jobs)).forEach(propertyName => {
> ```

Same as for the ETCD. I think it is better to wrap the specific methods in this file and not all of the methods in the package
___
*[core/pipeline-driver/lib/state/state-manager.js, line 30 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxEAOD_DzUN7YVuM216:-MxEAOD_DzUN7YVuM217:b-1rah5v) ([raw file](https://github.com/kube-hpc/hkube/blob/172825a30582f0d6a292f8bb4a76ffd2c837bb91/core/pipeline-driver/lib/state/state-manager.js#L30)):*
> ```JavaScript
>         this._subscribe();
>         this._watchDrivers();
>         this._graphStore = new GraphStore();
> ```

You need to get the real graphstore. not create a new one
___
*[core/pipeline-driver/lib/state/state-manager.js, line 63 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxDibaj79Fiw4tKae34:-MxDibaj79Fiw4tKae35:by9tba4) ([raw file](https://github.com/kube-hpc/hkube/blob/172825a30582f0d6a292f8bb4a76ffd2c837bb91/core/pipeline-driver/lib/state/state-manager.js#L63)):*
> ```JavaScript
>         const services = [this._etcd.discovery, this._etcd.jobs.results, this._etcd.jobs.status, this._etcd.jobs.tasks, this._etcd.drivers, this._etcd.streaming.statistics];
> 
>         const inheritedPropertyNames = Object.getOwnPropertyNames(Service.prototype);
> ```

you assume a lot about the internals of the `etcd` package. For instance, that there is a `Service` base class, and that all methods that you want to wrap are in the base
Like I wrote in the etcd PR, I think it will be better (more readable, less error prone to future changes in the package, and more specific to the needs here) to wrap the methods in `state-manager` and not in the package 
___
*[core/pipeline-driver/lib/state/state-manager.js, line 227 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxDjGAnEb7v6BSDrG6N:-MxDjGAnEb7v6BSDrG6O:b59x51s) ([raw file](https://github.com/kube-hpc/hkube/blob/172825a30582f0d6a292f8bb4a76ffd2c837bb91/core/pipeline-driver/lib/state/state-manager.js#L227)):*
> ```JavaScript
>     async _exitOnEtcdProblem(e) {
>         if (this._etcd.isFatal(e)) {
>             log.error(`ETCD unreachable ${e}`, { component });
> ```

add `error` property as additional parameter (like [here](https://github.com/kube-HPC/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/tasks/task-runner.js#L136))

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1537)* status: 3 of 9 files reviewed, 9 unresolved discussions (waiting on @yehiyam)

___
*[core/pipeline-driver/lib/state/db.js, line 17 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MwgF92VEYAVoWWqVxZ5:-MxEnnXp07HSKG78U8Yh:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/state/db.js#L17)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

also add the `error` as additional parameter (like [here](https://github.com/kube-HPC/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/tasks/task-runner.js#L136))
</blockquote></details>

Done.
___
*[core/pipeline-driver/lib/state/db.js, line 48 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxDl7yw69-Qu2a4M_Uh:-MxEnp8L6EcWRoTYSll_:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/172825a30582f0d6a292f8bb4a76ffd2c837bb91/core/pipeline-driver/lib/state/db.js#L48)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Same as for the ETCD. I think it is better to wrap the specific methods in this file and not all of the methods in the package
</blockquote></details>

Done.
___
*[core/pipeline-driver/lib/state/state-manager.js, line 30 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxEAOD_DzUN7YVuM216:-MxEFwCB2VLLNESFCWEq:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/172825a30582f0d6a292f8bb4a76ffd2c837bb91/core/pipeline-driver/lib/state/state-manager.js#L30)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

You need to get the real graphstore. not create a new one
</blockquote></details>

Done.
___
*[core/pipeline-driver/lib/state/state-manager.js, line 63 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxDibaj79Fiw4tKae34:-MxEG1Px8jGy4pBVUy-6:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/172825a30582f0d6a292f8bb4a76ffd2c837bb91/core/pipeline-driver/lib/state/state-manager.js#L63)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

you assume a lot about the internals of the `etcd` package. For instance, that there is a `Service` base class, and that all methods that you want to wrap are in the base
Like I wrote in the etcd PR, I think it will be better (more readable, less error prone to future changes in the package, and more specific to the needs here) to wrap the methods in `state-manager` and not in the package 
</blockquote></details>

Done.
___
*[core/pipeline-driver/lib/state/state-manager.js, line 227 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxDjGAnEb7v6BSDrG6N:-MxEnls-BNNia5qH7KCF:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/172825a30582f0d6a292f8bb4a76ffd2c837bb91/core/pipeline-driver/lib/state/state-manager.js#L227)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

add `error` property as additional parameter (like [here](https://github.com/kube-HPC/hkube/blob/31e8528dcaa99cc0eb2b8f0a6fe4bde651d83767/core/pipeline-driver/lib/tasks/task-runner.js#L136))
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1537)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/pipeline-driver/lib/state/state-manager.js, line 32 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxU2dXU4u9E-BDsdT6Q:-MxU2dXU4u9E-BDsdT6R:b-vihjy7) ([raw file](https://github.com/kube-hpc/hkube/blob/2087694c57cb29379bd95394328d7aec20ca8e1c/core/pipeline-driver/lib/state/state-manager.js#L32)):*
> ```JavaScript
> 
>     setCurrentTask(task) {
>         this._currentTask = task;
> ```

This will not work. There could be many task runners active at the same time.



_Code quote:_
```JavaScript
    setCurrentTask(task) {
        this._currentTask = task;
    }
```
___
*[core/pipeline-driver/lib/tasks/task-runner.js, line 134 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxU2vpu9pmDgOkSwQhY:-MxU2vpu9pmDgOkSwQhZ:b-vihjy7) ([raw file](https://github.com/kube-hpc/hkube/blob/2087694c57cb29379bd95394328d7aec20ca8e1c/core/pipeline-driver/lib/tasks/task-runner.js#L134)):*
> ```JavaScript
> 
>     async start(job) {
>         stateManager.setCurrentTask(this);
> ```

This will not work. There could be many task runners active at the same time.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1537)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/pipeline-driver/lib/state/state-manager.js, line 32 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxU2dXU4u9E-BDsdT6Q:-MxU_7iu21jrmqOpxHGd:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2087694c57cb29379bd95394328d7aec20ca8e1c/core/pipeline-driver/lib/state/state-manager.js#L32)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This will not work. There could be many task runners active at the same time.
</blockquote></details>

Done.
___
*[core/pipeline-driver/lib/tasks/task-runner.js, line 134 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxU2vpu9pmDgOkSwQhY:-MxU_8c7-UHAQGEP19-C:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2087694c57cb29379bd95394328d7aec20ca8e1c/core/pipeline-driver/lib/tasks/task-runner.js#L134)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This will not work. There could be many task runners active at the same time.
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1537)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[core/pipeline-driver/lib/consumer/jobs-consumer.js, line 156 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxYXY_SAcw9ZiBuvkjI:-MxYXY_SAcw9ZiBuvkjJ:b-i0f7x7) ([raw file](https://github.com/kube-hpc/hkube/blob/04042685995e1ba63a2ef276026fac3298c53f43/core/pipeline-driver/lib/consumer/jobs-consumer.js#L156)):*
> ```JavaScript
>     }
> 
>     async getTaskRunner() {
> ```

better in plural (getTaskRunners)
___
*[core/pipeline-driver/lib/state/state-manager.js, line 29 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxYVrwhAibElKOJEtKl:-MxYVrwhAibElKOJEtKm:bmrgk9k) ([raw file](https://github.com/kube-hpc/hkube/blob/04042685995e1ba63a2ef276026fac3298c53f43/core/pipeline-driver/lib/state/state-manager.js#L29)):*
> ```JavaScript
>         this._watchDrivers();
>         // eslint-disable-next-line global-require
>         this.jobConsumer = require('../consumer/jobs-consumer');
> ```

1. don't require in the middle of the file
2. You are creating a circular dependency of imports consumer => stateManager => consumer
___
*[core/pipeline-driver/lib/state/state-manager.js, line 223 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxYXIRI62lxAIKJcQoz:-MxYXIRI62lxAIKJcQp-:b-csotq4) ([raw file](https://github.com/kube-hpc/hkube/blob/04042685995e1ba63a2ef276026fac3298c53f43/core/pipeline-driver/lib/state/state-manager.js#L223)):*
> ```JavaScript
>             log.error(`ETCD problem ${e.message}`, { component }, e);
>             const taskRunners = this.jobConsumer.getTaskRunner();
>             await Promise.all(Object.values(taskRunners).map((taskRunner) => {
> ```

taskRunners is a `Map`. I don't think that `Object.values` will return the values of the map

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1537)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/pipeline-driver/lib/consumer/jobs-consumer.js, line 156 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxYXY_SAcw9ZiBuvkjI:-MxYl9pS9bE-liG3pG0t:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/04042685995e1ba63a2ef276026fac3298c53f43/core/pipeline-driver/lib/consumer/jobs-consumer.js#L156)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

better in plural (getTaskRunners)
</blockquote></details>

Done.
___
*[core/pipeline-driver/lib/state/state-manager.js, line 29 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxYVrwhAibElKOJEtKl:-MxYeuT03DF18R6i375C:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/04042685995e1ba63a2ef276026fac3298c53f43/core/pipeline-driver/lib/state/state-manager.js#L29)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

1. don't require in the middle of the file
2. You are creating a circular dependency of imports consumer => stateManager => consumer
</blockquote></details>

Done.
___
*[core/pipeline-driver/lib/state/state-manager.js, line 223 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1537#-MxYXIRI62lxAIKJcQoz:-MxYl8Rz4ajGVtJiVeio:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/04042685995e1ba63a2ef276026fac3298c53f43/core/pipeline-driver/lib/state/state-manager.js#L223)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

taskRunners is a `Map`. I don't think that `Object.values` will return the values of the map
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1537#-:-MxYm7hw-pAfHbQNtV7U:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
