### PR TITLE
Stateless nodes scale

### PR DESCRIPTION
**Pull request by RonShvarz**
Handle stateless nodes with minStatelessCount and create tasks for immidiate availability

Uses the new dag package 2.2.2

kube-HPC/hkube#1765

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1772)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1772)* status: 15 of 17 files reviewed, 1 unresolved discussion (waiting on @RonShvarz)

___
*[`core/pipeline-driver/lib/producer/jobs-producer.js` line 48 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1772#-NbiR9DL8JlGjQSYTzdq:-NbiR9DL8JlGjQSYTzdr:bubrooe) ([raw file](https://github.com/kube-HPC/hkube/blob/6d4eb367fdb6a6fa06dc2994b72061aa815c6c60/core/pipeline-driver/lib/producer/jobs-producer.js#L48)):*
> ```JavaScript
>             }
>             else if (statelessList) {
>                 tasks = statelessList.map(s => ({ taskId: s.taskId, status: s.status, input: s.input, statelessIndex: s.statelessIndex, storage: s.storage }));
> ```

remove the statelessindex



_Code quote:_
```JavaScript
 statelessIndex: s.statelessIndex,
```

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1772)* status: 15 of 17 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`core/pipeline-driver/lib/producer/jobs-producer.js` line 48 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1772#-NbiR9DL8JlGjQSYTzdq:-Nbie5S866tuBdj42-mW:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/6d4eb367fdb6a6fa06dc2994b72061aa815c6c60/core/pipeline-driver/lib/producer/jobs-producer.js#L48)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

remove the statelessindex
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1772)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RonShvarz)

**Pull request merged**
