### PR TITLE
Preferred adjustment

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @golanha and @NassiHarel)

___
*[core/pipeline-driver-queue/lib/jobs/consumer.js, line 55 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuL91z12Y76f5lTs-b9:-MuL91z12Y76f5lTs-bA:b71yawb) ([raw file](https://github.com/kube-hpc/hkube/blob/832c264beb9c6a498f6cc1ed1f05a4600f4a2925/core/pipeline-driver-queue/lib/jobs/consumer.js#L55)):*
> ```JavaScript
>             const { jobId } = job.data;
>             const jobData = await dataStore.getJob({ jobId });
>             const { status, pipeline, tags } = jobData || {};
> ```

job doesn't have tags



_Code quote:_
```JavaScript
 tags 
```

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/pipeline-driver-queue/lib/queue.js, line 31 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuL9UQ76ACC3xfPzlpH:-MuL9UQ76ACC3xfPzlpI:b-n0gkvc) ([raw file](https://github.com/kube-hpc/hkube/blob/832c264beb9c6a498f6cc1ed1f05a4600f4a2925/core/pipeline-driver-queue/lib/queue.js#L31)):*
> ```JavaScript
>     }
> 
>     async persistencyLoad(ordered) {
> ```

Where do you call with this params



_Code quote:_
```JavaScript
ordered
```

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 4 of 6 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: all files reviewed, 5 unresolved discussions (waiting on @golanha)

___
*[core/pipeline-driver-queue/lib/graceful-shutdown.js, line 14 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuLE0_o-S9YKrLfoU_9:-MuLE0_o-S9YKrLfoU_A:ba703fz) ([raw file](https://github.com/kube-hpc/hkube/blob/573d965aec3d951a696a6af434cc44491e73a406/core/pipeline-driver-queue/lib/graceful-shutdown.js#L14)):*
> ```JavaScript
>             await producer.shutdown();
>             if (queueRunner.queue) {
>                 // await queueRunner.queue.persistenceStore();
> ```

dont leave code in comments



_Code quote:_
```JavaScript
// await queueRunner.queue.persistenceStore();
```
___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 73 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuLDPd2-QFwbco6pZ5X:-MuLDPd2-QFwbco6pZ5Y:b-pw3gt6) ([raw file](https://github.com/kube-hpc/hkube/blob/573d965aec3d951a696a6af434cc44491e73a406/core/pipeline-driver-queue/lib/jobs/producer.js#L73)):*
> ```JavaScript
>             let data = queueRunner.queue.getQueue();
>             let managedData = data.map(q => {
>                 const { calculated, ...rest } = q;
> ```

I dont think you need this



_Code quote:_
```JavaScript
            let managedData = data.map(q => {
                const { calculated, ...rest } = q;
                const result = { ...rest };
                return result;
            });
```
___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 80 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuLDT3k7WdzRCPIPGCi:-MuLDT3k7WdzRCPIPGCj:b-pw3gt6) ([raw file](https://github.com/kube-hpc/hkube/blob/573d965aec3d951a696a6af434cc44491e73a406/core/pipeline-driver-queue/lib/jobs/producer.js#L80)):*
> ```JavaScript
>             const preferredData = data.map(q => {
>                 const { calculated, ...rest } = q;
>                 const result = { score: 1, ...rest };
> ```

I dont think you need this



_Code quote:_
```JavaScript
            const preferredData = data.map(q => {
                const { calculated, ...rest } = q;
                const result = { score: 1, ...rest };
                return result;
            });
```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: all files reviewed, 5 unresolved discussions (waiting on @NassiHarel)

___
*[core/pipeline-driver-queue/lib/graceful-shutdown.js, line 14 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuLE0_o-S9YKrLfoU_9:-MuLJXRH185C3m-xibxK:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/573d965aec3d951a696a6af434cc44491e73a406/core/pipeline-driver-queue/lib/graceful-shutdown.js#L14)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

dont leave code in comments
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/queue.js, line 31 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuL9UQ76ACC3xfPzlpH:-MuLC18e-Px310DhNw8z:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/832c264beb9c6a498f6cc1ed1f05a4600f4a2925/core/pipeline-driver-queue/lib/queue.js#L31)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Where do you call with this params
</blockquote></details>

Done.



_Code quote:_
```JavaScript
persistencyLoad
```
___
*[core/pipeline-driver-queue/lib/jobs/consumer.js, line 55 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuL91z12Y76f5lTs-b9:-MuLJZMn9PxdtKz3El4b:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/832c264beb9c6a498f6cc1ed1f05a4600f4a2925/core/pipeline-driver-queue/lib/jobs/consumer.js#L55)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

job doesn't have tags
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 73 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuLDPd2-QFwbco6pZ5X:-MuLQTDAC1AGcHoolQqo:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/573d965aec3d951a696a6af434cc44491e73a406/core/pipeline-driver-queue/lib/jobs/producer.js#L73)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I dont think you need this
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 80 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuLDT3k7WdzRCPIPGCi:-MuLQTzG-oBcWonnwGdy:blv93my) ([raw file](https://github.com/kube-hpc/hkube/blob/573d965aec3d951a696a6af434cc44491e73a406/core/pipeline-driver-queue/lib/jobs/producer.js#L80)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I dont think you need this
</blockquote></details>

I put sore 1 so that the resource manager takes it in to account, is that right?

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: all files reviewed, 4 unresolved discussions (waiting on @golanha)

___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 74 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuLbA4b370TlVoVsv2i:-MuLbA4c6_2rgZ60J8qb:b-fawk9z) ([raw file](https://github.com/kube-hpc/hkube/blob/38481243bc8353262b75070d4c8206429266bdb1/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L74)):*
> ```JavaScript
>             const deletedArr = queueRunner.preferredQueue.dequeue({ jobId });
>             if (deletedArr.length > 0) {
>                 const { pipelineName, experimentName, priority, maxExceeded, ...rest } = { ...deletedArr[0] };
> ```

Why not just move the job from one queue to another?



_Code quote:_
```JavaScript
 const { pipelineName, experimentName, priority, maxExceeded, ...rest } = { ...deletedArr[0] };
```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: 7 of 10 files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 80 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuLDT3k7WdzRCPIPGCi:-MuLfcHKBqdqPr1je-_c:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/573d965aec3d951a696a6af434cc44491e73a406/core/pipeline-driver-queue/lib/jobs/producer.js#L80)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

>  1 so that the resource manager take
I think it's better to set the score to 1 when you enqueue the job
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 74 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuL_Q0I7r64GX1vFEiX:-MuLboqI3swk-q-6cjgg:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/38481243bc8353262b75070d4c8206429266bdb1/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L74)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

no such parameter anymore
</blockquote></details>

Done.



_Code quote:_
```JavaScript
maxExceeded
```
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 74 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuLbA4b370TlVoVsv2i:-MuLc6Cu24sXKg_8_bBk:b-houek4) ([raw file](https://github.com/kube-hpc/hkube/blob/38481243bc8353262b75070d4c8206429266bdb1/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L74)):*
>  const { pipelineName, experimentName, priority, maxExceeded, ...rest } = { ...deletedArr[0] };
you want scoreHeuristic to run when a job enters the regular queue, so I use enqueue to make sure things that need to happen, do.
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 136 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuL_G2w9seDjEAskCkg:-MuLe164AuMG1InQhGan:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/38481243bc8353262b75070d4c8206429266bdb1/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L136)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

This `dataStore.setJobNext` is async function, but used like sync function
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[core/pipeline-driver-queue/lib/persistency/data-store.js, line 63 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuM24Sc3C_4GEl0ZWUA:-MuM24Sc3C_4GEl0ZWUB:b-vq902i) ([raw file](https://github.com/kube-hpc/hkube/blob/32b55a385f26bd7baf57bf0b46f849d4731fbbe3/core/pipeline-driver-queue/lib/persistency/data-store.js#L63)):*
> ```JavaScript
> 
>     async setJobNext(jobId, next) {
>         return this._db.jobs.updateNext(jobId, next);
> ```

Did you update the package with this new function?



_Code quote:_
```JavaScript
return this._db.jobs.updateNext(jobId, next);
```
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 131 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuM0Tpu-72isT5F1Z9u:-MuM0Tpv3sxaxw62iZ9J:b-beopi3) ([raw file](https://github.com/kube-hpc/hkube/blob/32b55a385f26bd7baf57bf0b46f849d4731fbbe3/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L131)):*
> ```JavaScript
>             const dequeued = queueRunner.queue.dequeue({ jobId: id });
>             if (dequeued.length > 0) {
>                 allDequeued.push({ score: 1, ...dequeued[0] });
> ```

There are two mistakes in this single line of code

1) the order is important `push({  ...dequeued[0], score: 1 });`
you want that the new score will override the old.

2) you are adding the score to the wrong array, you are not using it in the next lines.



_Code quote:_
```JavaScript
allDequeued.push({ score: 1, ...dequeued[0] });
```

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 128 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuM2VPf0J_j_Gg72hmt:-MuM2VPf0J_j_Gg72hmu:bp7foxq) ([raw file](https://github.com/kube-hpc/hkube/blob/32b55a385f26bd7baf57bf0b46f849d4731fbbe3/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L128)):*
> ```JavaScript
>         const index = this.getIndex(position, tag, pipelineName, jobId);
>         const allDequeued = [];
>         Promise.all(jobs.reverse().map(async id => {
> ```

You need await here



_Code quote:_
```JavaScript
Promise.all
```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: 4 of 13 files reviewed, 3 unresolved discussions (waiting on @NassiHarel)

___
*[core/pipeline-driver-queue/lib/persistency/data-store.js, line 63 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuM24Sc3C_4GEl0ZWUA:-MuPiwS5BD3W8aIfLlSQ:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/32b55a385f26bd7baf57bf0b46f849d4731fbbe3/core/pipeline-driver-queue/lib/persistency/data-store.js#L63)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Did you update the package with this new function?
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 128 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuM2VPf0J_j_Gg72hmt:-MuPj5N32c5zO68qZ0fT:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/32b55a385f26bd7baf57bf0b46f849d4731fbbe3/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L128)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

You need await here
</blockquote></details>

Done.



_Code quote:_
```JavaScript
        Promise.all(jobs.reverse().map(async id => {
```
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 131 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuM0Tpu-72isT5F1Z9u:-MuPkEL18byXZNFSla5K:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/32b55a385f26bd7baf57bf0b46f849d4731fbbe3/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L131)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

There are two mistakes in this single line of code

1) the order is important `push({  ...dequeued[0], score: 1 });`
you want that the new score will override the old.

2) you are adding the score to the wrong array, you are not using it in the next lines.
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/pipeline-driver-queue/tests/preffered.js, line 56 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuPmJeYECZ19njHF5S7:-MuPmJeYECZ19njHF5S8:b-ayzwn0) ([raw file](https://github.com/kube-hpc/hkube/blob/7985b343238b0ddfe37b40e0144d8433b9f94964/core/pipeline-driver-queue/tests/preffered.js#L56)):*
> ```JavaScript
>             await Promise.all(jobs.map((job) => dataStore.createJob({ jobId: job.jobId, pipeline, status })));
>             await queueRunner.queue.persistencyLoad();
>             // TODO: these functions should have await
> ```

Add await in all `preferredService.addPreferredJobs`



_Code quote:_
```JavaScript
 // TODO: these functions should have await
```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510)* status: 7 of 13 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/pipeline-driver-queue/tests/preffered.js, line 56 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1510#-MuPmJeYECZ19njHF5S7:-MuPnwVt85I6JOhnpWaN:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/7985b343238b0ddfe37b40e0144d8433b9f94964/core/pipeline-driver-queue/tests/preffered.js#L56)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Add await in all `preferredService.addPreferredJobs`
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1510#-:-MuQDRud0-yyd3hW4rat:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
