### PR TITLE
remove get dependency python and nodejs

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1396)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 2 of 3 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1396)* status: all files reviewed, 5 unresolved discussions (waiting on @golanha)

___
*[core/algorithm-builder/dockerfile/build.sh, line 7 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1396#-MhwfqeQ0q1UgXM7AIqy:-MhwfqeQ0q1UgXM7AIqz:b-oryzdo) ([raw file](https://github.com/kube-hpc/hkube/blob/90bccf681cb55232e1c242e2df2cccca667006c4/core/algorithm-builder/dockerfile/build.sh#L7)):*
> ```Shell
>   # ${SCRIPTPATH}/get-deps-python.sh
>   # ${SCRIPTPATH}/get-deps-nodejs.sh
>   ${SCRIPTPATH}/get-deps-java.sh
> ```

Why do we still need the java deps?
___
*[core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate, line 3 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1396#-Mhwg1JR0g7qCS_B-1Je:-Mhwg1JS-db5AAiD83G5:ba82yij) ([raw file](https://github.com/kube-hpc/hkube/blob/90bccf681cb55232e1c242e2df2cccca667006c4/core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate#L3)):*
> ```
> # First build
> 
> FROM  node:14.5.0 AS wrapper
> ```

this will not work in a disconnected environment. (no node:14.5.0 image)
You can use the baseImage as below (on second thought it might not work because there is no dev-env there to build the native modules)
If we must to use a plain node docker, then we need to add the private docker registry to it (similar to baseImage) and then add it to the list of dockers that we download as part of a version
___
*[core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate, line 4 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1396#-MhwhE258IGd2rq44Dh-:-MhwhE258IGd2rq44Dh0:bjpgz3s) ([raw file](https://github.com/kube-hpc/hkube/blob/90bccf681cb55232e1c242e2df2cccca667006c4/core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate#L4)):*
> ```
> /hkube/algorithm-runner/algorithm_unique_folder
> ```
not that it matters in the end result but this folder should be /hkube/algorithm-runner
___
*[core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate, line 20 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1396#-Mhwge_m43Dd72xaiGto:-Mhwge_m43Dd72xaiGtp:b-1po1yr) ([raw file](https://github.com/kube-hpc/hkube/blob/90bccf681cb55232e1c242e2df2cccca667006c4/core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate#L20)):*
> ```
> ENV packagesAuth=${packagesAuth}
> ENV dependency_install_cmd=${dependency_install_cmd}
> RUN ../dockerfile/requirements.sh
> ```

I thought that we will always go to the `artifacts-registry` and it will fallback to `npm.js` or the `packagesRegistry`
___
*[core/algorithm-builder/environments/python/dockerfile/requirements.sh, line 31 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1396#-MhwiIRx63y2ZR9Pz1x1:-MhwiIRx63y2ZR9Pz1x2:b60whxp) ([raw file](https://github.com/kube-hpc/hkube/blob/90bccf681cb55232e1c242e2df2cccca667006c4/core/algorithm-builder/environments/python/dockerfile/requirements.sh#L31)):*
> ```Shell
>      if [ ! -z ${PACKAGES_REGISTRY} ]; then
>           PACKAGES_REGISTRY_HOST=$(echo $PACKAGES_REGISTRY | sed -e "s/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/")
>           echo "found pip registry ${PACKAGES_REGISTRY}. Setting trusted host to ${PACKAGES_REGISTRY_HOST}"
> ```

same as for the nodejs. Consider using only the artifacts-registry, and configure the registry (through helm) to use the correct updtream

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1396)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-builder/dockerfile/build.sh, line 7 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1396#-MhwfqeQ0q1UgXM7AIqy:-Mi0Gm997zeTQ-3Wh1IX:b6rqnhd) ([raw file](https://github.com/kube-hpc/hkube/blob/90bccf681cb55232e1c242e2df2cccca667006c4/core/algorithm-builder/dockerfile/build.sh#L7)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Why do we still need the java deps?
</blockquote></details>

for the zmq libs download.
___
*[core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate, line 3 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1396#-Mhwg1JR0g7qCS_B-1Je:-Mp5w2iX4CFuwYh2pwrW:bmsr6w7) ([raw file](https://github.com/kube-hpc/hkube/blob/90bccf681cb55232e1c242e2df2cccca667006c4/core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate#L3)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

this will not work in a disconnected environment. (no node:14.5.0 image)
You can use the baseImage as below (on second thought it might not work because there is no dev-env there to build the native modules)
If we must to use a plain node docker, then we need to add the private docker registry to it (similar to baseImage) and then add it to the list of dockers that we download as part of a version
</blockquote></details>

Done. Please add node:14.5.0 to the imported i docker list
___
*[core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate, line 4 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1396#-MhwhE258IGd2rq44Dh-:-Mi0KlCBEeU_G4V9ZsLo:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/90bccf681cb55232e1c242e2df2cccca667006c4/core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate#L4)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> /hkube/algorithm-runner/algorithm_unique_folder
> ```
not that it matters in the end result but this folder should be /hkube/algorithm-runner
</blockquote></details>

Done.
___
*[core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate, line 20 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1396#-Mhwge_m43Dd72xaiGto:-Mp5wBNBDIe1LU-Av39n:blq3axv) ([raw file](https://github.com/kube-hpc/hkube/blob/90bccf681cb55232e1c242e2df2cccca667006c4/core/algorithm-builder/environments/nodejs/dockerfile/DockerfileTemplate#L20)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I thought that we will always go to the `artifacts-registry` and it will fallback to `npm.js` or the `packagesRegistry`
</blockquote></details>

Will be done in the future
___
*[core/algorithm-builder/environments/python/dockerfile/requirements.sh, line 31 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1396#-MhwiIRx63y2ZR9Pz1x1:-Mp5wF4I9Pi_bLKpiaAo:blq3axv) ([raw file](https://github.com/kube-hpc/hkube/blob/90bccf681cb55232e1c242e2df2cccca667006c4/core/algorithm-builder/environments/python/dockerfile/requirements.sh#L31)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

same as for the nodejs. Consider using only the artifacts-registry, and configure the registry (through helm) to use the correct updtream
</blockquote></details>

Will be done in the future

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1396#-:-MtHR2WC7V01NOpCT4Lb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
