### PR TITLE
Add graph api for pipeline

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1591)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1591)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[`core/api-server/package.json` line 23 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1591#-N2R8QP2CdPplrxuz34u:-N2R8QP2CdPplrxuz34v:biz57yf) ([raw file](https://github.com/kube-hpc/hkube/blob/c2a9da6b52b88e9f44ef72f2fd0c49335cfbfe62/core/api-server/package.json#L23)):*
> ```JSON
>         "@hkube/units-converter": "^1.0.17",
>         "@octokit/rest": "^18.12.0",
>         "clone": "^2.1.2",
> ```

This package was last updated 4 years ago.
Why not use lodash.clonedeep?

same for flat
___
*[`core/api-server/lib/service/pipelines.js` line 65 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1591#-N2RBFNC2ePjxyLKQvah:-N2RBFNC2ePjxyLKQvai:bvrnku2) ([raw file](https://github.com/kube-hpc/hkube/blob/c2a9da6b52b88e9f44ef72f2fd0c49335cfbfe62/core/api-server/lib/service/pipelines.js#L65)):*
> ```JavaScript
>         const { flowInputMetadata, flowInput, ...restPipeline } = pipeline;
> 
>         const extendedPipeline = await pipelineCreator.buildPipelineOfPipelines(restPipeline);
> ```

Dows this cover all relevant pipeline extensions?



_Code quote:_
```JavaScript
getJSONGraph
```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1591)* status: 9 of 12 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[`core/api-server/package.json` line 23 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1591#-N2R8QP2CdPplrxuz34u:-N2RRO7Y4SeJ-iq7MAkP:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/c2a9da6b52b88e9f44ef72f2fd0c49335cfbfe62/core/api-server/package.json#L23)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This package was last updated 4 years ago.
Why not use lodash.clonedeep?

same for flat
</blockquote></details>

Done.
___
*[`core/api-server/lib/service/pipelines.js` line 65 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1591#-N2RBFNC2ePjxyLKQvah:-N2RRPAdAEuywrftWg3S:b22ecqt) ([raw file](https://github.com/kube-hpc/hkube/blob/c2a9da6b52b88e9f44ef72f2fd0c49335cfbfe62/core/api-server/lib/service/pipelines.js#L65)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Dows this cover all relevant pipeline extensions?
</blockquote></details>

Same code as the code running in the pipelinedriver minus the special handling of batch and for the task information

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1591#-:-N2ft-v254xYFlYewCXu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
