### PR TITLE
Optimizer

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1430)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 56 of 71 files at r1, 14 of 15 files at r2, 1 of 1 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1430)* status: all files reviewed, 17 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-hyperparams-tuner/.eslintignore, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Moh_dZ45iJPxJnM1HHv:-Moh_dZ45iJPxJnM1HHw:bc8hg6a) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/.eslintignore#L1)):*
> ```ignore
> coverage
> ```

remove all js and eslint ​file
___
*[core/algorithm-hyperparams-tuner/app.py, line 15 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohZdox8w_9eFRLeAwb:-MohZdox8w_9eFRLeAwc:b-d957u) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L15)):*
> ```Python
> def getStudy(sampler, storagePath):
>     if (sampler):
>         if (sampler['name'] == 'Grid'):
> ```

Is there validation on parameters someplace else? 
___
*[core/algorithm-hyperparams-tuner/app.py, line 29 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohZlZxDSgjVu2Mgce3:-MohZlZxDSgjVu2Mgce4:btnqhmk) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L29)):*
> ```Python
>             study = optuna.create_study(
>                 storage='sqlite:///' + storagePath, sampler=optuna.samplers.TPESampler())
>         if (sampler['name'] == 'CmaEs'):
> ```

what will happen if `name` is not one of the above types? I think it will crash because sampler is not defined
___
*[core/algorithm-hyperparams-tuner/app.py, line 37 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohZQTc3rI969Fktzyp:-MohZQTc3rI969Fktzyq:b-rtrkv7) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L37)):*
> ```Python
> 
> 
> def start(options, hkubeApi):
> ```

I think it would be better to separate the `main` from the algorithm code itself
___
*[core/algorithm-hyperparams-tuner/app.py, line 68 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohalN232m4b_aWPmTM:-MohalN232m4b_aWPmTN:borb64b) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L68)):*
> ```
>         values[param['name']] = getattr(
>             sys.modules[__name__], "suggest_%s" % param['suggest'])(param, trial)
> ```
This will crash if param['suggest'] is not one of the available suggesters
___
*[core/algorithm-hyperparams-tuner/app.py, line 71 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mohb2908NAiySieNlqX:-Mohb2908NAiySieNlqY:bn1zrj2) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L71)):*
> ```Python
>     pipelineResult = hkubeApi.start_stored_subpipeline(
>         pipelineName, {'hyperParams': values}, True)
>     print('printed here' + str(pipelineResult))
> ```

`printed here`?
___
*[core/algorithm-hyperparams-tuner/app.py, line 83 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohbGx2EhmdouDH7WaS:-MohbGx2EhmdouDH7WaT:b-8njbt1) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L83)):*
> ```Python
> 
> def suggest_uniform(param, trial):
>     return trial.suggest_uniform(param['name'], param['low'], param['high'])
> ```

better use consts for all of these string consts
___
*[core/algorithm-hyperparams-tuner/bootstrap.js, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohbN-K-aHcnH5MwA73:-MohbN-K-aHcnH5MwA74:b-l6mwxj) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/bootstrap.js#L1)):*
> ```JavaScript
> const configIt = require('@hkube/config');
> ```

remove
___
*[core/algorithm-hyperparams-tuner/package.json, line 7 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohbQcHCd0ogji19lsJ:-MohbQcHCd0ogji19lsK:b-jp1z5) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/package.json#L7)):*
> ```JSON
>     "main": "app.js",
>     "dependencies": {
>         "@hkube/config": "^2.0.11",
> ```

remove all dependencies
___
*[core/algorithm-hyperparams-tuner/README.md, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohbYLA6m1MsDjM8Zlt:-MohbYLA6m1MsDjM8Zlu:b-jxmxqg) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/README.md#L1)):*
> ```Markdown
> [Build Status](https://travis-ci.org/kube-HPC/algorithm-hyperparams-tuner)
> ```

Create a real README or delete this file
___
*[core/algorithm-hyperparams-tuner/config/logger/config.base.js, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mohbb7S0NZDU2S2NEGh:-Mohbb7T7S761f4s6VLj:b-l6mwxj) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/config/logger/config.base.js#L1)):*
> ```JavaScript
> const config = {};
> ```

remove
___
*[core/algorithm-hyperparams-tuner/dockerfile/Dockerfile, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mohc4rI6aAJ3Ol_uveG:-Mohc4rI6aAJ3Ol_uveH:b-c4mibe) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/dockerfile/Dockerfile#L1)):*
> ```Dockerfile
> FROM ${BASE_PRIVATE_REGISTRY}python:3.7
> ```

because this is an algorithm, I thing the dockerfile should look like this:
https://github.com/kube-HPC/algorithm-example-python/blob/master/dockerfile/Dockerfile
___
*[core/algorithm-hyperparams-tuner/dockerfile/Dockerfile, line 4 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohblSa9MDRn8Q4egKo:-MohblSa9MDRn8Q4egKp:bxtn8tk) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/dockerfile/Dockerfile#L4)):*
> ```Dockerfile
> COPY . /hkube/algorithm-hyperparams-tuner
> WORKDIR /hkube/algorithm-hyperparams-tuner
> RUN pip install -r ./dockerfile/requirements.txt 
> ```

better to run the install before the COPY command (just copy the requirements.txt and run pip install)
___
*[core/algorithm-hyperparams-tuner/dockerfile/requirements.txt, line 2 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohcCzE9OqbRqVIS3_z:-MohcCzE9OqbRqVIS3a-:bbsiygw) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/dockerfile/requirements.txt#L2)):*
> ```help
> optuna==2.10.0
> hkube-python-wrapper==2.2.0.dev9
> ```

Need to update the wrapper version after each build of the wrapper (same as in the algorithm builder)
___
*[core/algorithm-operator/lib/operator.js, line 97 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohcUSd3Y7zawp5Uhes:-MohcUSd3Y7zawp5Uhet:b20hzau) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-operator/lib/operator.js#L97)):*
> ```JavaScript
>         try {
>             log.debug('Update board interval.', { component });
>             // await tensorboardReconciler.updateTensorboards();
> ```

should this be commented out?
___
*[core/algorithm-operator/lib/templates/optunaboard.js, line 42 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MoheRYQ7LpsbKPHuZPu:-MoheRYQ7LpsbKPHuZPv:b-ezomny) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-operator/lib/templates/optunaboard.js#L42)):*
> ```JavaScript
>                             {
>                                 name: 'OPTUNADB',
>                                 value: `/hkube/datasciencemetrics-storage/${id}`
> ```

Will it work only if the storage is `fs`, and not `s3`?
If so the entire feature should be disabled via the helm
___
*[core/api-server/lib/service/hyperparams-tuner.js, line 15 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mohfe9O4ndONmKWEVoJ:-Mohfe9O4ndONmKWEVoK:bl5je45) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/api-server/lib/service/hyperparams-tuner.js#L15)):*
> ```JavaScript
>     }
> 
>     async getHyperparamsTuners(options) {
> ```

no need for async

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 6 of 71 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1430)* status: all files reviewed, 19 unresolved discussions (waiting on @golanha)

___
*[core/algorithm-hyperparams-tuner/app.py, line 41 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MoXqL_E5NULcWSqscDd:-MoXqL_E5NULcWSqscDe:b-g9lkq6) ([raw file](https://github.com/kube-hpc/hkube/blob/e6177a707b7d80f0029792e77eaff418464aec7f/core/algorithm-hyperparams-tuner/app.py#L41)):*
> ```
> options['spec'].get('sampler')
> ```

What is the convention?
options['spec'].get('sampler') 
OR
options['spec']['sampler']
___
*[core/algorithm-hyperparams-tuner/app.py, line 52 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MoXqCiO2rN2UJLJaHWc:-MoXqCiP1wkNSjN_B3OG:b-fkelts) ([raw file](https://github.com/kube-hpc/hkube/blob/e6177a707b7d80f0029792e77eaff418464aec7f/core/algorithm-hyperparams-tuner/app.py#L52)):*
> ```
> study.best_params
> ```

What is this line?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1430)* status: 52 of 75 files reviewed, 20 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-hyperparams-tuner/app.py, line 41 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MoXqL_E5NULcWSqscDd:-MoliS4x8X1dJyRZKiGn:bhwz12f) ([raw file](https://github.com/kube-hpc/hkube/blob/e6177a707b7d80f0029792e77eaff418464aec7f/core/algorithm-hyperparams-tuner/app.py#L41)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> options['spec'].get('sampler')
> ```

What is the convention?
options['spec'].get('sampler') 
OR
options['spec']['sampler']

</blockquote></details>

When I use "get"  no exception is thrown in case there is not sampler attribute.
___
*[core/algorithm-hyperparams-tuner/app.py, line 52 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MoXqCiO2rN2UJLJaHWc:-MolipOr7kH7WiOy-lRL:b-hfpv0l) ([raw file](https://github.com/kube-hpc/hkube/blob/e6177a707b7d80f0029792e77eaff418464aec7f/core/algorithm-hyperparams-tuner/app.py#L52)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> study.best_params
> ```

What is this line?
</blockquote></details>

removed
___
*[core/algorithm-hyperparams-tuner/app.py, line 15 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohZdox8w_9eFRLeAwb:-Mol_h8j3--dTawoyPDL:b8rwby7) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L15)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is there validation on parameters someplace else? 
</blockquote></details>

Yes, the parameters are defined in openapi-spec
___
*[core/algorithm-hyperparams-tuner/app.py, line 29 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohZlZxDSgjVu2Mgce3:-Molb9X48_ghGM3gTJFr:b-7mu65l) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L29)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

what will happen if `name` is not one of the above types? I think it will crash because sampler is not defined
</blockquote></details>

name is mandatory in:
https://github.com/kube-HPC/hkube/blob/optimizer/core/openapi-spec/swagger/definitions/hyperparamsTuner/sampler.yaml
___
*[core/algorithm-hyperparams-tuner/app.py, line 37 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohZQTc3rI969Fktzyp:-MoliR2c3aRdqaHYZ1ze:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L37)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I think it would be better to separate the `main` from the algorithm code itself
</blockquote></details>

Done.
___
*[core/algorithm-hyperparams-tuner/app.py, line 68 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohalN232m4b_aWPmTM:-MolktUS0vshtDj3zFxw:bu7c74s) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L68)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
>         values[param['name']] = getattr(
>             sys.modules[__name__], "suggest_%s" % param['suggest'])(param, trial)
> ```
This will crash if param['suggest'] is not one of the available suggesters
</blockquote></details>

suggest is mandatory:
https://github.com/kube-HPC/hkube/blob/optimizer/core/openapi-spec/swagger/definitions/hyperparamsTuner/hyperParam.yaml
___
*[core/algorithm-hyperparams-tuner/app.py, line 71 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mohb2908NAiySieNlqX:-Moll-1O3UX9x88kIJeM:b-hfpv0l) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L71)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

`printed here`?
</blockquote></details>

removed
___
*[core/algorithm-hyperparams-tuner/app.py, line 83 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohbGx2EhmdouDH7WaS:-Momr0sa6igYLHe1gpOz:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/app.py#L83)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

better use consts for all of these string consts
</blockquote></details>

Done.
___
*[core/algorithm-hyperparams-tuner/package.json, line 7 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohbQcHCd0ogji19lsJ:-MomM-2ABcywvkjjlSdD:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/package.json#L7)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

remove all dependencies
</blockquote></details>

Done.
___
*[core/algorithm-hyperparams-tuner/dockerfile/Dockerfile, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mohc4rI6aAJ3Ol_uveG:-MomI3VFAmvdrd_576hV:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/dockerfile/Dockerfile#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

because this is an algorithm, I thing the dockerfile should look like this:
https://github.com/kube-HPC/algorithm-example-python/blob/master/dockerfile/Dockerfile
</blockquote></details>

Done.
___
*[core/algorithm-hyperparams-tuner/dockerfile/Dockerfile, line 4 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohblSa9MDRn8Q4egKo:-MomI4d926tP9dLmLnht:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/dockerfile/Dockerfile#L4)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

better to run the install before the COPY command (just copy the requirements.txt and run pip install)
</blockquote></details>

Done.
___
*[core/algorithm-operator/lib/operator.js, line 97 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohcUSd3Y7zawp5Uhes:-MomKd1n3_q_DriqZfrE:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-operator/lib/operator.js#L97)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

should this be commented out?
</blockquote></details>

Done.
___
*[core/algorithm-operator/lib/templates/optunaboard.js, line 42 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MoheRYQ7LpsbKPHuZPu:-Mon5kr0Ex0VUPDETwPb:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-operator/lib/templates/optunaboard.js#L42)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Will it work only if the storage is `fs`, and not `s3`?
If so the entire feature should be disabled via the helm
</blockquote></details>

Done.
___
*[core/algorithm-operator/lib/templates/optunaboard.js, line 42 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MomRTI9DfD3n2Hjd18I:-MomRTI9DfD3n2Hjd18J:b-qv58jn) ([raw file](https://github.com/kube-hpc/hkube/blob/fb1797f04a1b670043e1bcac2b5be5d613240d0a/core/algorithm-operator/lib/templates/optunaboard.js#L42)):*
> ```
> atasciencemetric
> ```
___
*[core/api-server/lib/service/hyperparams-tuner.js, line 15 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mohfe9O4ndONmKWEVoJ:-MomM3V_AD27yW6EezqW:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/api-server/lib/service/hyperparams-tuner.js#L15)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

no need for async
</blockquote></details>

Done.
___
*[core/algorithm-hyperparams-tuner/.eslintignore, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Moh_dZ45iJPxJnM1HHv:-Mol_Ulh1ArLBHU5Thjp:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/.eslintignore#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

remove all js and eslint ​file
</blockquote></details>

Done.
___
*[core/algorithm-hyperparams-tuner/bootstrap.js, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohbN-K-aHcnH5MwA73:-MollKzi4UI75Wzd6REy:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/bootstrap.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[core/algorithm-hyperparams-tuner/README.md, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohbYLA6m1MsDjM8Zlt:-Molo4_b9PywyVKcLNxe:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/README.md#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Create a real README or delete this file
</blockquote></details>

Done.
___
*[core/algorithm-hyperparams-tuner/config/logger/config.base.js, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mohbb7S0NZDU2S2NEGh:-MomM0T23a5Pukro8Mvn:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/config/logger/config.base.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[core/algorithm-hyperparams-tuner/dockerfile/requirements.txt, line 2 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MohcCzE9OqbRqVIS3_z:-MomIX_x2AqpvCSnVRpS:b-cjx29m) ([raw file](https://github.com/kube-hpc/hkube/blob/b913576cb715dfedeea7dd6c145f1a7126f28e12/core/algorithm-hyperparams-tuner/dockerfile/requirements.txt#L2)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Need to update the wrapper version after each build of the wrapper (same as in the algorithm builder)
</blockquote></details>

That is also true for the nodejs wrapper for gateway,debug,output. also there is a pull request with changes in the wrapper update procedure (Still waiting for secured artifactory for tests).
I created a separate issue for this:
https://github.com/kube-HPC/hkube/issues/1461

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 22 of 23 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1430)* status: all files reviewed, 5 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 392 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mp0L4il57hKxBnxA6hX:-Mp0L4il57hKxBnxA6hY:b49bq4) ([raw file](https://github.com/kube-hpc/hkube/blob/67b5c430cfc1cf7d7fb4903ef326db427c897897/core/task-executor/lib/jobs/jobCreator.js#L392)):*
> ```JavaScript
>     if (kind === nodeKind.HyperparamsTuner) {
>         if (!clusterOptions?.optunaDashboardEnabled) {
>             spec = applyEnvToContainer(spec, CONTAINERS.ALGORITHM, hyperparamsTunerEnvNoDashboard);
> ```

why do you need the env if it is not enabled?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1430)* status: all files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 392 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mp0L4il57hKxBnxA6hX:-Mp0OgI77f5V7ZlihIB0:b-ugl8pn) ([raw file](https://github.com/kube-hpc/hkube/blob/67b5c430cfc1cf7d7fb4903ef326db427c897897/core/task-executor/lib/jobs/jobCreator.js#L392)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why do you need the env if it is not enabled?
</blockquote></details>

When not enabled, I still allow to run the hyperparam-tuner. Only the dashboard is disabled.
When the dashboard is disabled the env makes the dashboard statistics be saved locally, since the dashboard won't use it.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1430)* status: all files reviewed, 4 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-operator/lib/templates/optunaboard.js, line 42 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1430#-MomRTI9DfD3n2Hjd18I:-MpMa5t96VGPoBnCe_p3:b3kre) ([raw file](https://github.com/kube-hpc/hkube/blob/fb1797f04a1b670043e1bcac2b5be5d613240d0a/core/algorithm-operator/lib/templates/optunaboard.js#L42)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> ```
> atasciencemetric
> ```

</blockquote></details>

?
___
*[core/task-executor/lib/jobs/jobCreator.js, line 392 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1430#-Mp0L4il57hKxBnxA6hX:-MpMZt_2BXEVCTcohXov:bokdg0s) ([raw file](https://github.com/kube-hpc/hkube/blob/67b5c430cfc1cf7d7fb4903ef326db427c897897/core/task-executor/lib/jobs/jobCreator.js#L392)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

When not enabled, I still allow to run the hyperparam-tuner. Only the dashboard is disabled.
When the dashboard is disabled the env makes the dashboard statistics be saved locally, since the dashboard won't use it.
</blockquote></details>

In restricted environments (like openshift) you cannot write inside the container. Setting `SHARED_METRICS` to `.` will not work.
I think you can use `/tmp` or add an empty-dir as the volume for the mount (in line 217 change to emptyDir instead of persistentVolumeClaim. see line 257

**Review by yehiyam — APPROVED** [review]
> Reviewed 10 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1430)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @NassiHarel)

**Pull request merged**
