### PR TITLE
debug hkube api

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[core/algorithm-debug/lib/index.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MdN4gPX-h3EoYM8VWBJ:-MdN4gPX-h3EoYM8VWBK:b-s9w008) ([raw file](https://github.com/kube-hpc/hkube/blob/37f567ec8da08d445ebe9be9f5b4b5f79719e87d/core/algorithm-debug/lib/index.js#L5)):*
> ```
> require('./consts/messages');
> ```

You can remove this file?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/algorithm-debug/lib/index.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MdN4gPX-h3EoYM8VWBJ:-MdNAuLWE4UHyeUpZ4Ax:blyu04q) ([raw file](https://github.com/kube-hpc/hkube/blob/37f567ec8da08d445ebe9be9f5b4b5f79719e87d/core/algorithm-debug/lib/index.js#L5)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> require('./consts/messages');
> ```

You can remove this file?
</blockquote></details>

tests failed because debug related messages are not in nodejs messages. So now I use this file for debugrleated messages:streamingInMessageDone,  streamingOutMessage, streamingInMessage

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-debug/lib/index.js, line 35 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MduOnbsAZ-_P2zXIvge:-MduOnbsAZ-_P2zXIvgf:b-2r4jow) ([raw file](https://github.com/kube-hpc/hkube/blob/c55aa8a66a5c75fbeb981331c0254c8219b97bdd/core/algorithm-debug/lib/index.js#L35)):*
> ```JavaScript
>     });
> 
>     ws.on(messages.outgoing.startAlgorithmExecution, async ({ execId, algorithmName, input, includeResult }) => {
> ```

if you use Promise.then/catch you don't need async. Async is only needed for await.

Beside that, please use async await with try/catch. It is more readable than then/catch
___
*[core/algorithm-debug/tests/debug.js, line 4 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MduPRKVEtQawLzwHs6M:-MduPRKVEtQawLzwHs6N:bu5v0tu) ([raw file](https://github.com/kube-hpc/hkube/blob/c55aa8a66a5c75fbeb981331c0254c8219b97bdd/core/algorithm-debug/tests/debug.js#L4)):*
> ```JavaScript
> const { main: config } = configIt.load();
> const { expect } = require('chai');
> const messages = require('@hkube/nodejs-wrapper/lib/consts/messages');
> ```

It's not good practice to require an internal file. If you need these messages than export them from the package

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 5 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MdN4gPX-h3EoYM8VWBJ:-MeYsyqE9LfZKZnW98Aj:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/37f567ec8da08d445ebe9be9f5b4b5f79719e87d/core/algorithm-debug/lib/index.js#L5)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

tests failed because debug related messages are not in nodejs messages. So now I use this file for debugrleated messages:streamingInMessageDone,  streamingOutMessage, streamingInMessage
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 35 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MduOnbsAZ-_P2zXIvge:-MeYsyXA3uXPsIvOnYwV:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/c55aa8a66a5c75fbeb981331c0254c8219b97bdd/core/algorithm-debug/lib/index.js#L35)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

if you use Promise.then/catch you don't need async. Async is only needed for await.

Beside that, please use async await with try/catch. It is more readable than then/catch
</blockquote></details>

Done.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-debug/tests/debug.js, line 4 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MduPRKVEtQawLzwHs6M:-MeZciZC4lC6KRZuAHhf:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/c55aa8a66a5c75fbeb981331c0254c8219b97bdd/core/algorithm-debug/tests/debug.js#L4)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

It's not good practice to require an internal file. If you need these messages than export them from the package
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-debug/lib/index.js, line 35 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MduOnbsAZ-_P2zXIvge:-MeZYO4n9_5WJzH3ZSdy:brxaz97) ([raw file](https://github.com/kube-hpc/hkube/blob/c55aa8a66a5c75fbeb981331c0254c8219b97bdd/core/algorithm-debug/lib/index.js#L35)):*
> Beside that, please use async await with try/catch. It is more readable than then/catch
why not use async/await
___
*[core/algorithm-debug/lib/index.js, line 71 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MeZdSsmBIwg94TXE5Rc:-MeZdSsn-iJdkln8pAJS:b-rqlbs7) ([raw file](https://github.com/kube-hpc/hkube/blob/b21b26e73ea51fe9d3d0a6cc599e3eba228a00a0/core/algorithm-debug/lib/index.js#L71)):*
> ```JavaScript
>     ws.on(messages.outgoing.streamingOutMessage, ({ message, flowName, sendMessageId }) => {
>         const sendMessage = sendMessageDelegates[sendMessageId];
>         log.info(`sending a message, flow:${flowName}`);
> ```

Isn't `info` too verbose? it will log for every message

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 35 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MduOnbsAZ-_P2zXIvge:-Mecsu671iOMdQ1QFd1z:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/c55aa8a66a5c75fbeb981331c0254c8219b97bdd/core/algorithm-debug/lib/index.js#L35)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> Beside that, please use async await with try/catch. It is more readable than then/catch
why not use async/await
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 71 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MeZdSsmBIwg94TXE5Rc:-MecsvpYAKc9b1I5KHiB:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b21b26e73ea51fe9d3d0a6cc599e3eba228a00a0/core/algorithm-debug/lib/index.js#L71)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Isn't `info` too verbose? it will log for every message
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 5 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MesS9u09r2IPPTA4EWR:-MesS9u1-pztOYq2wzXN:b-u688ky) ([raw file](https://github.com/kube-hpc/hkube/blob/3132e8543d30eeaac964d6a81ed58cf19bf25cce/core/algorithm-debug/lib/index.js#L5)):*
> ```
> /
> ```
this `/` is redundant
___
*[core/algorithm-debug/lib/index.js, line 55 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MesUu6E2mvs6HMkgkDk:-MesUu6E2mvs6HMkgkDl:b-fg2m5b) ([raw file](https://github.com/kube-hpc/hkube/blob/3132e8543d30eeaac964d6a81ed58cf19bf25cce/core/algorithm-debug/lib/index.js#L55)):*
> ```JavaScript
>     ws.on(messages.outgoing.startStoredSubPipeline, async ({ subPipeline, subPipelineId, includeResult }) => {
>         try {
>             const response = await hkubeApi.startStoredSubpipeline(subPipeline.name, subPipeline.flatInput, includeResult);
> ```

For this file you have only 68.42% test coverage, this is too low.
`startAlgorithmExecution, startRawSubPipeline, startStoredSubPipeline,dataSourceRequest`
are not covered by unit tests.
___
*[core/algorithm-debug/lib/index.js, line 79 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MesV4x-29qOgGdhgcNj:-MesV4x01aCG-VS4vFes:b-xiyyyp) ([raw file](https://github.com/kube-hpc/hkube/blob/3132e8543d30eeaac964d6a81ed58cf19bf25cce/core/algorithm-debug/lib/index.js#L79)):*
> ```JavaScript
>     ws.on(messages.outgoing.streamingOutMessage, ({ message, flowName, sendMessageId }) => {
>         const sendMessage = sendMessageDelegates[sendMessageId];
>         log.debug(`sending a message, flow:${flowName}`);
> ```

For better verbosity, I think you need `log.info` instead of `log.debug`, but with `throttle`
`log.throttle.info('....')`

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 5 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MesS9u09r2IPPTA4EWR:-MetUZ0j-y977N_uTcmw:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/3132e8543d30eeaac964d6a81ed58cf19bf25cce/core/algorithm-debug/lib/index.js#L5)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> /
> ```
this `/` is redundant
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 55 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MesUu6E2mvs6HMkgkDk:-MetUdsUATV1KMIiYnH8:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/3132e8543d30eeaac964d6a81ed58cf19bf25cce/core/algorithm-debug/lib/index.js#L55)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

For this file you have only 68.42% test coverage, this is too low.
`startAlgorithmExecution, startRawSubPipeline, startStoredSubPipeline,dataSourceRequest`
are not covered by unit tests.

</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 79 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1316#-MesV4x-29qOgGdhgcNj:-MetUhNQ5WEqwJ7QWayu:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/3132e8543d30eeaac964d6a81ed58cf19bf25cce/core/algorithm-debug/lib/index.js#L79)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

For better verbosity, I think you need `log.info` instead of `log.debug`, but with `throttle`
`log.throttle.info('....')`
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 11 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mey-1oC-ySR3rSKOczM:-Mey-1oC-ySR3rSKOczN:b-pjh3vr) ([raw file](https://github.com/kube-hpc/hkube/blob/1742dbe0a72637c99daf9011ce8d8aac7387b16d/core/algorithm-debug/lib/index.js#L11)):*
> ```
> log.debug
> ```
maybe info?
___
*[core/algorithm-debug/lib/index.js, line 55 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mey-u2X0AsodW25y1Mz:-Mey-u2X0AsodW25y1N-:b-5up2zy) ([raw file](https://github.com/kube-hpc/hkube/blob/1742dbe0a72637c99daf9011ce8d8aac7387b16d/core/algorithm-debug/lib/index.js#L55)):*
> ```
> subPipeline.flatInput
> ```
flatInput? or flowInput?
___
*[core/algorithm-debug/lib/index.js, line 68 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mey3FA17IUV3BMqKKEv:-Mey3FA17IUV3BMqKKEw:b-vfc72h) ([raw file](https://github.com/kube-hpc/hkube/blob/1742dbe0a72637c99daf9011ce8d8aac7387b16d/core/algorithm-debug/lib/index.js#L68)):*
> ```
> dataSourceResponseError
> ```
Do we have this message in our wrappers?

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 41 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mey87hjAFLkcN4E1Txv:-Mey87hjAFLkcN4E1Txw:bq43acw) ([raw file](https://github.com/kube-hpc/hkube/blob/1742dbe0a72637c99daf9011ce8d8aac7387b16d/core/algorithm-debug/lib/index.js#L41)):*
> ```
> response: response.message
> ```
Do you have a message in the response?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 11 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mey-1oC-ySR3rSKOczM:-MeyLObD7Wavuva66npT:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/1742dbe0a72637c99daf9011ce8d8aac7387b16d/core/algorithm-debug/lib/index.js#L11)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> log.debug
> ```
maybe info?
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 55 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mey-u2X0AsodW25y1Mz:-MeyLym473lEtND-C2Fr:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/1742dbe0a72637c99daf9011ce8d8aac7387b16d/core/algorithm-debug/lib/index.js#L55)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> subPipeline.flatInput
> ```
flatInput? or flowInput?
</blockquote></details>

Done.
___
*[core/algorithm-debug/lib/index.js, line 68 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mey3FA17IUV3BMqKKEv:-MeyN-37DtHcK5mnP6dg:b-lo5837) ([raw file](https://github.com/kube-hpc/hkube/blob/1742dbe0a72637c99daf9011ce8d8aac7387b16d/core/algorithm-debug/lib/index.js#L68)):*
> ```
> messages.incoming.dataSourceResponseError
> ```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-debug/lib/index.js, line 41 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mey87hjAFLkcN4E1Txv:-MeyU4wvDY2X3FYVqqh8:b-ikn5dq) ([raw file](https://github.com/kube-hpc/hkube/blob/1742dbe0a72637c99daf9011ce8d8aac7387b16d/core/algorithm-debug/lib/index.js#L41)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> response: response.message
> ```
Do you have a message in the response?
</blockquote></details>

Its the message of the exception thrown.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 3 of 7 files reviewed, 11 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 39 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf6zuYDBbkJ9V1csRMh:-Mf6zuYDBbkJ9V1csRMi:b-tga8il) ([raw file](https://github.com/kube-hpc/hkube/blob/fa6a1f7508a1e1da80c36b58786f9ff676f183a1/core/algorithm-debug/lib/algorithm-communication/ws.js#L39)):*
> ```
> const encoding = new Encoding({ type: data.encoding });
> ```
You already have `this._encoding`....
___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 41 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf7-2iU3hlgV66o4M5I:-Mf7-2iU3hlgV66o4M5J:b1vw926) ([raw file](https://github.com/kube-hpc/hkube/blob/fa6a1f7508a1e1da80c36b58786f9ff676f183a1/core/algorithm-debug/lib/algorithm-communication/ws.js#L41)):*
> ```
> socket.send(encoding.encode('Debugger connected already'));
> ```
Who the hell is listening to this topic?
___
*[core/api-server/lib/service/debug.js, line 28 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf6zAmS3J8Sn_cJ2gHK:-Mf6zAmT-weuVltRCVj1:bqowd7e) ([raw file](https://github.com/kube-hpc/hkube/blob/fa6a1f7508a1e1da80c36b58786f9ff676f183a1/core/api-server/lib/service/debug.js#L28)):*
> ```
>         if (!algorithmName) {
>             throw new InvalidDataError('Node for debug must have algorithm name set');
>         }
> ```
this should be the first validation, before trying to fetch from the DB

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 3 of 7 files reviewed, 10 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 41 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf7-2iU3hlgV66o4M5I:-Mf7-Kuq1FEUGLGCRx99:bh5112z) ([raw file](https://github.com/kube-hpc/hkube/blob/fa6a1f7508a1e1da80c36b58786f9ff676f183a1/core/algorithm-debug/lib/algorithm-communication/ws.js#L41)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> socket.send(encoding.encode('Debugger connected already'));
> ```
Who the hell is listening to this topic?
</blockquote></details>

We have a format to send messages on WS

**Comment by golanha** [comment]
___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 39 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf6zuYDBbkJ9V1csRMh:-Mf70kjrDcGHrY7MH8Qm:b-dzna56) ([raw file](https://github.com/kube-hpc/hkube/blob/fa6a1f7508a1e1da80c36b58786f9ff676f183a1/core/algorithm-debug/lib/algorithm-communication/ws.js#L39)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const encoding = new Encoding({ type: data.encoding });
> ```
You already have `this._encoding`....
</blockquote></details>

It might be a different one by the second debugged algo.

**Comment by golanha** [comment]
___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 41 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf7-2iU3hlgV66o4M5I:-Mf71wGx7s4kCQ_inquv:b6jo948) ([raw file](https://github.com/kube-hpc/hkube/blob/fa6a1f7508a1e1da80c36b58786f9ff676f183a1/core/algorithm-debug/lib/algorithm-communication/ws.js#L41)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

We have a format to send messages on WS
</blockquote></details>

I didn't think it should be part of the protocol between worker and wrapper. I thought it should act like a connection problem.
I"ll add it and deal with it.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 3 of 7 files reviewed, 10 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/lib/service/debug.js, line 28 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf6zAmS3J8Sn_cJ2gHK:-Mf7T5zJED38qqElfxB2:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/fa6a1f7508a1e1da80c36b58786f9ff676f183a1/core/api-server/lib/service/debug.js#L28)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>         if (!algorithmName) {
>             throw new InvalidDataError('Node for debug must have algorithm name set');
>         }
> ```
this should be the first validation, before trying to fetch from the DB
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 39 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf7qNNFCWw7_qykEHSv:-Mf7qNNFCWw7_qykEHSw:b-puhve4) ([raw file](https://github.com/kube-hpc/hkube/blob/70e509e75e995b9c278d41ba6d1b714690ef50c7/core/algorithm-debug/lib/algorithm-communication/ws.js#L39)):*
> ```
> socket.close(1007);
> ```
What is 1007?

Does it have any meaning?

https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 39 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf7rb4X36Ruyj2tWlC1:-Mf7rb4X36Ruyj2tWlC2:b-sbuo62) ([raw file](https://github.com/kube-hpc/hkube/blob/70e509e75e995b9c278d41ba6d1b714690ef50c7/core/algorithm-debug/lib/algorithm-communication/ws.js#L39)):*
> ```
>  socket.close(1007);
> ```
Maybe 1013?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 39 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf7qNNFCWw7_qykEHSv:-Mf8-PAi7QbFqW2vWG_6:bz1xyum) ([raw file](https://github.com/kube-hpc/hkube/blob/70e509e75e995b9c278d41ba6d1b714690ef50c7/core/algorithm-debug/lib/algorithm-communication/ws.js#L39)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> socket.close(1007);
> ```
What is 1007?

Does it have any meaning?

https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent

</blockquote></details>

I took the first unreserved code.
___
*[core/algorithm-debug/lib/algorithm-communication/ws.js, line 39 at r10](https://reviewable.io/reviews/kube-hpc/hkube/1316#-Mf7rb4X36Ruyj2tWlC1:-Mf8-TdAETAfXuq4PQ06:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/70e509e75e995b9c278d41ba6d1b714690ef50c7/core/algorithm-debug/lib/algorithm-communication/ws.js#L39)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  socket.close(1007);
> ```
Maybe 1013?
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1316#-:-Mf8T_3NA3T9Ky0FsxDy:bnfp4nl)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

**Pull request merged**
