### PR TITLE
use getAll on clean etcd

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1457)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1457)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[core/gc-service/lib/helpers/etcd.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1457#-MpAs29gECTqYvTQ3G55:-MpAs29gECTqYvTQ3G56:bkbdiya) ([raw file](https://github.com/kube-hpc/hkube/blob/14cc9afe7b93bcaef7fdeda33b80a88c87247448/core/gc-service/lib/helpers/etcd.js#L11)):*
> ```JavaScript
> 
>     async getKeys(path) {
>         const ret = await this._etcd._client.getAll(path);
> ```

This potentially can fetch a huge amount of data and lead to OOM.

**Comment by golanha** [comment]
___
*[core/gc-service/lib/helpers/etcd.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1457#-MpAs29gECTqYvTQ3G55:-MpAzyMYDfEy-OOxwXPS:b-n8gv0q) ([raw file](https://github.com/kube-hpc/hkube/blob/14cc9afe7b93bcaef7fdeda33b80a88c87247448/core/gc-service/lib/helpers/etcd.js#L11)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

This potentially can fetch a huge amount of data and lead to OOM.
</blockquote></details>

I think that when there was limit, it first fetched all the data anyway and only after it had been fetched some records were filtered out: 
https://github.com/kube-HPC/etcd.hkube/blob/master/lib/core/etcd-client.js

<code>    async getKeysSortLimit(path, sort, limit) {
        return this.client.getAll()
            .prefix(path)
            .sort(...sort)
            .limit(limit)
            .keys();
    }</code>

**Review by yehiyam — DISMISSED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1457)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/gc-service/lib/helpers/etcd.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1457#-MpAs29gECTqYvTQ3G55:-MpHl69y24HDfYkGN8-5:b-1rnz2g) ([raw file](https://github.com/kube-hpc/hkube/blob/14cc9afe7b93bcaef7fdeda33b80a88c87247448/core/gc-service/lib/helpers/etcd.js#L11)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I think that when there was limit, it first fetched all the data anyway and only after it had been fetched some records were filtered out: 
https://github.com/kube-HPC/etcd.hkube/blob/master/lib/core/etcd-client.js

<code>    async getKeysSortLimit(path, sort, limit) {
        return this.client.getAll()
            .prefix(path)
            .sort(...sort)
            .limit(limit)
            .keys();
    }</code>


</blockquote></details>

Nassi is right. It will lead to OOM.
in the query you mentioned all of the parameters are chained internally and the actual query is performed (with all of the parameters).

only when keys() is called the actual query is performed.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1457)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[core/gc-service/lib/helpers/etcd.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1457#-MpAs29gECTqYvTQ3G55:-MpLVELm8iEyZ8cn8Q8T:b-ho9hmi) ([raw file](https://github.com/kube-hpc/hkube/blob/14cc9afe7b93bcaef7fdeda33b80a88c87247448/core/gc-service/lib/helpers/etcd.js#L11)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Nassi is right. It will lead to OOM.
in the query you mentioned all of the parameters are chained internally and the actual query is performed (with all of the parameters).

only when keys() is called the actual query is performed.
</blockquote></details>


This should be like:
while (there is data to clean):
1) loop over paths
2) get 100 keys
3) clean keys

this cleaner should act differently from other cleaners...
in one pass it should clean until there is no more to clean.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1457)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/gc-service/lib/cleaners/etcd/index.js, line 50 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1457#-MpM5WbO0FsxQBQJ6Jcw:-MpM5WbO0FsxQBQJ6Jcx:bg2kw6z) ([raw file](https://github.com/kube-hpc/hkube/blob/076c1fa854658b96fbb49cfdb9d9d5f6ecf26e64/core/gc-service/lib/cleaners/etcd/index.js#L50)):*
> ```
> const data = await Promise.all(paths.map(p => etcdStore.getKeys(p)));
> ```

The main reason for OOM is this line, fetch of 13 paths with 10,000 entries each.
So 

```
while (there is data to clean in current path):
get 100 keys
clean keys
```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1457)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/gc-service/lib/cleaners/etcd/index.js, line 50 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1457#-MpM5WbO0FsxQBQJ6Jcw:-Mp_ZkAK53PggSEGtg-a:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/076c1fa854658b96fbb49cfdb9d9d5f6ecf26e64/core/gc-service/lib/cleaners/etcd/index.js#L50)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const data = await Promise.all(paths.map(p => etcdStore.getKeys(p)));
> ```

The main reason for OOM is this line, fetch of 13 paths with 10,000 entries each.
So 

```
while (there is data to clean in current path):
get 100 keys
clean keys
```
</blockquote></details>

Done.
___
*[core/gc-service/lib/helpers/etcd.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1457#-MpAs29gECTqYvTQ3G55:-Mp_ZmVP4hFGQ9-edHK3:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/14cc9afe7b93bcaef7fdeda33b80a88c87247448/core/gc-service/lib/helpers/etcd.js#L11)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>


This should be like:
while (there is data to clean):
1) loop over paths
2) get 100 keys
3) clean keys

this cleaner should act differently from other cleaners...
in one pass it should clean until there is no more to clean.

</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 6 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1457#-:-MrwFqxF-dX3MjDsuI8y:bnfp4nl)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @yehiyam)

**Pull request merged**
