### PR TITLE
feat: jobs search

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1277)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, 3 of 4 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1277)* status: all files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/api/rest-api/swagger.json, line 1572 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb5LYChBDOWLF1aR7VP:-Mb5LYChBDOWLF1aR7VQ:b51oqhv) ([raw file](https://github.com/kube-hpc/hkube/blob/bdb53b1037725a7022bd68fcc465ab643fd184aa/core/api-server/api/rest-api/swagger.json#L1572)):*
> ```JSON
>                     "default": "desc"
>                   },
>                   "limit": {
> ```

Is there a limit on the limit?
___
*[core/api-server/api/rest-api/swagger.json, line 1588 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb5LdZ9Bc9icZeFzMZB:-Mb5LdZ9Bc9icZeFzMZC:b-cor3yk) ([raw file](https://github.com/kube-hpc/hkube/blob/bdb53b1037725a7022bd68fcc465ab643fd184aa/core/api-server/api/rest-api/swagger.json#L1588)):*
> ```JSON
>                   "query": {
>                     "datesRange": {
>                       "from": "2021-05-22T15:00:00",
> ```

is it possible that in the example it will always return the last day?
___
*[core/api-server/api/rest-api/routes/v1/exec.js, line 89 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb5M-Wc7mMcfuJEoApU:-Mb5M-Wc7mMcfuJEoApV:b-9iflp2) ([raw file](https://github.com/kube-hpc/hkube/blob/bdb53b1037725a7022bd68fcc465ab643fd184aa/core/api-server/api/rest-api/routes/v1/exec.js#L89)):*
> ```JavaScript
>         next();
>     });
>     router.all('/search', methods(['POST']), logger(), async (req, res, next) => {
> ```

maybe add another endpoint with `GET` and query string. It is easy to search like this from the browser
___
*[core/api-server/api/rest-api/swagger/definitions/searchJobs.yaml, line 51 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb5MDvC1WR6yuahw1Yj:-Mb5MDvC1WR6yuahw1Yk:b-cor3yk) ([raw file](https://github.com/kube-hpc/hkube/blob/bdb53b1037725a7022bd68fcc465ab643fd184aa/core/api-server/api/rest-api/swagger/definitions/searchJobs.yaml#L51)):*
> ```YAML
>     datesRange:
>       from: '2021-05-22T15:00:00'
>       to: '2021-06-22T16:00:00'
> ```

is it possible that in the example it will always return the last day?

**Review by yehiyam — COMMENTED** [review]
I saw that you sort the results in the db package by ID. Isn't it more intuitive for the user to sort by creation date?

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1277#-:-Mb5UrHBBi2NbEdQPxsk:b-63apl1)* status: all files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1277)* status: all files reviewed, 4 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/api/rest-api/swagger.json, line 1572 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb5LYChBDOWLF1aR7VP:-Mb5uuFg9E2wAMjCbxe8:b32w12) ([raw file](https://github.com/kube-hpc/hkube/blob/bdb53b1037725a7022bd68fcc465ab643fd184aa/core/api-server/api/rest-api/swagger.json#L1572)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is there a limit on the limit?
</blockquote></details>

No
___
*[core/api-server/api/rest-api/swagger.json, line 1588 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb5LdZ9Bc9icZeFzMZB:-Mb5vj082oCO6fSESICF:bcg29te) ([raw file](https://github.com/kube-hpc/hkube/blob/bdb53b1037725a7022bd68fcc465ab643fd184aa/core/api-server/api/rest-api/swagger.json#L1588)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

is it possible that in the example it will always return the last day?
</blockquote></details>

Didn't find something
___
*[core/api-server/api/rest-api/routes/v1/exec.js, line 89 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb5M-Wc7mMcfuJEoApU:-Mb5vmTp-dbJzDDZ6UeH:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/bdb53b1037725a7022bd68fcc465ab643fd184aa/core/api-server/api/rest-api/routes/v1/exec.js#L89)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

maybe add another endpoint with `GET` and query string. It is easy to search like this from the browser
</blockquote></details>

Done.
___
*[core/api-server/api/rest-api/swagger/definitions/searchJobs.yaml, line 51 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb5MDvC1WR6yuahw1Yj:-Mb5vxu72Zey_t-OdXhc:bt8yjv4) ([raw file](https://github.com/kube-hpc/hkube/blob/bdb53b1037725a7022bd68fcc465ab643fd184aa/core/api-server/api/rest-api/swagger/definitions/searchJobs.yaml#L51)):*
> Didn't find something

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1277)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/api/rest-api/swagger.json, line 1712 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb67yxz51jYEyIb27-e:-Mb67yy01oCgVlXArkvU:b-yw0ral) ([raw file](https://github.com/kube-hpc/hkube/blob/9cfda5a6c1bc75c2e2478d2cd2296064f9f7a7b2/core/api-server/api/rest-api/swagger.json#L1712)):*
> ```JSON
>           },
>           {
>             "name": "status",
> ```

we should name the query parameters the same as in the post method. e.g. status vs pipelineStatus
___
*[core/api-server/api/rest-api/routes/v1/exec.js, line 111 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb68sLk1plR046X4p6o:-Mb68sLl5AJmqQLIgpFq:b-kysbvu) ([raw file](https://github.com/kube-hpc/hkube/blob/9cfda5a6c1bc75c2e2478d2cd2296064f9f7a7b2/core/api-server/api/rest-api/routes/v1/exec.js#L111)):*
> ```JavaScript
>             cursor,
>             sort,
>             pageNum: formatter.parseInt(page, null),
> ```

why pass null here? Isn't it the same as not providing it at all?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1277)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/api/rest-api/swagger.json, line 1712 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb67yxz51jYEyIb27-e:-Mb6Je5U7-QqkzDVppUX:bd7yiuw) ([raw file](https://github.com/kube-hpc/hkube/blob/9cfda5a6c1bc75c2e2478d2cd2296064f9f7a7b2/core/api-server/api/rest-api/swagger.json#L1712)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

we should name the query parameters the same as in the post method. e.g. status vs pipelineStatus
</blockquote></details>

I knew you would say that... I wanted to make the writing shorter
___
*[core/api-server/api/rest-api/routes/v1/exec.js, line 111 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb68sLk1plR046X4p6o:-Mb6LYYS-l9Y_Nrq_BXI:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/9cfda5a6c1bc75c2e2478d2cd2296064f9f7a7b2/core/api-server/api/rest-api/routes/v1/exec.js#L111)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why pass null here? Isn't it the same as not providing it at all?
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1277#-:-Mb6MopY3s39WJPLKNBL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/api/rest-api/swagger.json, line 1712 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1277#-Mb67yxz51jYEyIb27-e:-Mb6MbbV1LM1gthRIHtp:b-3ycf3x) ([raw file](https://github.com/kube-hpc/hkube/blob/9cfda5a6c1bc75c2e2478d2cd2296064f9f7a7b2/core/api-server/api/rest-api/swagger.json#L1712)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I knew you would say that... I wanted to make the writing shorter
</blockquote></details>

so change the post to the shorter version :-)

**Pull request merged**
