### PR TITLE
Update instead of create

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1575)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1575)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[core/algorithm-queue/package-lock.json, line 2172 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1575#-N-336W--vSkorh9W3mD:-N-336W--vSkorh9W3mE:b-caceid) ([raw file](https://github.com/kube-hpc/hkube/blob/568f1746e588f212428b22b7e4e586dadfa7da84/core/algorithm-queue/package-lock.json#L2172)):*
> ```JSON
>       "integrity": "sha512-kFjcSNhnlGV1kyoGk7OXKSawH5JOb/LzUc5w9B02hOTO0dfFRjbHQKvg1d6cf3HbeUmtU9VbbV3qzZ2Teh97WQ==",
>       "requires": {
>         "has-symbols": "^1.0.2"
> ```

why did this file changed?
___
*[core/pipeline-driver/tests/setup.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1575#-N-33MVH2dR3XXUNvPga:-N-33MVH2dR3XXUNvPgb:b-92p0z7) ([raw file](https://github.com/kube-hpc/hkube/blob/465545037896e0b15e24ac9f8aab665daa976641/core/pipeline-driver/tests/setup.js#L11)):*
> ```JavaScript
> 
> before(async () => {
>     const { provider, ...options } = config.db;
> ```

why did you add it here? how did it work before?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1575)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-queue/package-lock.json, line 2172 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1575#-N-336W--vSkorh9W3mD:-N-3KZ6Q1RD4h_6utIh9:bb47oiq) ([raw file](https://github.com/kube-hpc/hkube/blob/568f1746e588f212428b22b7e4e586dadfa7da84/core/algorithm-queue/package-lock.json#L2172)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why did this file changed?
</blockquote></details>

I ran npm i since the version of the hkube/db changed.
The rest of the changes maybe due to a bad merge done before.
___
*[core/pipeline-driver/tests/setup.js, line 11 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1575#-N-33MVH2dR3XXUNvPga:-N-3L1Om4EBLzMhhsUQ7:bp8u6fa) ([raw file](https://github.com/kube-hpc/hkube/blob/465545037896e0b15e24ac9f8aab665daa976641/core/pipeline-driver/tests/setup.js#L11)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why did you add it here? how did it work before?
</blockquote></details>

Now in my query I relay on the fact that there is 'taskId' indicies. I added it, because I wanted to invoke db.init with createIndices - true.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1575#-:-N-HuF7yD5JfjV79PE-t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
