### PR TITLE
Gc taskStatus cleaner

### PR DESCRIPTION
**Pull request by awesomecakex**
When all Redis pods stop working the pipelines that are running stop working, but it only shows this as a warning in the Etcd but this warning does not transfer to mongodb so it does not show the user that there are tasks in a warning status.

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1853)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 12 of 16 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1853)* status: all files reviewed, 9 unresolved discussions (waiting on @awesomecakex)

___
*[`core/gc-service/config/main/config.base.js` line 113 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAxETc0NA5di303Q-c:-NoAxETc0NA5di303Q-d:b-m61mk1) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/config/main/config.base.js#L113)):*
> ```JavaScript
>         enabled: formatter.parseBool(process.env.TASKSTATUS_ENABLED, true),
>         settings: {
>             maxInterval:12000
> ```

pdIntervalBreach



_Code quote:_
```JavaScript
maxInterval
```
___
*[`core/gc-service/config/main/config.test.js` line 15 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAwdgl83MHMKQFRXmO:-NoAwdgl83MHMKQFRXmP:byp18fd) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/config/main/config.test.js#L15)):*
> ```JavaScript
>     taskStatus:{
>         cron: process.env.TASKSTATUS_CRON || '* * * * *',
>         // enabled: formatter.parseBool(process.env.TASKSTATUS_ENABLED, true),
> ```

Remove



_Code quote:_
```JavaScript
 // enabled: formatter.parseBool(process.env.TASKSTATUS_ENABLED, true),
```
___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 10 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAxJYm1Ls0On0audqJ:-NoAxJYm1Ls0On0audqK:b-iqb7d7) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L10)):*
> ```JavaScript
>     constructor(config) {
>         super(config);
>         this.INTERVAL = config.config.settings.maxInterval;
> ```

this.pdIntervalBreach



_Code quote:_
```JavaScript
INTERVAL
```
___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 22 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAxX0RBGbxfC4tI0F3:-NoAxX0RBGbxfC4tI0F4:b-2q6532) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L22)):*
> ```JavaScript
>         filteredGraphsList.forEach(element => {
>             graphsList.push(element.graph);
>         });
> ```

use graphList.map(.....



_Code quote:_
```JavaScript
        const graphsList = [];
        filteredGraphsList.forEach(element => {
            graphsList.push(element.graph);
        });
```
___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 30 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAxznx4uf52xOhfhdz:-NoAxznx4uf52xOhfhe-:bn8xuab) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L30)):*
> ```JavaScript
> 
>     // new
>     async handleWarnings(graphs = []) {
> ```

synchDBWithEtcdWarnings



_Code quote:_
```JavaScript
handleWarnings
```
___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 31 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAz7q24lfnYJrp-vwf:-NoAz7q24lfnYJrp-vwg:bn34bs1) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L31)):*
> ```JavaScript
>     // new
>     async handleWarnings(graphs = []) {
>         const warningGraphs = [...graphs];
> ```

No need for a new list, original list is not modified



_Code quote:_
```JavaScript
 const warningGraphs = [...graphs];
```
___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 36 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAzvcgCJzp9AF855ER:-NoAzvcgCJzp9AF855ES:b6k5qx8) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L36)):*
> ```JavaScript
>             const { jobId } = warningGraphs[i];
>             let warningExist = false;
>             let warningExistTmp = false;
> ```

warningExistTmp can be declered in an inner scope



_Code quote:_
```JavaScript
 let warningExistTmp = false;
```
___
*[`core/gc-service/tests/taskStatus/test.js` line 22 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoBBOPF-zApEkwMBChY:-NoBBOPF-zApEkwMBChZ:bc9xxgp) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/tests/taskStatus/test.js#L22)):*
> ```JavaScript
>         etcdMock.reset();
>         jobIds = await cleaner.clean();
>         expect(jobIds.length).to.equal(2);
> ```

Also check for db contnet change after clean



_Code quote:_
```JavaScript
expect(jobIds.length).to.equal(2);
```
___
*[`core/worker/bootstrap.js` line 44 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoBApXuDG9p2mI8ZweZ:-NoBApXuDG9p2mI8Zwe_:b-txc1ha) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/worker/bootstrap.js#L44)):*
> ```JavaScript
>                 log.error(data.error.message, { component });
>                 jobConsumer.sendWarning(data.error.message);
>                 log.info('The status has been changed to warning')
> ```

Can be removed, the error was logged.



_Code quote:_
```JavaScript
 log.info('The status has been changed to warning')
```

**Comment by awesomecakex** [comment]
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 31 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAz7q24lfnYJrp-vwf:-NoBTcpS2I-uE8YpuvEk:b-jumop7) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L31)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

No need for a new list, original list is not modified
</blockquote></details>

it was made so i do not modify the function parameter

**Review by awesomecakex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1853)* status: all files reviewed, 9 unresolved discussions (waiting on @golanha)

___
*[`core/gc-service/config/main/config.base.js` line 113 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAxETc0NA5di303Q-c:-NoCNFclBPGujr9FOm-E:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/config/main/config.base.js#L113)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

pdIntervalBreach
</blockquote></details>

Done.
___
*[`core/gc-service/config/main/config.test.js` line 15 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAwdgl83MHMKQFRXmO:-NoCNCd_AUNj6jFuN1Vc:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/config/main/config.test.js#L15)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 10 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAxJYm1Ls0On0audqJ:-NoCN1Nm-K83itQMAi2u:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L10)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

this.pdIntervalBreach
</blockquote></details>

Done.
___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 22 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAxX0RBGbxfC4tI0F3:-NoCMwLt9mRXl8nh9IQ7:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L22)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

use graphList.map(.....
</blockquote></details>

Done.
___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 30 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAxznx4uf52xOhfhdz:-NoCMuyq7XAgnLAJ51tz:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L30)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

synchDBWithEtcdWarnings
</blockquote></details>

Done.
___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 36 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAzvcgCJzp9AF855ER:-NoCMnhY2ZpdQCQfy6ZQ:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L36)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

warningExistTmp can be declered in an inner scope
</blockquote></details>

Done.
___
*[`core/gc-service/tests/taskStatus/test.js` line 22 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoBBOPF-zApEkwMBChY:-NoCMjBX2cHJpxe4AD_V:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/tests/taskStatus/test.js#L22)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Also check for db contnet change after clean
</blockquote></details>

Done.
___
*[`core/worker/bootstrap.js` line 44 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoBApXuDG9p2mI8ZweZ:-NoCMggPERmRT5JktZTv:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/worker/bootstrap.js#L44)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Can be removed, the error was logged.
</blockquote></details>

Done.

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @awesomecakex)

___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 22 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAxX0RBGbxfC4tI0F3:-NoFod_PCv13JcLCkjFA:b-ccx7jl) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L22)):*
<details><summary><i>Previously, awesomecakex wrote…</i></summary><blockquote>

Done.
</blockquote></details>

 const graphsList  = filteredGraphsList.map(element => {return element.grapth}
___
*[`core/gc-service/lib/cleaners/taskStatus/index.js` line 31 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1853#-NoAz7q24lfnYJrp-vwf:-NoFp_h856sQUxOhBjZf:bylys5m) ([raw file](https://github.com/kube-HPC/hkube/blob/eaa0a154a8d8ca327150195df10afce5f0d486b1/core/gc-service/lib/cleaners/taskStatus/index.js#L31)):*
<details><summary><i>Previously, awesomecakex wrote…</i></summary><blockquote>

it was made so i do not modify the function parameter
</blockquote></details>

But you done't modify the list itself any ways. Lets talk about it.

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @awesomecakex)

**Review by golanha — APPROVED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @awesomecakex)

**Pull request merged**
