### PR TITLE
fill missing data that was too large for debug algorithm

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1069)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1069)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[core/worker/lib/code-api/subpipeline/subpipeline-v1.js, line 5 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1069#-MPrQonN99takr9fHEb7:-MPrQg5kCdlI6NduLbMV:boadlyg) ([raw file](https://github.com/kube-hpc/hkube/blob/53298e44486da9e21e2049aa46c9eb05716c57bf/core/worker/lib/code-api/subpipeline/subpipeline-v1.js#L5)):*
> ```JavaScript
> async function fillMissing(element) {
>     if (element.info) {
>         if (element.info.message && element.info.message.startsWith('data too large')) {
> ```

can be shortened to `if (element.info.message?. startsWith(...)`

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1069)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/worker/lib/code-api/subpipeline/subpipeline-v1.js, line 5 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1069#-MPrQonN99takr9fHEb7:-MPr_Mvg5v7iPPjXXAn1:bb7f2mf) ([raw file](https://github.com/kube-hpc/hkube/blob/53298e44486da9e21e2049aa46c9eb05716c57bf/core/worker/lib/code-api/subpipeline/subpipeline-v1.js#L5)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

can be shortened to `if (element.info.message?. startsWith(...)`
</blockquote></details>

done

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1069)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
