### PR TITLE
feat: algorithm-queue scale

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1318)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1318)* status: all files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[core/algorithm-queue/lib/queues-manager.js, line 77 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1318#-MdrJ8TO4bnXhDrGnzh8:-MdrJ8TO4bnXhDrGnzh9:b48cuyi) ([raw file](https://github.com/kube-hpc/hkube/blob/3481156437dbbb5a1473101dd456d178ab580df1/core/algorithm-queue/lib/queues-manager.js#L77)):*
> ```JavaScript
>     async _checkIdleAlgorithms() {
>         const queues = Array.from(this._queues.values());
>         const isIdle = queues.filter(q => q.isIdle());
> ```

You first check this._isIdle and only after you call checkIdle?
___
*[core/algorithm-queue/lib/queues-manager.js, line 79 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1318#-MdrJhQU1s4ZaQVMtHOI:-MdrJhQU1s4ZaQVMtHOJ:bjj0ngi) ([raw file](https://github.com/kube-hpc/hkube/blob/3481156437dbbb5a1473101dd456d178ab580df1/core/algorithm-queue/lib/queues-manager.js#L79)):*
> ```JavaScript
>         const isIdle = queues.filter(q => q.isIdle());
>         const isStaled = queues.filter(q => q.isStaled());
>         await Promise.all(queues.map(a => a.checkIdle()));
> ```

why do you call checkIdle here?
___
*[core/algorithm-queue/lib/queues-manager.js, line 81 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1318#-MdrJUxVE_7qakml3fVL:-MdrJUxVE_7qakml3fVM:b-qbwhci) ([raw file](https://github.com/kube-hpc/hkube/blob/3481156437dbbb5a1473101dd456d178ab580df1/core/algorithm-queue/lib/queues-manager.js#L81)):*
> ```JavaScript
>         await Promise.all(queues.map(a => a.checkIdle()));
>         await Promise.all(isIdle.map(q => q.pause()));
>         await Promise.all(isStaled.map(async q => {
> ```

you can call Promise.allSettled and map the results with the error
___
*[core/algorithm-queue/lib/jobs/consumer.js, line 42 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1318#-MdrJpZcBZ_sEbm5RNTv:-MdrJpZcBZ_sEbm5RNTw:bbms4rc) ([raw file](https://github.com/kube-hpc/hkube/blob/3481156437dbbb5a1473101dd456d178ab580df1/core/algorithm-queue/lib/jobs/consumer.js#L42)):*
> ```JavaScript
>     }
> 
>     async pause() {
> ```

no resume?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1318)* status: all files reviewed, 4 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-queue/lib/queues-manager.js, line 77 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1318#-MdrJ8TO4bnXhDrGnzh8:-MduYhZzE8QMdRSzV3Qa:bjdlqz) ([raw file](https://github.com/kube-hpc/hkube/blob/3481156437dbbb5a1473101dd456d178ab580df1/core/algorithm-queue/lib/queues-manager.js#L77)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

You first check this._isIdle and only after you call checkIdle?
</blockquote></details>

If the `checkIdle` set to true,  the `_isIdle` will be relevant in the next tick (5 sec).
___
*[core/algorithm-queue/lib/queues-manager.js, line 81 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1318#-MdrJUxVE_7qakml3fVL:-Mdu_BpX8Ps2MiO1N06n:b-tm80vt) ([raw file](https://github.com/kube-hpc/hkube/blob/3481156437dbbb5a1473101dd456d178ab580df1/core/algorithm-queue/lib/queues-manager.js#L81)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

you can call Promise.allSettled and map the results with the error
</blockquote></details>

This is not much cleaner in this case

```
const all = await Promise.allSettled(isStaled.map(async q => this._removeAction(q.algorithmName, 'idle', false)));
const rejected = all.filter(a => a.status === 'rejected');
if (rejected.length) {
      rejected.forEach(r => {
          log.throttle.error(`error removing idle queue ${q.algorithmName} ${e.message}`, { component }, e);
          });
}
```
___
*[core/algorithm-queue/lib/jobs/consumer.js, line 42 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1318#-MdrJpZcBZ_sEbm5RNTv:-Mdu_QJLEB1LiIAyszyh:b-rgo2uq) ([raw file](https://github.com/kube-hpc/hkube/blob/3481156437dbbb5a1473101dd456d178ab580df1/core/algorithm-queue/lib/jobs/consumer.js#L42)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

no resume?
</blockquote></details>

Once it paused it means it was idle & empty for a long time, so in this case, I want to shut it down anyway.
If there is a demand for that algorithm it will be up again.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1318#-:-MdubEKcD7-tLRZ6QNel:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Pull request merged**
