### PR TITLE
feat: add queue active by timestamp

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1353)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1353)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/algorithm-operator/lib/reconcile/algorithm-queue.js, line 116 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1353#-MgAFLhf8nMtOfypjMnr:-MgAFLhf8nMtOfypjMns:byrautb) ([raw file](https://github.com/kube-hpc/hkube/blob/caa6b17d5afabd8c32684dc1dfec8047b77d22db/core/algorithm-operator/lib/reconcile/algorithm-queue.js#L116)):*
> ```JavaScript
> 
> const reconcile = async ({ deployments, algorithms, discovery, versions, registry, clusterOptions, resources, options, devMode } = {}) => {
>     const { limit, algorithmMinIdleTimeMS } = options.algorithmQueueBalancer;
> ```

shouldn't it be maxIdleTime?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1353)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/algorithm-operator/lib/reconcile/algorithm-queue.js, line 116 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1353#-MgAFLhf8nMtOfypjMnr:-MgAVfTj6KDKvjfmpvUS:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/caa6b17d5afabd8c32684dc1dfec8047b77d22db/core/algorithm-operator/lib/reconcile/algorithm-queue.js#L116)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

shouldn't it be maxIdleTime?
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1353#-:-MgAWEGr2dOC6Nws2Owh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Pull request merged**
