### PR TITLE
remove nodeselector warning summary 

### PR DESCRIPTION
**Pull request by RonShvarz**
Removing node selector summary message, it is elaborated upon in the complexResourceDescriptor,

Summary still holds the error message when node selector is the issue itself.

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1747)

### CODE REVIEW

**Comment by RonShvarz** [comment]
kube-HPC/hkube#1738

**Comment by RonShvarz** [comment]
image

New message - now summary doesn't comtain node selector when it is not the culprit of an error.

**Review by golanha — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1747)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RonShvarz)

**Comment by RonShvarz** [comment]
image

Node selector removed from summary in task-executor

**Pull request merged**
