### PR TITLE
algorithm-deps-install

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1081)

### CODE REVIEW

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 18 of 20 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1081#-:-MQHCtGtEZUW76rZmyoR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/api-server/lib/service/builds.js, line 225 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1081#-MQHC8QfDqeSLQkz4yVW:-MQHC8Qg9HnI8BmFnCQh:b1hjfux) ([raw file](https://github.com/kube-hpc/hkube/blob/f0126ddc46d660f456b6e0716f892966692c09f3/core/api-server/lib/service/builds.js#L225)):*
> ```
> dependencyInstallCmd 
> ```
You can add a test for that, just copy a test from tests/algorithms-store.js with:
"a build was triggered due to"

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1081)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/lib/service/builds.js, line 225 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1081#-MQHC8QfDqeSLQkz4yVW:-MQHUU7eDgD_ZFxT-Xeb:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/f0126ddc46d660f456b6e0716f892966692c09f3/core/api-server/lib/service/builds.js#L225)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> dependencyInstallCmd 
> ```
You can add a test for that, just copy a test from tests/algorithms-store.js with:
"a build was triggered due to"
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1081#-:-MQHWuP4C21EgNzULJ-E:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
