### PR TITLE
bring debs for dockerfile install

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/975)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
Why not download the debs like we do for other dependencies? Like we do here: `core/algorithm-builder/dockerfile/get-deps-java.sh`

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/975#-:-MJ_smds7hpJrvarV-3J:bmx8seu)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 7 at r1](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJ_tE-G-92QdRzKB_pJ:-MJ_tE-G-92QdRzKB_pK:b-vm2qp1) ([raw file](https://github.com/kube-hpc/hkube/blob/510c30cfa79ca41e2d2287f5e5cc94186a4ea264/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L7)):*
> ```
> COPY  ./dockerfile/cpy-settings ./algorithm_unique_folder/src/main/resources/settings.xml* /root/.m2/
> COPY ./jars/* /hkube/algorithm-runner/
> COPY ./debs /hkube/algorithm-runner/
> ```

Put it in /deps or /libjzmq or something. It doesn't need to be with the algorithm
Also, you use it in the second build container (FROM ${baseImage}), so you can copy it there
___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 15 at r1](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJ_tvs43i1JBk2V72Po:-MJ_tvs43i1JBk2V72Pp:b-nuqqdg) ([raw file](https://github.com/kube-hpc/hkube/blob/510c30cfa79ca41e2d2287f5e5cc94186a4ea264/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L15)):*
> ```
> baseImage
> ```
Not completely relevant to this PR, but currently the base image in [config](https://github.com/kube-HPC/hkube/blob/master/core/algorithm-builder/config/main/config.base.js#L57) does not have a tag, which implies latest. Using latest is not best practice. Pick an actual tag from docker hub and use it
___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 20 at r1](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJ_tb-pDcjahzQoYy92:-MJ_tb-pDcjahzQoYy93:b-pbkw2u) ([raw file](https://github.com/kube-hpc/hkube/blob/510c30cfa79ca41e2d2287f5e5cc94186a4ea264/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L20)):*
> ```
> WORKDIR /hkube/algorithm-runner
> RUN mkdir -p /hkube-logs
> RUN  dpkg -i libpgm-5.2-0_5.2.122~dfsg-2_amd64.deb && dpkg -i libnorm1_1.5r6+dfsg1-6_amd64.deb && dpkg -i libsodium23_1.0.16-2_amd64.deb && dpkg -i libzmq5_4.2.5-1ubuntu0.2_amd64.deb && dpkg -i libzmq-jni_3.1.0-10_amd64.deb && dpkg -i libzmq-java_3.1.0-10_amd64.deb
> ```

If all of the debs are in one folder (e.g. /pkg) you can just run `dpkg -i *.deb`)

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/975)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 7 at r1](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJ_tE-G-92QdRzKB_pJ:-MJgJVPE2rQbYu1mWAjn:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/5988bfc5d422777a1e1b4e6e068b208410c915b3/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L7)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Put it in /deps or /libjzmq or something. It doesn't need to be with the algorithm
Also, you use it in the second build container (FROM ${baseImage}), so you can copy it there
</blockquote></details>

Done.
___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 15 at r1](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJ_tvs43i1JBk2V72Po:-MJgJXel-kRXO2FhN8yt:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/5988bfc5d422777a1e1b4e6e068b208410c915b3/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L15)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> baseImage
> ```
Not completely relevant to this PR, but currently the base image in [config](https://github.com/kube-HPC/hkube/blob/master/core/algorithm-builder/config/main/config.base.js#L57) does not have a tag, which implies latest. Using latest is not best practice. Pick an actual tag from docker hub and use it
</blockquote></details>

Done.
___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 20 at r1](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJ_tb-pDcjahzQoYy92:-MJbb_OF1ZGNJwCvzyAs:b-6kmwnb) ([raw file](https://github.com/kube-hpc/hkube/blob/5988bfc5d422777a1e1b4e6e068b208410c915b3/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L20)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

If all of the debs are in one folder (e.g. /pkg) you can just run `dpkg -i *.deb`)
</blockquote></details>

their order matters.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/975)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[core/algorithm-builder/.travis.yml, line 18 at r2](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJgPGk28nyiu9cU8spw:-MJgP7ch-Ur6LnL4jQkv:b-upfr1d) ([raw file](https://github.com/kube-hpc/hkube/blob/adfdd512a449d553f452a5ceba64ce02fc3bf036/core/algorithm-builder/.travis.yml#L18)):*
> ```YAML
> install:
>   - npm ci
>   - apt-get -y apt-rdepends
> ```

you don't use apt-rdepends
also, this file is not used in the build
___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 20 at r1](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJ_tb-pDcjahzQoYy92:-MJgRlKT5RBb9Mf7ZtEN:b-gvxsnn) ([raw file](https://github.com/kube-hpc/hkube/blob/5988bfc5d422777a1e1b4e6e068b208410c915b3/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L20)):*
> dpkg -i *.deb
i tried it again, and it seems that it installed correctly (I didn't test with actual JAVA code)

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/975)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-builder/.travis.yml, line 18 at r2](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJgPGk28nyiu9cU8spw:-MJu57-h0TEpR50lSJzN:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/adfdd512a449d553f452a5ceba64ce02fc3bf036/core/algorithm-builder/.travis.yml#L18)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

you don't use apt-rdepends
also, this file is not used in the build
</blockquote></details>

Done.
___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 20 at r1](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJ_tb-pDcjahzQoYy92:-MJu4yFI0XUASmfXLNg2:bj0h93n) ([raw file](https://github.com/kube-hpc/hkube/blob/5988bfc5d422777a1e1b4e6e068b208410c915b3/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L20)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> dpkg -i *.deb
i tried it again, and it seems that it installed correctly (I didn't test with actual JAVA code)
</blockquote></details>

I tried again, on my laptop it worked fine but on the java docker image, it didn't.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/975)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[core/algorithm-builder/dockerfile/get-deps-java.sh, line 9 at r3](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJuQRoD7C_9iCMri8Kv:-MJuQRoE5norh25Lowdq:bcubutc) ([raw file](https://github.com/kube-hpc/hkube/blob/411b31d2cf6c598ba0490f97ae5229130f0bbbaf/core/algorithm-builder/dockerfile/get-deps-java.sh#L9)):*
> ```
> debs
> ```
better add this folder to .gitignore so we don't accidentally add it to git. like [here](https://github.com/kube-HPC/hkube/blob/support_libzmq-java_in_close_sys/core/algorithm-builder/.gitignore#L10-L11)

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/975)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/algorithm-builder/dockerfile/get-deps-java.sh, line 9 at r3](https://reviewable.io/reviews/kube-hpc/hkube/975#-MJuQRoD7C_9iCMri8Kv:-MJuYhhH8Oiozk78SztT:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/411b31d2cf6c598ba0490f97ae5229130f0bbbaf/core/algorithm-builder/dockerfile/get-deps-java.sh#L9)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> debs
> ```
better add this folder to .gitignore so we don't accidentally add it to git. like [here](https://github.com/kube-HPC/hkube/blob/support_libzmq-java_in_close_sys/core/algorithm-builder/.gitignore#L10-L11)
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/975#-:-MJuZ4RaBzfir7c-A905:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
