### PR TITLE
pipeline-driver-queue latency issue

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1301)

### CODE REVIEW

**Comment by NassiHarel** [comment]
I will add stats to the pipeline-driver, such as min/max/avg jobs so we could see in the dashboard the workload

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1301)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/pipeline-driver/lib/consumer/jobs-consumer.js, line 89 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1301#-McdzvYzAIqr6ocUUzxa:-McdzvZ-9cdZQ0nHs8hI:b-bjqej8) ([raw file](https://github.com/kube-hpc/hkube/blob/cffbae2f17113b67aad24fd36515cdf6c3af2947/core/pipeline-driver/lib/consumer/jobs-consumer.js#L89)):*
> ```JavaScript
>                 }
>                 if (jobs.length > this._maxJobs) {
>                     this._maxJobs = jobs.length;
> ```

If max jobs is never cleared, will this info be relevant after the driver has been up for a few days?
___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 94 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1301#-Mce6Eus7J3lNEUaNZls:-Mce6Eut3GEUXIYd-NpZ:bpz96w6) ([raw file](https://github.com/kube-hpc/hkube/blob/cffbae2f17113b67aad24fd36515cdf6c3af2947/core/pipeline-driver-queue/lib/jobs/producer.js#L94)):*
> ```JavaScript
>         }).on(Events.COMPLETED, (data) => {
>             log.info(`${Events.COMPLETED} ${data.jobId}`, { component, jobId: data.jobId, status: Events.COMPLETED });
>             this._checkMaxExceeded(data.options.data);
> ```

There is a bug with maxExcedded. after a pipeline finishes, the next one does not start

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1301)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 94 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1301#-Mce6Eus7J3lNEUaNZls:-Mce6pGTD8XVb9nYGEJD:b3bdmfm) ([raw file](https://github.com/kube-hpc/hkube/blob/cffbae2f17113b67aad24fd36515cdf6c3af2947/core/pipeline-driver-queue/lib/jobs/producer.js#L94)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

There is a bug with maxExcedded. after a pipeline finishes, the next one does not start
</blockquote></details>

Only if I send another job then the next 10 concurrent start

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1301)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/pipeline-driver/lib/consumer/jobs-consumer.js, line 89 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1301#-McdzvYzAIqr6ocUUzxa:-Mci-5ycB6u5lMkC3OtL:bg3rznm) ([raw file](https://github.com/kube-hpc/hkube/blob/cffbae2f17113b67aad24fd36515cdf6c3af2947/core/pipeline-driver/lib/consumer/jobs-consumer.js#L89)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

If max jobs is never cleared, will this info be relevant after the driver has been up for a few days?
</blockquote></details>

This is meant for us to check if a driver has reached its max concurrency.
You can always delete the pod...
___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 94 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1301#-Mce6Eus7J3lNEUaNZls:-Mci-VPOD7Ix1igWBUEW:b5718le) ([raw file](https://github.com/kube-hpc/hkube/blob/cffbae2f17113b67aad24fd36515cdf6c3af2947/core/pipeline-driver-queue/lib/jobs/producer.js#L94)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Only if I send another job then the next 10 concurrent start
</blockquote></details>

I add a test for it, I hope it will catch it...

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1301)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/pipeline-driver-queue/lib/persistency/persistence.js, line 42 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1301#-Mci46w49Fw74V9aS-eA:-Mci46w49Fw74V9aS-eB:b-bzep7r) ([raw file](https://github.com/kube-hpc/hkube/blob/55681bb6ebeeaa402e5fe07976c1b47dc7db0260/core/pipeline-driver-queue/lib/persistency/persistence.js#L42)):*
> ```JavaScript
> 
>     async getJob({ jobId }) {
>         return this._db.jobs.fetch({ jobId, fields: { status: true, pipeline: true } });
> ```

Pipeline can be huge. especially the flowInput. Do we need to fetch all of it?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1301)* status: all files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/pipeline-driver-queue/lib/persistency/persistence.js, line 42 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1301#-Mci46w49Fw74V9aS-eA:-Mci8WT7-fQ-6Ef0AvAx:bnkv5s1) ([raw file](https://github.com/kube-hpc/hkube/blob/55681bb6ebeeaa402e5fe07976c1b47dc7db0260/core/pipeline-driver-queue/lib/persistency/persistence.js#L42)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Pipeline can be huge. especially the flowInput. Do we need to fetch all of it?
</blockquote></details>

Yes, you are right....
btw, I think that we don't need to save the `flowInput` in Mongo, only in the object-storage.

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1301)* status: all files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/pipeline-driver-queue/lib/persistency/persistence.js, line 42 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1301#-Mci46w49Fw74V9aS-eA:-Mci96wo6hW_47Y9uA_2:b9gbs9m) ([raw file](https://github.com/kube-hpc/hkube/blob/55681bb6ebeeaa402e5fe07976c1b47dc7db0260/core/pipeline-driver-queue/lib/persistency/persistence.js#L42)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Yes, you are right....
btw, I think that we don't need to save the `flowInput` in Mongo, only in the object-storage.
</blockquote></details>

The pipeline driver also fetch the entire pipeline....
We need to change this....

**Review by yehiyam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1301)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/pipeline-driver-queue/lib/persistency/persistence.js, line 42 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1301#-Mci46w49Fw74V9aS-eA:-MciAG121nZckN68kits:bn27szc) ([raw file](https://github.com/kube-hpc/hkube/blob/55681bb6ebeeaa402e5fe07976c1b47dc7db0260/core/pipeline-driver-queue/lib/persistency/persistence.js#L42)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

The pipeline driver also fetch the entire pipeline....
We need to change this....
</blockquote></details>

we can also save it as a top level object - like the graph. This way it will not be duplicated between pipeline and userPipeline, and it will also be easier to filter out.
We can do a little thinking about that when we meet in the office

**Review by yehiyam — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1301#-:-MciArlUChb27HJzE-pM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

**Pull request merged**
