### PR TITLE
copy to local repository

### PR DESCRIPTION
**Pull request by golanha**
/deploy

---
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/989)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/989)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[core/algorithm-builder/dockerfile/get-deps-java.sh, line 11 at r1](https://reviewable.io/reviews/kube-hpc/hkube/989#-MK4w6wv2ievdhzgjWuJ:-MK4w6wv2ievdhzgjWuK:byi65pb) ([raw file](https://github.com/kube-hpc/hkube/blob/2ebd95b42d0cae72e6b69a12e764f9c0e922404c/core/algorithm-builder/dockerfile/get-deps-java.sh#L11)):*
> ```Shell
> mkdir -p $SCRIPTPATH/../environments/java/debs
> cd $SCRIPTPATH/../environments/java/debs
> docker run --rm --workdir /tmp/pkg -v $PWD:/tmp/pkg adoptopenjdk/openjdk11:jre-11.0.8_10-ubuntu  apt-get update && apt-get download $(apt-cache depends --recurse --no-recommends --no-suggests  --no-conflicts --no-breaks --no-replaces --no-enhances  --no-pre-depends libzmq-java | grep "^\w")
> ```

back to what it was
___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 21 at r1](https://reviewable.io/reviews/kube-hpc/hkube/989#-MK4x3FCDA22b102FAsq:-MK4x3FCDA22b102FAsr:b-puq0mg) ([raw file](https://github.com/kube-hpc/hkube/blob/2ebd95b42d0cae72e6b69a12e764f9c0e922404c/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L21)):*
> ```
> WORKDIR /hkube/algorithm-runner
> RUN mkdir -p /hkube-logs
> CMD ["/bin/sh", "-c", "./runJava.sh"]
> ```

redirect stdout to file for logs like in python and node

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/989)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-builder/dockerfile/get-deps-java.sh, line 11 at r1](https://reviewable.io/reviews/kube-hpc/hkube/989#-MK4w6wv2ievdhzgjWuJ:-MK5-Dmy-vSBL7NqlRd5:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/2ebd95b42d0cae72e6b69a12e764f9c0e922404c/core/algorithm-builder/dockerfile/get-deps-java.sh#L11)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

back to what it was
</blockquote></details>

Done.
___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 21 at r1](https://reviewable.io/reviews/kube-hpc/hkube/989#-MK4x3FCDA22b102FAsq:-MK5-ExC0zxWgNnVn41m:b-wszcca) ([raw file](https://github.com/kube-hpc/hkube/blob/2ebd95b42d0cae72e6b69a12e764f9c0e922404c/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L21)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

redirect stdout to file for logs like in python and node
</blockquote></details>

exists in runJava script

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/989)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
