### PR TITLE
Sidecar feature

### PR DESCRIPTION
**Pull request by Adir111**
Sidecar feature, related issue: kube-HPC/hkube#1821

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/2033)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 3 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/2033)* status: 3 of 39 files reviewed, 1 unresolved discussion (waiting on @Adir111)

___
*[`core/api-server/api/graphql/schemas/log-schema.js` line 26 at r1](https://reviewable.io/reviews/kube-HPC/hkube/2033#-OEz5xw8B8dfnvVeSAoC:-OEz5xw8B8dfnvVeSAoD:bsoe8sm) ([raw file](https://github.com/kube-HPC/hkube/blob/1813338f71aec3081512a08757350340ad79cbf4/core/api-server/api/graphql/schemas/log-schema.js#L26)):*
> ```JavaScript
>       sideCarNames: [String]
>     ): LogsMainType
>   }
> ```

Try replacing the sideCarNames with containerNames that will be ["Algorunner"] by default.
Now see how you revision the whole implementation. sideCar don't need any prefix same way as algorithm output doesn't have.



_Code quote:_
```JavaScript
  extend type Query {
    logsByQuery(
      podName: String!
      taskId: String
      source: String
      nodeKind: String
      logMode: String
      searchWord: String
      taskTime: String
      limit: Int
      sideCarNames: [String]
    ): LogsMainType
  }
```

**Review by Adir111 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/2033)* status: 0 of 39 files reviewed, 1 unresolved discussion (waiting on @Adir111 and @golanha)

___
*[`core/api-server/api/graphql/schemas/log-schema.js` line 26 at r1](https://reviewable.io/reviews/kube-HPC/hkube/2033#-OEz5xw8B8dfnvVeSAoC:-OF1kJRi1NV5r6BV94KQ:bxblqr4) ([raw file](https://github.com/kube-HPC/hkube/blob/1813338f71aec3081512a08757350340ad79cbf4/core/api-server/api/graphql/schemas/log-schema.js#L26)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Try replacing the sideCarNames with containerNames that will be ["Algorunner"] by default.
Now see how you revision the whole implementation. sideCar don't need any prefix same way as algorithm output doesn't have.
</blockquote></details>

Done.
Now the code is more modular.

**Review by golanha — APPROVED** [review]
> Reviewed 30 of 39 files at r1, 4 of 7 files at r2, 2 of 3 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/2033)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Adir111)

**Comment by golanha** [comment]
If no volumes are defined for sidecar taskexecutor fails:
"level":"error","message":"Cannot read properties of undefined (reading 'forEach')","meta":{"hostName":"task-executor-7ff98c6f9d-84vr7","internal":{"component":"Executor"},"timestamp":1736064612473,"trace":[{"column":17,"file":"/hkube/task-executor/lib/reconcile/resources.js","line":175,"method":null},{"column":null,"file":null,"line":null,"method":"Array.forEach"},{"column":14,"file":"/hkube/task-executor/lib/reconcile/resources.js","line":173,"method":"_getMissingSideCarVolumes"},{"column":35,"file":"/hkube/task-executor/lib/reconcile/resources.js","line":217,"method":"shouldAddJob"},{"column":64,"file":"/hkube/task-executor/lib/reconcile/resources.js","line":375,"method":"cb"},{"column":null,"file":null,"line":null,"method":"Array.forEach"},{"column":22,"file":"/hkube/task-executor/lib/reconcile/resources.js","line":392,"method":"matchJobsToResources"},{"column":34,"file":"/hkube/task-executor/lib/reconcile/reconciler.js","line":636,"method":"Object.reconcile"},{"column":5,"file":"node:internal/process/task_queues","line":95,"method":"process.processTicksAndRejections"},{"column":35,"file":"/hkube/task-executor/lib/executor.js","line":97,"method":"async Executor._algorithmsHandle"},{"column":null,"file":null,"line":null,"method":"async Promise.all (index"},{"column":13,"file":"/hkube/task-executor/lib/executor.js","line":77,"method":"async Executor._interval"}],"type":"task-executor","uptime":8990.43}}

**Pull request merged**
