### PR TITLE
Added overwrite to pipeline insert

### PR DESCRIPTION
**Pull request by RonShvarz**
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1884)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1884)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @RonShvarz)

___
*[`core/api-server/lib/service/pipelines.js` line 211 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1884#-NqLjcKABmCed0LzKiHs:-NqLjcKABmCed0LzKiHt:b-f6e9i3) ([raw file](https://github.com/kube-HPC/hkube/blob/e462d6cc9c19783a9c1ef9c52abc67a8c9ee51d4/core/api-server/lib/service/pipelines.js#L211)):*
> ```JavaScript
>                     const updatedPipeline = await this.updatePipeline(options);
>                     return updatedPipeline;
>                 }
> ```

what if some pipelnes are new and don't exsit? 
Overwrite doesn't mean update, it means create or update.



_Code quote:_
```JavaScript
                try {
                    const updatedPipeline = await this.updatePipeline(options);
                    return updatedPipeline;
                }
```

**Review by golanha — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1884)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @RonShvarz)

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1884)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`core/api-server/lib/service/pipelines.js` line 211 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1884#-NqLjcKABmCed0LzKiHs:-NqRAiZJ3mnj5Ab4YNuJ:b-jkxbbk) ([raw file](https://github.com/kube-HPC/hkube/blob/e462d6cc9c19783a9c1ef9c52abc67a8c9ee51d4/core/api-server/lib/service/pipelines.js#L211)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

what if some pipelnes are new and don't exsit? 
Overwrite doesn't mean update, it means create or update.
</blockquote></details>

The piece of code initiates on the condition of "pipeline exists", so it's all covered.

**Pull request merged**
