### PR TITLE
get Streaming Flow Graph

### PR DESCRIPTION
**Pull request by zivglik**
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1803)

### CODE REVIEW

**Comment by zivglik** [comment]
kube-HPC/hkube#1788

**Review by golanha — CHANGES_REQUESTED** [review]
Fails on lint. please install the lint plugin and fix

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1803#-:-Nh13b3hBK__5zgNQKFB:b-kzh4p4)* status: all files reviewed, 1 unresolved discussion (waiting on @zivglik)

___
*[`core/api-server/api/rest-api/routes/v1/store.js` line 33 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1803#-Nh15A7G5lAoKQ38pa4l:-Nh15A7G5lAoKQ38pa4m:b7i6vjd) ([raw file](https://github.com/kube-HPC/hkube/blob/f7ea56b34db09618a515430b4a395a025d13d91f/core/api-server/api/rest-api/routes/v1/store.js#L33)):*
> ```JavaScript
>     });
> 
>     router.post('/pipelines/graph', async (req, res) => {
> ```

You also need to expose this api in swagger

**Review by golanha — APPROVED** [review]
> Reviewed 2 of 15 files at r2, 2 of 12 files at r3, 1 of 1 files at r7, 1 of 3 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1803)* status: 8 of 19 files reviewed, 1 unresolved discussion (waiting on @zivglik)

**Pull request merged**
