### PR TITLE
add ingress type

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1355)

### CODE REVIEW

**Comment by yehiyam** [comment]
for kube-HPC/hkube#1354

**Comment by yehiyam** [comment]
blocked by https://github.com/kube-HPC/kubernetes-client.hkube/pull/20

**Review by NassiHarel — DISMISSED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1355#-:-MgAZcyb3pY5uoWCMVEi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1355#-:-MgKxH4zDbppzEcywG11:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
