### PR TITLE
concurrency updates

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1538)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 14 of 16 files at r1, 2 of 2 files at r2, 2 of 2 files at r3, 6 of 9 files at r4, 3 of 3 files at r5, 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1538)* status: 25 of 26 files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/api-server/package.json, line 3 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1538#-MxXqRH7D7K51MdSXLnI:-MxXqRH7D7K51MdSXLnJ:bfdweb5) ([raw file](https://github.com/kube-hpc/hkube/blob/82d881e853d9d7a8d57687ce4b603474a3b0fd95/core/api-server/package.json#L3)):*
> ```JSON
> {
>     "name": "api-server",
>     "version": "2.3.1-a",
> ```

Did you leave the 2.3.1-a on purpose?
___
*[core/api-server/tests/webhooks.js, line 7 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1538#-MxY-VAT7VW5-lIKPtyv:-MxY-VAT7VW5-lIKPtyw:b9p46fi) ([raw file](https://github.com/kube-hpc/hkube/blob/82d881e853d9d7a8d57687ce4b603474a3b0fd95/core/api-server/tests/webhooks.js#L7)):*
> ```JavaScript
> const stateManager = require('../lib/state/state-manager');
> const { delay, request } = require('./utils');
> const { workerStub } = require('./mocks');
> ```

Is the workerStub used?



_Code quote:_
```JavaScript
{ workerStub } 
```
___
*[core/pipeline-driver-queue/tests/concurrencyTests.js, line 75 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1538#-MxYWSno2rU28DjY_uX4:-MxYWSno2rU28DjY_uX5:bfol6of) ([raw file](https://github.com/kube-hpc/hkube/blob/82d881e853d9d7a8d57687ce4b603474a3b0fd95/core/pipeline-driver-queue/tests/concurrencyTests.js#L75)):*
> ```JavaScript
>         });
> 
>         it('should handle preferred queue concurrent jobs', async () => {
> ```

Maybe you check that the jobs from preferred is dequeued first.

**Review by golanha — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1538)* status: 25 of 26 files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1538)* status: 23 of 26 files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[core/api-server/package.json, line 3 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1538#-MxXqRH7D7K51MdSXLnI:-MxYhUP45l6g9DokhIrI:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/82d881e853d9d7a8d57687ce4b603474a3b0fd95/core/api-server/package.json#L3)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Did you leave the 2.3.1-a on purpose?
</blockquote></details>

Done.
___
*[core/api-server/tests/webhooks.js, line 7 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1538#-MxY-VAT7VW5-lIKPtyv:-MxYhWD07O2ShZBwbKwT:b-1d1etg) ([raw file](https://github.com/kube-hpc/hkube/blob/82d881e853d9d7a8d57687ce4b603474a3b0fd95/core/api-server/tests/webhooks.js#L7)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Is the workerStub used?
</blockquote></details>

It is used in the newer commits
___
*[core/pipeline-driver-queue/tests/concurrencyTests.js, line 75 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1538#-MxYWSno2rU28DjY_uX4:-MxYhOWb48A7ClFqOn-d:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/82d881e853d9d7a8d57687ce4b603474a3b0fd95/core/pipeline-driver-queue/tests/concurrencyTests.js#L75)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Maybe you check that the jobs from preferred is dequeued first. 
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1538#-:-MxYmanc4Qmx97KrEdRo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Review by golanha — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1538)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
