### PR TITLE
Count active when producing jobs

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1503)

### CODE REVIEW

**Review by NassiHarel — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1503)* status: all files reviewed, 4 unresolved discussions (waiting on @yehiyam)

___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 20 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtCTTX06des75MyLnOa:-MtCTTX06des75MyLnOb:b-70p53h) ([raw file](https://github.com/kube-hpc/hkube/blob/c27e717ed3702cb40cd2f3d29ef351370aedc5f3/core/pipeline-driver-queue/lib/jobs/producer.js#L20)):*
> ```JavaScript
>         this._updateState = this._updateState.bind(this);
>         this._groupActiveJobs = {};
>         this._pipelines = {};
> ```

Here is an object, but you use it as an array



_Code quote:_
```JavaScript
this._pipelines = {};
```
___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 20 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtCTbzH2iescYUhJ7vD:-MtCTbzH2iescYUhJ7vE:b-t498fj) ([raw file](https://github.com/kube-hpc/hkube/blob/c27e717ed3702cb40cd2f3d29ef351370aedc5f3/core/pipeline-driver-queue/lib/jobs/producer.js#L20)):*
> ```JavaScript
>         this._updateState = this._updateState.bind(this);
>         this._groupActiveJobs = {};
>         this._pipelines = {};
> ```

isn't better to create a single data structure (map)?
like:

```
pipeline  <string>
     concurrency <int>
     running        <int>
     
```



_Code quote:_
```JavaScript
        this._groupActiveJobs = {};
        this._pipelines = {};
```
___
*[core/pipeline-driver-queue/tests/test.js, line 36 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtCUmxi6k525QGEkHbu:-MtCUmxi6k525QGEkHbv:b4rs4rt) ([raw file](https://github.com/kube-hpc/hkube/blob/c27e717ed3702cb40cd2f3d29ef351370aedc5f3/core/pipeline-driver-queue/tests/test.js#L36)):*
> ```JavaScript
>     });
>     let _semaphore = null;
>     beforeEach(async () => {
> ```

Please add tests to a separate file, the conflicts are trouble...
___
*[core/pipeline-driver-queue/tests/test.js, line 43 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtCUaik-U2Ip-wRImKc:-MtCUaik-U2Ip-wRImKd:bfyfmec) ([raw file](https://github.com/kube-hpc/hkube/blob/c27e717ed3702cb40cd2f3d29ef351370aedc5f3/core/pipeline-driver-queue/tests/test.js#L43)):*
> ```JavaScript
>         producerLib._isConsumerActive=true;
>     });
>     describe('algorithm queue', () => {
> ```

algorithm queue?



_Code quote:_
```JavaScript
algorithm queue
```

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1503)* status: all files reviewed, 5 unresolved discussions (waiting on @yehiyam)

___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 20 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtCVAic3w8gE5BxDi9h:-MtCVAic3w8gE5BxDi9i:b-oqfmve) ([raw file](https://github.com/kube-hpc/hkube/blob/c27e717ed3702cb40cd2f3d29ef351370aedc5f3/core/pipeline-driver-queue/lib/jobs/producer.js#L20)):*
> ```JavaScript
>         this._updateState = this._updateState.bind(this);
>         this._groupActiveJobs = {};
>         this._pipelines = {};
> ```

make this code more generic, also separate to different files so you can easily apply this to master



_Code quote:_
```JavaScript
 this._pipelines = {};
```

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1503)* status: 3 of 9 files reviewed, 9 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 12 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtI3qHp0PRlg3kFjLDc:-MtI3qHp0PRlg3kFjLDd:byc1l6q) ([raw file](https://github.com/kube-hpc/hkube/blob/fcc43296981ed4bcfb59cf2b2773a277d6e5d642/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L12)):*
> ```JavaScript
> class ConcurrencyHandler {
>     constructor(producer, options) {
>         this._groupActiveJobs = {};
> ```

I think that single data structure is better :-)



_Code quote:_
```JavaScript
        this._groupActiveJobs = {};
        this._pipelines = [];
```
___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 14 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtI3Ehl056yzbaMHtTq:-MtI3Ehl056yzbaMHtTr:b-dib45r) ([raw file](https://github.com/kube-hpc/hkube/blob/fcc43296981ed4bcfb59cf2b2773a277d6e5d642/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L14)):*
> ```JavaScript
>         this._groupActiveJobs = {};
>         this._pipelines = [];
>         this._producer = producer;
> ```

Instead of passing the producer as a ref, you can pass a callback/event and when you call `_cancelExceededJob` just trigger it



_Code quote:_
```JavaScript
this._producer = producer;
```
___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 39 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtI4VxR3_LqMJp2wrPv:-MtI4VxR3_LqMJp2wrPw:b4q1ozc) ([raw file](https://github.com/kube-hpc/hkube/blob/fcc43296981ed4bcfb59cf2b2773a277d6e5d642/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L39)):*
> ```JavaScript
>             if (this._groupActiveJobs[job.pipelineName] > 0) {
>                 this._groupActiveJobs[job.pipelineName] += job.updateRunning;
>                 delete job.updateRunning;
> ```

I think this method of `updateRunning` (1, -1) is too tricky



_Code quote:_
```JavaScript
delete job.updateRunning;
```
___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 110 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtI2tMt3crDSoX4uExz:-MtI2tMt3crDSoX4uEy-:b-dvr3uv) ([raw file](https://github.com/kube-hpc/hkube/blob/fcc43296981ed4bcfb59cf2b2773a277d6e5d642/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L110)):*
> ```JavaScript
>         const max = this._pipelines.find(p => p.name === job.pipelineName).options.concurrentPipelines.amount;
>         if (active >= max) {
>             job.updateRunning = -1;
> ```

again, is too tricky



_Code quote:_
```JavaScript
job.updateRunning
```

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1503)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 108 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtI7LpW7j4RVHICwrbW:-MtI7LpXBZePz-eeHog7:bvu42jb) ([raw file](https://github.com/kube-hpc/hkube/blob/fcc43296981ed4bcfb59cf2b2773a277d6e5d642/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L108)):*
> ```JavaScript
>             return true;
>         }
>         const max = this._pipelines.find(p => p.name === job.pipelineName).options.concurrentPipelines.amount;
> ```

what if `find` will return null?
(you have a check to see if the pipeline exists)

in a single data-structure you will do
```
const {active, max} = this._ds[name] || {}
```



_Code quote:_
```JavaScript
this._pipelines.find(p => p.name === job.pipelineName)
```

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1503)* status: 3 of 9 files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 14 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtI3Ehl056yzbaMHtTq:-MtIJr9R58HWFTkTVXAC:bic3ixm) ([raw file](https://github.com/kube-hpc/hkube/blob/fcc43296981ed4bcfb59cf2b2773a277d6e5d642/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L14)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Instead of passing the producer as a ref, you can pass a callback/event and when you call `_cancelExceededJob` just trigger it
</blockquote></details>

I prefer the dependency injection method. I don't like callbacks
___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 39 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtI4VxR3_LqMJp2wrPv:-MtIK-oD3BfQjWzTxQK2:b-4udsbc) ([raw file](https://github.com/kube-hpc/hkube/blob/fcc43296981ed4bcfb59cf2b2773a277d6e5d642/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L39)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I think this method of `updateRunning` (1, -1) is too tricky
</blockquote></details>

What do you suggest? two different flags for increment/decrement? use consts for increment/decrement
___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 110 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtI2tMt3crDSoX4uExz:-MtIKLkR7zN3WzHcNP0Z:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/fcc43296981ed4bcfb59cf2b2773a277d6e5d642/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L110)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

again, is too tricky
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1503)* status: 3 of 9 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 111 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtJKmVX2yQsWPyVaB1J:-MtJKmVX2yQsWPyVaB1K:b-cri08j) ([raw file](https://github.com/kube-hpc/hkube/blob/a345dcf5c717e88b7bed6263d968425fd2bb20e0/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L111)):*
> ```JavaScript
> 
>     _checkRunningJobs(job) {
>         const active = this._activeState[job.pipelineName]?.count;
> ```

you can make it shorter:
```
const { active,  max } = this._activeState[job.pipelineName] || {}
if (!active || !max) {
    return true;
}
```



_Code quote:_
```JavaScript
 const active = this._activeState[job.pipelineName]?.count;
```

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1503)* status: 3 of 9 files reviewed, 3 unresolved discussions (waiting on @NassiHarel)

___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 12 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtI3qHp0PRlg3kFjLDc:-MtXGqaG5_b9ls-M_Qet:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/fcc43296981ed4bcfb59cf2b2773a277d6e5d642/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L12)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I think that single data structure is better :-)
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 108 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtI7LpW7j4RVHICwrbW:-MtXGuIg8GYWAGR8hUO8:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/fcc43296981ed4bcfb59cf2b2773a277d6e5d642/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L108)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

what if `find` will return null?
(you have a check to see if the pipeline exists)

in a single data-structure you will do
```
const {active, max} = this._ds[name] || {}
```
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 111 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtJKmVX2yQsWPyVaB1J:-MtXGsYSAEWIyBFiszRr:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/a345dcf5c717e88b7bed6263d968425fd2bb20e0/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L111)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

you can make it shorter:
```
const { active,  max } = this._activeState[job.pipelineName] || {}
if (!active || !max) {
    return true;
}
```
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 4 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1503#-:-MtXLp288k5JNnpFMs99:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js, line 12 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1503#-MtXKclc9QAGP0Nf-ySn:-MtXKclc9QAGP0Nf-ySo:b-ll14kz) ([raw file](https://github.com/kube-hpc/hkube/blob/a345dcf5c717e88b7bed6263d968425fd2bb20e0/core/pipeline-driver-queue/lib/jobs/concurrencyHandler.js#L12)):*
> ```JavaScript
> class ConcurrencyHandler {
>     constructor(producer, options) {
>         this._activeState = {};
> ```

I would make this a data structure (in a separate file)
so instead of something like this:
```
this._activeState[p.name]?.count || 0;
```

I would do:
```
this._activeState.get(p.name)
this._activeState.getCount(p.name)
this._activeState.updateCount(p.name)
this._activeState.getMax(p.name)

```



_Code quote:_
```JavaScript
this._activeState
```

**Pull request merged**
