### PR TITLE
Complex descriptor unit test

### PR DESCRIPTION
**Pull request by awesomecakex**
kube-HPC/hkube#1729

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1766)

### CODE REVIEW

**Review by RonShvarz — CHANGES_REQUESTED** [review]
"should update algorithm that cannot be scheduled due to cpu" test brings the algorithm to a situation where it has insufficiant resources, and a complexResourceDescriptor should check for that, 
Also consider adding verification for the node name , when selector is applied for example - If you know in advance that a selector of type "gpu" will unselect all nodes without GPU, verify that the remaning node name is the one you have expected.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1766#-:-N_galg72kbcBXUIfNQ1:bl1fjfz)* status: all files reviewed, 1 unresolved discussion (waiting on @awesomecakex)

___
*[`core/task-executor/tests/reconcilerTests.js` line 1563 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1766#-N_g_H5cDLhAOsD3w5Dm:-N_g_H5cDLhAOsD3w5Dn:b-tsya48) ([raw file](https://github.com/kube-HPC/hkube/blob/ac0fbb9bce8ef2a97d0677b6456843d593021146/core/task-executor/tests/reconcilerTests.js#L1563)):*
> ```JavaScript
>             const algorithms = resources && resources[0] && resources[0].unScheduledAlgorithms;
>             expect(algorithms[algorithm.name].reason).to.eql('FailedScheduling');
>             expect(algorithms[algorithm.name].message).to.eql(`Maximum capacity exceeded cpu (1) mem (1) gpu (1)`);
> ```

Since there are exceeded capacity messages , also verify that the complexResourceDescriptor shows the over capacity for both cpu and memory.



_Code quote:_
```JavaScript
(`Maximum capacity exceeded cpu (1) mem (1) gpu (1)`);
```

**Comment by awesomecakex** [comment]
about node name it is checked in the code section you quoted from just a line after what you quoted where i check for the name node4

**Review by RonShvarz — CHANGES_REQUESTED** [review]
Ok

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1766#-:-N_gxd9uBN7kZndkVxoO:b32w1t)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @awesomecakex)

**Review by RonShvarz — CHANGES_REQUESTED** [review]
Once an ability has been tested overall i.e. ability to facilitate all nodes with missing cpu ( for example, this test will verify that the case of #ofLoops = max is working), there wont be a need to repeat the code in the noted spot "all nodes facilitated for gpu already tested, this code is fine as is.".

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1766#-:-N_hjdEoBjjbNOkqvunC:b-j8bfua)* status: all files reviewed, 5 unresolved discussions (waiting on @awesomecakex)

___
*[`core/task-executor/tests/reconcilerTests.js` line 1399 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1766#-N_hj3iu1NxDayOs7EsY:-N_hj3iu1NxDayOs7EsZ:b-660puy) ([raw file](https://github.com/kube-HPC/hkube/blob/b5247dfa209ff41efa990ab194ab27707a3e371b/core/task-executor/tests/reconcilerTests.js#L1399)):*
> ```JavaScript
>             expect(algorithms[algorithm.name].reason).to.eql('FailedScheduling');
>             expect(algorithms[algorithm.name].message).to.eql('Insufficient cpu (4)');
>             expect(algorithms[algorithm.name].complexResourceDescriptor.nodes[0].amountsMissing.cpu).to.eql('1.18');
> ```

In this case, if i am not mistaken, the message says there are 4 nodes found valid, and all of them have missing cpu.
There is benefit in seeing that the complexResourceDescriptor did indeed facilitate 4 nodes with 4 explicit missing CPU calculations.
___
*[`core/task-executor/tests/reconcilerTests.js` line 1426 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1766#-N_hjS6R1xtG8hWAK2W7:-N_hjS6R1xtG8hWAK2W8:bygurs6) ([raw file](https://github.com/kube-HPC/hkube/blob/b5247dfa209ff41efa990ab194ab27707a3e371b/core/task-executor/tests/reconcilerTests.js#L1426)):*
> ```JavaScript
>             expect(algorithms[algorithm.name].reason).to.eql('FailedScheduling');
>             expect(algorithms[algorithm.name].message).to.eql('Insufficient mem (4)');
>             expect(algorithms[algorithm.name].complexResourceDescriptor.nodes[0].amountsMissing.mem).to.eql('11929.60');
> ```

Same as for the CPU comment.
___
*[`core/task-executor/tests/reconcilerTests.js` line 1468 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1766#-N_hjYB4CsdOY2ty8lea:-N_hjYB4CsdOY2ty8leb:b-jbtov5) ([raw file](https://github.com/kube-HPC/hkube/blob/b5247dfa209ff41efa990ab194ab27707a3e371b/core/task-executor/tests/reconcilerTests.js#L1468)):*
> ```JavaScript
>             expect(algorithms[algorithm.name].reason).to.eql('FailedScheduling');
>             expect(algorithms[algorithm.name].message).to.eql('Insufficient gpu (4)');
>             expect(algorithms[algorithm.name].complexResourceDescriptor.nodes[0].amountsMissing.gpu).to.eql('3.00');
> ```

Same as the CPU comment
___
*[`core/task-executor/tests/reconcilerTests.js` line 1530 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1766#-N_hjzQX6FZRuVwAi85S:-N_hjzQX6FZRuVwAi85T:baeyaje) ([raw file](https://github.com/kube-HPC/hkube/blob/b5247dfa209ff41efa990ab194ab27707a3e371b/core/task-executor/tests/reconcilerTests.js#L1530)):*
> ```JavaScript
>             expect(algorithms[algorithm.name].reason).to.eql('FailedScheduling');
>             expect(algorithms[algorithm.name].message).to.eql('Maximum capacity exceeded gpu (4)');
>             expect(algorithms[algorithm.name].complexResourceDescriptor.nodes[0].amountsMissing.gpu).to.eql('7.00');
> ```

all nodes facilitated for gpu already tested, this code is fine as is.

**Review by awesomecakex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1766)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @RonShvarz)

___
*[`core/task-executor/tests/reconcilerTests.js` line 1563 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1766#-N_g_H5cDLhAOsD3w5Dm:-N_lv_P837KGalGQ6OZ0:bgk9s5f) ([raw file](https://github.com/kube-HPC/hkube/blob/ac0fbb9bce8ef2a97d0677b6456843d593021146/core/task-executor/tests/reconcilerTests.js#L1563)):*
<details><summary><i>Previously, RonShvarz (Ron Shvarzburd) wrote…</i></summary><blockquote>

Since there are exceeded capacity messages , also verify that the complexResourceDescriptor shows the over capacity for both cpu and memory.
</blockquote></details>

this is verified in previous test so there is no need to repeat in my opinion
___
*[`core/task-executor/tests/reconcilerTests.js` line 1426 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1766#-N_hjS6R1xtG8hWAK2W7:-N_luy0AEJ9Efa-WrDeY:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/b5247dfa209ff41efa990ab194ab27707a3e371b/core/task-executor/tests/reconcilerTests.js#L1426)):*
<details><summary><i>Previously, RonShvarz (Ron Shvarzburd) wrote…</i></summary><blockquote>

Same as for the CPU comment.
</blockquote></details>

Done.
___
*[`core/task-executor/tests/reconcilerTests.js` line 1530 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1766#-N_hjzQX6FZRuVwAi85S:-N_lvOjwENGrONT7Tt6B:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/b5247dfa209ff41efa990ab194ab27707a3e371b/core/task-executor/tests/reconcilerTests.js#L1530)):*
<details><summary><i>Previously, RonShvarz (Ron Shvarzburd) wrote…</i></summary><blockquote>

all nodes facilitated for gpu already tested, this code is fine as is.
</blockquote></details>

Done.

**Review by awesomecakex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1766)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @RonShvarz)

___
*[`core/task-executor/tests/reconcilerTests.js` line 1468 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1766#-N_hjYB4CsdOY2ty8lea:-N_lwfvHBDjG0F1n5R-e:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/b5247dfa209ff41efa990ab194ab27707a3e371b/core/task-executor/tests/reconcilerTests.js#L1468)):*
<details><summary><i>Previously, RonShvarz (Ron Shvarzburd) wrote…</i></summary><blockquote>

Same as the CPU comment
</blockquote></details>

Done.

**Review by awesomecakex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1766)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @RonShvarz)

___
*[`core/task-executor/tests/reconcilerTests.js` line 1399 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1766#-N_hj3iu1NxDayOs7EsY:-N_lwlnA6jgBUeXM3sH6:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/b5247dfa209ff41efa990ab194ab27707a3e371b/core/task-executor/tests/reconcilerTests.js#L1399)):*
<details><summary><i>Previously, RonShvarz (Ron Shvarzburd) wrote…</i></summary><blockquote>

In this case, if i am not mistaken, the message says there are 4 nodes found valid, and all of them have missing cpu.
There is benefit in seeing that the complexResourceDescriptor did indeed facilitate 4 nodes with 4 explicit missing CPU calculations.
</blockquote></details>

Done.

**Review by RonShvarz — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1766)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @awesomecakex)

**Pull request merged**
