### PR TITLE
Api server update stop api call

### PR DESCRIPTION
**Pull request by mkkCoder**
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1793)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1793)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @mkkCoder)

___
*[`core/api-server/api/rest-api/routes/v1/exec.js` line 59 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NdV6mZ37EpYCCc9b-aW:-NdV6mZ37EpYCCc9b-aX:b-22o0di) ([raw file](https://github.com/kube-HPC/hkube/blob/7a8d5b31f7055a39976003bcd34d8c4fadcd7af5/core/api-server/api/rest-api/routes/v1/exec.js#L59)):*
> ```JavaScript
>                 error: {
>                     code: 404,
>                     message: jobId ? `jobId ${jobId} Not Found` : 'No Jobs Found'
> ```

Message should include infromation about the pipeline and the starttime  in the query



_Code quote:_
```JavaScript
 message: jobId ? `jobId ${jobId} Not Found` : 'No Jobs Found'
```

**Review by mkkCoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1793)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`core/api-server/api/rest-api/routes/v1/exec.js` line 59 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NdV6mZ37EpYCCc9b-aW:-NdeV3ypC2sacnjjdY-d:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/7a8d5b31f7055a39976003bcd34d8c4fadcd7af5/core/api-server/api/rest-api/routes/v1/exec.js#L59)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Message should include infromation about the pipeline and the starttime  in the query
</blockquote></details>

Done.

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1793)* status: all files reviewed, 7 unresolved discussions (waiting on @mkkCoder)

___
*[`core/api-server/api/rest-api/routes/v1/exec.js` line 54 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCTDGMAJw41XLFylXx:-NeCTDGMAJw41XLFylXy:b-cigzxz) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/api/rest-api/routes/v1/exec.js#L54)):*
> ```JavaScript
>             search.query.pipelineName = jobId;
>         }
>         const searchResponse = await Execution.search({ ...search, limit: 100 });
> ```

We don't need to limit the search result



_Code quote:_
```JavaScript
limit: 100 
```
___
*[`core/api-server/api/rest-api/routes/v1/exec.js` line 61 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCTYb32mTDrqVqTEJ9:-NeCTYb32mTDrqVqTEJA:bxws361) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/api/rest-api/routes/v1/exec.js#L61)):*
> ```JavaScript
>             }
>             else if (pipelineName && !datesRange) {
>                 errormsg = `pipelineName ${pipelineName} jobs Not Found`;
> ```

No running jobs of $(pipelineName) to stop.



_Code quote:_
```JavaScript
pipelineName ${pipelineName} jobs Not Found`
```
___
*[`core/api-server/api/rest-api/routes/v1/exec.js` line 64 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCTwlv0MfG8LQPl8jT:-NeCTwlv0MfG8LQPl8jU:b-z9z4hd) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/api/rest-api/routes/v1/exec.js#L64)):*
> ```JavaScript
>             }
>             else if (pipelineName) {
>                 errormsg = `pipelineName ${pipelineName} jobs Not Found between ${datesRange.from} to ${datesRange.to}`;
> ```

No running jobs of $(pipelineName) which started between ${datesRange.from} and ${datesRange.to)  to stop.



_Code quote:_
```JavaScript
pipelineName ${pipelineName} jobs Not Found between ${datesRange.from} to ${datesRange.to
```
___
*[`core/api-server/lib/service/execution.js` line 283 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCUsS0-hmLNOEbDbBd:-NeCUsS0-hmLNOEbDbBe:bso31er) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/lib/service/execution.js#L283)):*
> ```JavaScript
>         }
>         else if (options.job) {
>             ({ jobId } = options.job || {});
> ```

jobId is empty, its covered in the conditon before:  if(jobid), so its not needed here.



_Code quote:_
```JavaScript
{ jobId } = options.job 
```
___
*[`core/api-server/lib/service/execution.js` line 286 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCdMQTDQErLKJKL5mu:-NeCdMQTDQErLKJKL5mv:bxt82xc) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/lib/service/execution.js#L286)):*
> ```JavaScript
>             ({ status, pipeline } = options.job || {});
>         }
>         const statusObject = { jobId, status: pipelineStatuses.STOPPED, reason, level: levels.INFO.name };
> ```

no need for jobId, its empty



_Code quote:_
```JavaScript
 jobId,
```
___
*[`core/api-server/lib/service/execution.js` line 287 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCdReNDoVJYaME1h4E:-NeCdReNDoVJYaME1h4F:bkljk6o) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/lib/service/execution.js#L287)):*
> ```JavaScript
>         }
>         const statusObject = { jobId, status: pipelineStatuses.STOPPED, reason, level: levels.INFO.name };
>         const resultObject = { jobId, startTime: pipeline.startTime, pipeline: pipeline.name, reason, status: pipelineStatuses.STOPPED };
> ```

no need for jobid, its empty



_Code quote:_
```JavaScript
jobId,
```
___
*[`core/api-server/tests/exec-stop.js` line 46 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCdxQH4IluV0PWe7D-:-NeCdxQH4IluV0PWe7D0:b4he8ey) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/tests/exec-stop.js#L46)):*
> ```JavaScript
>             expect(response.body.error).to.not.exist;
>             expect(response.body.message).to.equal('OK');
>         });
> ```

Add test to get not found because no jobs in time frame of because no jobs of certaion pipeline in time frame or because no jobs of certain pipeline found or because no jobs of certaion job in certaion time frame exist.

**Review by golanha — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1793)* status: all files reviewed, 7 unresolved discussions (waiting on @mkkCoder)

**Review by golanha — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1793#-:-NeDBuXM1hehsjBWNcTv:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @mkkCoder)

**Review by mkkCoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1793)* status: 9 of 10 files reviewed, 7 unresolved discussions (waiting on @golanha)

___
*[`core/api-server/api/rest-api/routes/v1/exec.js` line 54 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCTDGMAJw41XLFylXx:-NeD9Y7A24JAh4ncs0ed:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/api/rest-api/routes/v1/exec.js#L54)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

We don't need to limit the search result
</blockquote></details>

Done.
___
*[`core/api-server/api/rest-api/routes/v1/exec.js` line 61 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCTYb32mTDrqVqTEJ9:-NeD9jSP5NGpGQ74tiT8:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/api/rest-api/routes/v1/exec.js#L61)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

No running jobs of $(pipelineName) to stop.
</blockquote></details>

Done.
___
*[`core/api-server/api/rest-api/routes/v1/exec.js` line 64 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCTwlv0MfG8LQPl8jT:-NeD9fwe6tjotF7kCceh:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/api/rest-api/routes/v1/exec.js#L64)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

No running jobs of $(pipelineName) which started between ${datesRange.from} and ${datesRange.to)  to stop.
</blockquote></details>

Done.
___
*[`core/api-server/lib/service/execution.js` line 283 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCUsS0-hmLNOEbDbBd:-NeD9nKVECz2r2i1BX9_:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/lib/service/execution.js#L283)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

jobId is empty, its covered in the conditon before:  if(jobid), so its not needed here.
</blockquote></details>

Done.
___
*[`core/api-server/lib/service/execution.js` line 286 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCdMQTDQErLKJKL5mu:-NeD9nnGAOp1lUu954mU:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/lib/service/execution.js#L286)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

no need for jobId, its empty
</blockquote></details>

Done.
___
*[`core/api-server/lib/service/execution.js` line 287 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCdReNDoVJYaME1h4E:-NeD9oW57H2n3i6JacLB:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/lib/service/execution.js#L287)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

no need for jobid, its empty
</blockquote></details>

Done.
___
*[`core/api-server/tests/exec-stop.js` line 46 at r3](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeCdxQH4IluV0PWe7D-:-NeHM1uhDzskcpZsep8R:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/0c54144ada42e31cad0057041a7e282e32a235bc/core/api-server/tests/exec-stop.js#L46)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Add test to get not found because no jobs in time frame of because no jobs of certaion pipeline in time frame or because no jobs of certain pipeline found or because no jobs of certaion job in certaion time frame exist.
</blockquote></details>

Done.

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1793)* status: 9 of 10 files reviewed, 9 unresolved discussions (waiting on @mkkCoder)

___
*[`core/api-server/tests/exec-stop.js` line 77 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeHyv728JYFwNuNk1Fj:-NeHyv728JYFwNuNk1Fk:b-vkugvh) ([raw file](https://github.com/kube-HPC/hkube/blob/9532eaa0e715cfb3b1044dd4f00c490ec2026596/core/api-server/tests/exec-stop.js#L77)):*
> ```JavaScript
>             expect(response.body.message).to.equal('OK');
>         });
>         it('should throw a "not found" error when no jobs are found within a time frame', async () => {
> ```

This one is suppose to fail, the timeframe is fine and should have a job to stop.



_Code quote:_
```JavaScript
it('should throw a "not found" error when no jobs are found within a time frame', async () 
```
___
*[`core/api-server/tests/exec-stop.js` line 142 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1793#-NeHs47uEaciFm0U4tsL:-NeHs47uEaciFm0U4tsM:bc6hbhu) ([raw file](https://github.com/kube-HPC/hkube/blob/9532eaa0e715cfb3b1044dd4f00c490ec2026596/core/api-server/tests/exec-stop.js#L142)):*
> ```JavaScript
>             expect(responseTimeFrame.body.error.message).to.equal(`No running jobs of ${optionsTimeFrame.body.pipelineName} which started between ${optionsTimeFrame.body.startTime.from} to ${optionsTimeFrame.body.startTime.to} to stop`);
>         });
>         it.only('should throw a "not found" error when no jobs of a certain pipeline are found', async () => {
> ```

remove the only



_Code quote:_
```JavaScript
only
```

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1793)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkkCoder)

**Review by golanha — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1793)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkkCoder)

**Pull request merged**
