### PR TITLE
test get pod

### PR DESCRIPTION
**Pull request by zivglik**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1647)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1647)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @zivglik)

___
*[`core/api-server/api/task-logs/consts.js` line 38 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1647#-NLQ3dTO0AndCzJMWTDP:-NLQ3dTO0AndCzJMWTDQ:bbj9db5) ([raw file](https://github.com/kube-hpc/hkube/blob/b06510d131e3482ab6773dcc86b481552165ccf0/core/api-server/api/task-logs/consts.js#L38)):*
> ```JavaScript
> 
> };
> ```

Move to consts module
___
*[`core/api-server/api/task-logs/logs.js` line 84 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1647#-NLQ3n554M9ywO31QiHc:-NLQ3n554M9ywO31QiHd:b-l6mwxj) ([raw file](https://github.com/kube-hpc/hkube/blob/b06510d131e3482ab6773dcc86b481552165ccf0/core/api-server/api/task-logs/logs.js#L84)):*
> ```JavaScript
>                         level: 'info',
>                         timestamp: Date.now()
>                     }];
> ```

remove



_Code quote:_
```JavaScript
                    logsData.logs = [{
                        message: [`image ${currentAlgorunner.image} not exist`],
                        level: 'info',
                        timestamp: Date.now()
                    }];
```

**Review by zivglik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1647)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[`core/api-server/api/task-logs/consts.js` line 38 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1647#-NLQ3dTO0AndCzJMWTDP:-NLUNt8bCD_V3E6ektdt:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b06510d131e3482ab6773dcc86b481552165ccf0/core/api-server/api/task-logs/consts.js#L38)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Move to consts module
</blockquote></details>

Done.



_Code quote:_
```JavaScript
NOT_EXIST: 'NOT_EXIST',
```
___
*[`core/api-server/api/task-logs/consts.js` line 39 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1647#-NLUAl8kDQlpZkGCV2L6:-NLUAl8kDQlpZkGCV2L7:bkuwfuv) ([raw file](https://github.com/kube-hpc/hkube/blob/b06510d131e3482ab6773dcc86b481552165ccf0/core/api-server/api/task-logs/consts.js#L39)):*
>  consts module
___
*[`core/api-server/api/task-logs/logs.js` line 84 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1647#-NLQ3n554M9ywO31QiHc:-NLUAhQIC1IkGeIzPp6r:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b06510d131e3482ab6773dcc86b481552165ccf0/core/api-server/api/task-logs/logs.js#L84)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1647)* status: all files reviewed, 1 unresolved discussion

**Pull request merged**
