### PR TITLE
Change node status after stopped pipeline

### PR DESCRIPTION
**Pull request by RonShvarz**
Mark nodes as stopped

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1832)

### CODE REVIEW

**Comment by RonShvarz** [comment]
kube-HPC/hkube#1827

**Review by golanha — APPROVED** [review]
> Reviewed 2 of 9 files at r6, 7 of 9 files at r7, 2 of 2 files at r8, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1832)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RonShvarz)

**Pull request merged**
