### PR TITLE
add pipeline type for caching debug

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1313)

### CODE REVIEW

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1313#-:-MdHPekID5JI0CRdw5uu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/api-server/tests/exec-raw.js, line 45 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1313#-MdHQDkiA3WlGiHSA0Lo:-MdHQDkiA3WlGiHSA0Lp:bswglaf) ([raw file](https://github.com/kube-hpc/hkube/blob/4b6e5fab6a89939a94f6d59efa33a870d6cc1738/core/api-server/tests/exec-raw.js#L45)):*
> ```
> onst {body: job}=await g
> ```
Please do a basic format.

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1313)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/tests/exec-raw.js, line 45 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1313#-MdHQDkiA3WlGiHSA0Lo:-MdHSPHFA2-yydxFAb3_:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/4b6e5fab6a89939a94f6d59efa33a870d6cc1738/core/api-server/tests/exec-raw.js#L45)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> onst {body: job}=await g
> ```
Please do a basic format.
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1313)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
