### PR TITLE
Store pipelines update

### PR DESCRIPTION
**Pull request by mkkCoder**
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1804)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1804)* status: all files reviewed, 1 unresolved discussion (waiting on @mkkCoder)

___
*[`core/api-server/tests/pipelines-store.js` line 510 at r4](https://reviewable.io/reviews/kube-HPC/hkube/1804#-Nn-35mh9ZkiQNIP2ssy:-Nn-35mi2d5eCtrzt5Jv:bk8btcp) ([raw file](https://github.com/kube-HPC/hkube/blob/5af98be6f1a1bbb6fc3cb8f35360041a38771b1b/core/api-server/tests/pipelines-store.js#L510)):*
> ```JavaScript
>             expect(response.body[1]).to.have.property('name');
>         });
>         it('should secceed creating an array containing a pipeline with a 400 Bad Request status and error message for invalid data', async () => {
> ```

succeed
(check all occurrences)



_Code quote:_
```JavaScript
secceed 
```

**Review by mkkCoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1804)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`core/api-server/tests/pipelines-store.js` line 510 at r4](https://reviewable.io/reviews/kube-HPC/hkube/1804#-Nn-35mh9ZkiQNIP2ssy:-Nn-7qut686EXCA3yUdW:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/5af98be6f1a1bbb6fc3cb8f35360041a38771b1b/core/api-server/tests/pipelines-store.js#L510)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

succeed
(check all occurrences)
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1804)* status: all files reviewed, 1 unresolved discussion (waiting on @mkkCoder)

**Review by golanha — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1804)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkkCoder)

**Pull request merged**
