### PR TITLE
Jupyter

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1460)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 24 of 44 files at r1, 3 of 5 files at r2, 5 of 7 files at r3, 9 of 14 files at r4, 2 of 3 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/algorithm-operator/lib/reconcile/devenv.js, line 26 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1460#-Mp5btTs15hHC15KN4hu:-Mp5btTs15hHC15KN4hv:b26dk3e) ([raw file](https://github.com/kube-hpc/hkube/blob/4f03c33d6120dd455b1f4080e4bb51085e5ece2d/core/algorithm-operator/lib/reconcile/devenv.js#L26)):*
> ```
> for (const type of Object.values(devenvTypes))
> ```

Do u actually need to do `for of` 8 times?

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1460)* status: 28 of 55 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/algorithm-operator/lib/reconcile/devenv.js, line 26 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1460#-Mp5btTs15hHC15KN4hu:-MpFs2wI6ZfjaaGIX5SD:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/4f03c33d6120dd455b1f4080e4bb51085e5ece2d/core/algorithm-operator/lib/reconcile/devenv.js#L26)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> for (const type of Object.values(devenvTypes))
> ```

Do u actually need to do `for of` 8 times?
</blockquote></details>

Done.

**Review by NassiHarel — DISMISSED** [review]
:lgtm:

> Reviewed 21 of 24 files at r8, 3 of 3 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1460#-:-MpFucALBSvYIw-0YyS5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Review by NassiHarel — APPROVED** [review]
> Reviewed 3 of 5 files at r11, 2 of 2 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1460)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request closed without merging**
