### PR TITLE
support storageInput for code-api

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1193)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1193)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/worker/lib/code-api/algorithm-execution/algorithm-execution.js, line 186 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1193#-MW-QDXS9enkABUD3tHv:-MW-QDXS9enkABUD3tHw:bthnw6v) ([raw file](https://github.com/kube-hpc/hkube/blob/5aa694245d82e67b2ba2932ab714d5125062d354/core/worker/lib/code-api/algorithm-execution/algorithm-execution.js#L186)):*
> ```
> const { storageInput } = data;
> ```

This is strange, it looks like I'm expecting this `storageInput` to come from the algorithm, but I never implemented this, or it was and then deleted...

anyway, you can also move this destrction below to:
`const { algorithmName, input, includeResult, storageInput, storage = {} } = data;`

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1193)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/worker/lib/code-api/algorithm-execution/algorithm-execution.js, line 186 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1193#-MW-QDXS9enkABUD3tHv:-MW-T07P6MK6j7WWcu0e:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/5aa694245d82e67b2ba2932ab714d5125062d354/core/worker/lib/code-api/algorithm-execution/algorithm-execution.js#L186)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const { storageInput } = data;
> ```

This is strange, it looks like I'm expecting this `storageInput` to come from the algorithm, but I never implemented this, or it was and then deleted...

anyway, you can also move this destrction below to:
`const { algorithmName, input, includeResult, storageInput, storage = {} } = data;`
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1193#-:-MW-VbSv-GHbXrfo0i3W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
