### PR TITLE
Tasts attachment to node

### PR DESCRIPTION
**Pull request by RonShvarz**
kube-HPC/hkube#1831

Handle stateless tasks attachment to jobs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1839)

### CODE REVIEW

**Review by golanha — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1839)* status: 2 of 3 files reviewed, all discussions resolved

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RonShvarz)

**Comment by RonShvarz** [comment]
kube-HPC/hkube#1827

**Pull request merged**
