### PR TITLE
healthchecks-v1.3

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/api-server/lib/state/state-manager.js, line 47 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ7tnT726rw7dKdvuhI:-MZ7tnT726rw7dKdvuhJ:b-3u6c6j) ([raw file](https://github.com/kube-hpc/hkube/blob/40e32e0c1a61883dcf92c3b6b3d687ef51e803d4/core/api-server/lib/state/state-manager.js#L47)):*
> ```
> result.status === States.COMPLETED
> ```

Only completed status?
Do you need to check the status?

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/lib/state/state-manager.js, line 47 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ7tnT726rw7dKdvuhI:-MZ80ZAM4rQOpuYx9WL3:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/40e32e0c1a61883dcf92c3b6b3d687ef51e803d4/core/api-server/lib/state/state-manager.js#L47)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> result.status === States.COMPLETED
> ```

Only completed status?
Do you need to check the status?

</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/lib/webhook/States.js, line 15 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ82lywCPEAjm8LRXXF:-MZ82lywCPEAjm8LRXXG:b9xf7af) ([raw file](https://github.com/kube-hpc/hkube/blob/95771dd26ca7187ac4697dd8532d01dd2a5b71d5/core/api-server/lib/webhook/States.js#L15)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> const CompletedState = [pipelineStatuses.COMPLETED, pipelineStatuses.FAILED, pipelineStatuses.STOPPED];
> const isCompletedState = (state) => {
>     return CompletedState.includes(state);
> };
> ```
</details>


Any usage?
___
*[core/api-server/tests/webhooks.js, line 214 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ82sh0BRy0O4smBhZ3:-MZ82sh0BRy0O4smBhZ4:bx5bms4) ([raw file](https://github.com/kube-hpc/hkube/blob/95771dd26ca7187ac4697dd8532d01dd2a5b71d5/core/api-server/tests/webhooks.js#L214)):*
> ```
> ············
> ```
Too many empty lines.....

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/lib/webhook/States.js, line 15 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ82lywCPEAjm8LRXXF:-MZ88ely1ZL_BHNghZBv:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/95771dd26ca7187ac4697dd8532d01dd2a5b71d5/core/api-server/lib/webhook/States.js#L15)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const CompletedState = [pipelineStatuses.COMPLETED, pipelineStatuses.FAILED, pipelineStatuses.STOPPED];
> const isCompletedState = (state) => {
>     return CompletedState.includes(state);
> };
> ```

Any usage?
</blockquote></details>

Done.
___
*[core/api-server/tests/webhooks.js, line 214 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ82sh0BRy0O4smBhZ3:-MZ88g228hQDn_ft3Ssq:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/95771dd26ca7187ac4697dd8532d01dd2a5b71d5/core/api-server/tests/webhooks.js#L214)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> ············
> ```
Too many empty lines.....
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 3 of 5 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/lib/state/state-manager.js, line 62 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ8F3M37W6TVcXvzoUZ:-MZ8F3M37W6TVcXvzoU_:b-chtl6z) ([raw file](https://github.com/kube-hpc/hkube/blob/4f2628622a51a6ec6410b6d35fda716b5ad5732c/core/api-server/lib/state/state-manager.js#L62)):*
> ```
> log.throttle
> ```
You don't have throttle in logger config

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/tests/webhooks.js, line 203 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ8F9Cn1o8Iv9hP15_n:-MZ8F9Cn1o8Iv9hP15_o:b-maj9ev) ([raw file](https://github.com/kube-hpc/hkube/blob/4f2628622a51a6ec6410b6d35fda716b5ad5732c/core/api-server/tests/webhooks.js#L203)):*
> ```
> ····
> ```
Still tabs

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/tests/webhooks.js, line 177 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ8HozP9Kceg6Z9NfoA:-MZ8HozP9Kceg6Z9NfoB:b-kwpxmb) ([raw file](https://github.com/kube-hpc/hkube/blob/4f2628622a51a6ec6410b6d35fda716b5ad5732c/core/api-server/tests/webhooks.js#L177)):*
> ```JavaScript
>             expect(response2.body).to.have.property('pipelineStatus');
>             expect(response2.body).to.have.property('responseStatus');
>         });
> ```

Why we can't see the tests phase in the "checks tab"?

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239)* status: 9 of 12 files reviewed, 5 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/lib/state/state-manager.js, line 62 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ8F3M37W6TVcXvzoUZ:-MZ8IvaOChppiuVOlKh9:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/4f2628622a51a6ec6410b6d35fda716b5ad5732c/core/api-server/lib/state/state-manager.js#L62)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> log.throttle
> ```
You don't have throttle in logger config
</blockquote></details>

Done.
___
*[core/api-server/tests/webhooks.js, line 177 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ8HozP9Kceg6Z9NfoA:-MZ8J5-CBpyXnFpcyZ5d:b4c475z) ([raw file](https://github.com/kube-hpc/hkube/blob/4f2628622a51a6ec6410b6d35fda716b5ad5732c/core/api-server/tests/webhooks.js#L177)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Why we can't see the tests phase in the "checks tab"?
</blockquote></details>

because in this branch it was still in Travis-ci
___
*[core/api-server/tests/webhooks.js, line 203 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ8F9Cn1o8Iv9hP15_n:-MZ8IwyFEfW2tFutY2Lf:b-aiyxqf) ([raw file](https://github.com/kube-hpc/hkube/blob/4f2628622a51a6ec6410b6d35fda716b5ad5732c/core/api-server/tests/webhooks.js#L203)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> ····
> ```
Still tabs
</blockquote></details>

Third time a charm :-)

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239)* status: 9 of 12 files reviewed, 5 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/tests/webhooks.js, line 177 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ8HozP9Kceg6Z9NfoA:-MZ8JCd222fLTVRhwHYA:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/4f2628622a51a6ec6410b6d35fda716b5ad5732c/core/api-server/tests/webhooks.js#L177)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

because in this branch it was still in Travis-ci
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1239#-:-MZ8KwJm2y1vn3vnwWVx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/api-server/tests/webhooks.js, line 197 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1239#-MZ8Kl5V9eY__Fc1LWhy:-MZ8Kl5V9eY__Fc1LWhz:bgwpnyj) ([raw file](https://github.com/kube-hpc/hkube/blob/06ba4bd1c8f01fd1eaf7dbfbed8411ad1abd61a2/core/api-server/tests/webhooks.js#L197)):*
> ```
> ····
> ```

one more to go...

**Pull request merged**
