### PR TITLE
Hkube gc

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1287)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 86 of 96 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, 9 of 34 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1287)* status: 73 of 98 files reviewed, 7 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/hkube-gc/bootstrap.js, line 30 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfYXPPELsKgJeDhqGk:-MbfYXPPELsKgJeDhqGl:bi3x923) ([raw file](https://github.com/kube-hpc/hkube/blob/d71f62031c2c97764f2ae7b4629b7069cf45e8db/core/hkube-gc/bootstrap.js#L30)):*
> ```JavaScript
>             await cleanerManager.init(config);
>             await Promise.all(modules.map(m => m.init(config)));
>             // await healthchecks.initAndStart(main.healthchecks, () => runner.checkHealth(main.healthchecks.maxDiff), main.serviceName);
> ```

need to think how to add the healthchecks back
at least check that each of the cronjobs that started also finished in a reasonable time
___
*[core/hkube-gc/lib/cleaners/storage/indices-cleaner.js, line 8 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfhA-n-r-IRWAbwmSG:-MbfhA-n-r-IRWAbwmSH:bbaoxjx) ([raw file](https://github.com/kube-hpc/hkube/blob/d71f62031c2c97764f2ae7b4629b7069cf45e8db/core/hkube-gc/lib/cleaners/storage/indices-cleaner.js#L8)):*
> ```JavaScript
> class IndicesCleaner extends BaseCleaner {
>     async getJobsToDelete({ indices, maxAgeResults }) {
>         return super.getJobsToDelete({ indices, maxAge: maxAgeResults });
> ```

why `maxAgeResults` in `IndicesCleaner` and not `ResultsCleaner`?
___
*[core/hkube-gc/lib/cleaners/storage/promise-wrapper.js, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfeuzuCeDzMAzShic_:-MbfeuzuCeDzMAzShica:b-pmdsbf) ([raw file](https://github.com/kube-hpc/hkube/blob/d71f62031c2c97764f2ae7b4629b7069cf45e8db/core/hkube-gc/lib/cleaners/storage/promise-wrapper.js#L1)):*
> ```JavaScript
> const promiseWrapper = (func) => {
> ```

why not use `Promise.allSettled` instead?
___
*[core/hkube-gc/lib/core/kind-cleaner.js, line 4 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfiC2GDC618n2643vx:-MbfiC2GDC618n2643vy:b7eyhna) ([raw file](https://github.com/kube-hpc/hkube/blob/940bf05c1c0a25e87ec79f5ea23df06c9ea5c5de/core/hkube-gc/lib/core/kind-cleaner.js#L4)):*
> ```JavaScript
> const storeManager = require('../helpers/store-manager');
> 
> class Cleaner {
> ```

Isn't it better to give each class its own name?
___
*[core/hkube-gc/lib/cleaner-manager.js, line 14 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfbwG350lZTA7c-Ozu:-MbfbwG350lZTA7c-Ozv:b-y65ytv) ([raw file](https://github.com/kube-hpc/hkube/blob/d71f62031c2c97764f2ae7b4629b7069cf45e8db/core/hkube-gc/lib/cleaner-manager.js#L14)):*
> ```JavaScript
>         cleaners.forEach(name => {
>             const config = options.cleanerSettings[name];
>             if (config.enabled) {
> ```

Write to log if not enabled, so we can know why it didn't run
___
*[core/hkube-gc/lib/cleaner-manager.js, line 17 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfcxfuC8EnaAQWnATK:-Mbfcxfv1Jt7MrCsitk-:b2b0o3g) ([raw file](https://github.com/kube-hpc/hkube/blob/d71f62031c2c97764f2ae7b4629b7069cf45e8db/core/hkube-gc/lib/cleaner-manager.js#L17)):*
> ```JavaScript
>                 const Cleaner = require(`../${CLEANERS_PATH}/${name}`); // eslint-disable-line
>                 const cleaner = new Cleaner({ config, name });
>                 cleaner.init({ cleanMethod: (...args) => cleaner.clean(...args) });
> ```

Why pass the cleanMethod, and not call the overloaded method in each cleaner
___
*[core/hkube-gc/lib/core/cleaner-manager.js, line 30 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1287#-Mbfi5ow4cUwU43EXghV:-Mbfi5ow4cUwU43EXghW:b-8pqbqu) ([raw file](https://github.com/kube-hpc/hkube/blob/940bf05c1c0a25e87ec79f5ea23df06c9ea5c5de/core/hkube-gc/lib/core/cleaner-manager.js#L30)):*
> ```JavaScript
>     }
> 
>     _cronFormat(cron) {
> ```

put this in `base-cleaner` and call it after the init

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1287)* status: 63 of 99 files reviewed, 7 unresolved discussions (waiting on @yehiyam)

___
*[core/hkube-gc/bootstrap.js, line 30 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfYXPPELsKgJeDhqGk:-Mbjs0PnAechE0bO4uoQ:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/d71f62031c2c97764f2ae7b4629b7069cf45e8db/core/hkube-gc/bootstrap.js#L30)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

need to think how to add the healthchecks back
at least check that each of the cronjobs that started also finished in a reasonable time
</blockquote></details>

Done.
___
*[core/hkube-gc/lib/cleaners/storage/indices-cleaner.js, line 8 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfhA-n-r-IRWAbwmSG:-Mbk0ZGg1Pm6TuXShVe0:b-xq5iyq) ([raw file](https://github.com/kube-hpc/hkube/blob/d71f62031c2c97764f2ae7b4629b7069cf45e8db/core/hkube-gc/lib/cleaners/storage/indices-cleaner.js#L8)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why `maxAgeResults` in `IndicesCleaner` and not `ResultsCleaner`?
</blockquote></details>

This function is redundant.
___
*[core/hkube-gc/lib/cleaners/storage/promise-wrapper.js, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfeuzuCeDzMAzShic_:-Mbk1IQyAoTlRXu3DOT-:bu4wfx1) ([raw file](https://github.com/kube-hpc/hkube/blob/d71f62031c2c97764f2ae7b4629b7069cf45e8db/core/hkube-gc/lib/cleaners/storage/promise-wrapper.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why not use `Promise.allSettled` instead?
</blockquote></details>

You are right, This is an old copy-paste
___
*[core/hkube-gc/lib/core/kind-cleaner.js, line 4 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfiC2GDC618n2643vx:-Mbkq42G8qSrY1wRz3Sx:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/940bf05c1c0a25e87ec79f5ea23df06c9ea5c5de/core/hkube-gc/lib/core/kind-cleaner.js#L4)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Isn't it better to give each class its own name?
</blockquote></details>

Done.
___
*[core/hkube-gc/lib/cleaner-manager.js, line 14 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfbwG350lZTA7c-Ozu:-Mbk1c280E9KLfe214I2:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/d71f62031c2c97764f2ae7b4629b7069cf45e8db/core/hkube-gc/lib/cleaner-manager.js#L14)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Write to log if not enabled, so we can know why it didn't run
</blockquote></details>

Done.
___
*[core/hkube-gc/lib/cleaner-manager.js, line 17 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbfcxfuC8EnaAQWnATK:-Mbk1Zu5DHJd7yYRJtsR:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/d71f62031c2c97764f2ae7b4629b7069cf45e8db/core/hkube-gc/lib/cleaner-manager.js#L17)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Why pass the cleanMethod, and not call the overloaded method in each cleaner
</blockquote></details>

Done.
___
*[core/hkube-gc/lib/core/cleaner-manager.js, line 30 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1287#-Mbfi5ow4cUwU43EXghV:-Mbkkm0AAsic-_PI3Lrp:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/940bf05c1c0a25e87ec79f5ea23df06c9ea5c5de/core/hkube-gc/lib/core/cleaner-manager.js#L30)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

put this in `base-cleaner` and call it after the init
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 34 files at r4, 13 of 27 files at r5, 99 of 99 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1287)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[.github/labeler.yml, line 30 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbpxpuRBEgBJ2WcnbSy:-MbpxpuRBEgBJ2WcnbSz:bwq0dsz) ([raw file](https://github.com/kube-hpc/hkube/blob/c91a6f1345f2829ce512b9c9f5bdd779f57e8bf8/.github/labeler.yml#L30)):*
> ```
> gc-service
> ```
You need to rename the folder also
___
*[core/hkube-gc/config/main/config.base.js, line 18 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbpyHum3T65IdZtwbat:-MbpyHum3T65IdZtwbau:b65ny8z) ([raw file](https://github.com/kube-hpc/hkube/blob/c91a6f1345f2829ce512b9c9f5bdd779f57e8bf8/core/hkube-gc/config/main/config.base.js#L18)):*
> ```JavaScript
>     prefix: 'api',
>     poweredBy: 'HKube GC',
>     bodySizeLimit: process.env.BODY_SIZE_LIMIT || '2000mb'
> ```

2GB? isn't it excessive?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1287)* status: 102 of 103 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[.github/labeler.yml, line 30 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbpxpuRBEgBJ2WcnbSy:-Mc3gu_E5oV8zQyHK7Zb:b5ot515) ([raw file](https://github.com/kube-hpc/hkube/blob/c91a6f1345f2829ce512b9c9f5bdd779f57e8bf8/.github/labeler.yml#L30)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> gc-service
> ```
You need to rename the folder also
</blockquote></details>

Where? I already changed it
___
*[core/hkube-gc/config/main/config.base.js, line 18 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1287#-MbpyHum3T65IdZtwbat:-Mc3gz4j886lPlXXpqGL:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/c91a6f1345f2829ce512b9c9f5bdd779f57e8bf8/core/hkube-gc/config/main/config.base.js#L18)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

2GB? isn't it excessive? 
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1287#-:-Mc3hvrM1Cb7Z8_HMorJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Pull request merged**
