### PR TITLE
add debugOverride

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1321)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1321)* status: all files reviewed, 4 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/lib/service/debug.js, line 50 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1321#-Me59DKA1pZPvw4g2CPy:-Me59DKA1pZPvw4g2CPz:b-ye7ais) ([raw file](https://github.com/kube-hpc/hkube/blob/5e2d1ad3c21d2a4454435fc2731b65802b697416/core/api-server/lib/service/debug.js#L50)):*
> ```
> url: debugUrl
> ```
I think this is redundant
___
*[core/api-server/lib/service/debug.js, line 64 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1321#-Me5Crm28N3bTdDGDe9M:-Me5Crm28N3bTdDGDe9N:b-c8b0s0) ([raw file](https://github.com/kube-hpc/hkube/blob/5e2d1ad3c21d2a4454435fc2731b65802b697416/core/api-server/lib/service/debug.js#L64)):*
> ```JavaScript
>         await Promise.all(debugAlgorithms.map(a => stateManager.updateAlgorithm(a)));
>     }
> ```

Add this test

```
it('ooopppssss, I throw unhandledRejection', async () => {
            const options = {
                uri: restPath,
                body: {
                    name: 'exec_raw',
                    nodes: [
                        {
                            nodeName: 'node',
                            algorithmName: 'green-alg',
                            input: []
                        }
                    ],
                    options: {
                        debugOverride: [
                            'node'
                        ]
                    }
                }
            };
            const res = await request(options);
        });
```
___
*[core/api-server/tests/exec-stored.js, line 18 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1321#-Me58EWE6qmVIRdLuvNM:-Me58EWE6qmVIRdLuvNN:b-3a388s) ([raw file](https://github.com/kube-hpc/hkube/blob/5e2d1ad3c21d2a4454435fc2731b65802b697416/core/api-server/tests/exec-stored.js#L18)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         before(async () => {
>             restPath = `${restUrl}/exec/stored`;
>             await stateManager.deleteAlgorithm({ kind: nodeKind.Debug})
>   });
> ```
</details>


there is strange formatting in this file
___
*[core/openapi-spec/package.json, line 10 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1321#-Me570t_CE8HBZ31__SQ:-Me570t_CE8HBZ31__SR:bh3xycr) ([raw file](https://github.com/kube-hpc/hkube/blob/5e2d1ad3c21d2a4454435fc2731b65802b697416/core/openapi-spec/package.json#L10)):*
> ```
>       "build-swagger": "node ./swagger-builder.js && echo ../api-server/api/rest-api ../gc-service/api/rest-api ../datasources-service/api/rest-api | xargs -n 1 cp swagger.json",
> ```

Do we want to always change the api-server, gc-service, and ds-service and initiate build to all of them?

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1321)* status: all files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/lib/service/debug.js, line 50 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1321#-Me59DKA1pZPvw4g2CPy:-Me5EzQr32kSBLcsPbuO:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/5e2d1ad3c21d2a4454435fc2731b65802b697416/core/api-server/lib/service/debug.js#L50)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> url: debugUrl
> ```
I think this is redundant
</blockquote></details>

Done.
___
*[core/api-server/lib/service/debug.js, line 64 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1321#-Me5Crm28N3bTdDGDe9M:-Me5EbIxCoy5T9MMlxYT:b-u2wxda) ([raw file](https://github.com/kube-hpc/hkube/blob/5e2d1ad3c21d2a4454435fc2731b65802b697416/core/api-server/lib/service/debug.js#L64)):*
> it('ooopppssss, I throw unhandledRejection', async () => {
<details><summary><i alt="summary">Quoted 20 lines of code…</i></summary>

>             const options = {
>                 uri: restPath,
>                 body: {
>                     name: 'exec_raw',
>                     nodes: [
>                         {
>                             nodeName: 'node',
>                             algorithmName: 'green-alg',
>                             input: []
>                         }
>                     ],
>                     options: {
>                         debugOverride: [
>                             'node'
>                         ]
>                     }
>                 }
>             };
>             const res = await request(options);
>         });
</details>
I've fixed it. It wasn't the latest version
___
*[core/api-server/tests/exec-stored.js, line 18 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1321#-Me58EWE6qmVIRdLuvNM:-Me5Etfz0GmtN1vnznbS:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/5e2d1ad3c21d2a4454435fc2731b65802b697416/core/api-server/tests/exec-stored.js#L18)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>         before(async () => {
>             restPath = `${restUrl}/exec/stored`;
>             await stateManager.deleteAlgorithm({ kind: nodeKind.Debug})
>   });
> ```

there is strange formatting in this file
</blockquote></details>

Done.
___
*[core/openapi-spec/package.json, line 10 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1321#-Me570t_CE8HBZ31__SQ:-Me5Evfl5m-Z6LVk_5Wk:b39uv3y) ([raw file](https://github.com/kube-hpc/hkube/blob/5e2d1ad3c21d2a4454435fc2731b65802b697416/core/openapi-spec/package.json#L10)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>       "build-swagger": "node ./swagger-builder.js && echo ../api-server/api/rest-api ../gc-service/api/rest-api ../datasources-service/api/rest-api | xargs -n 1 cp swagger.json",
> ```

Do we want to always change the api-server, gc-service, and ds-service and initiate build to all of them?


</blockquote></details>

It will prevent errors in the future

**Review by NassiHarel — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1321#-:-Me5G5688mp7beVHfA81:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Review by NassiHarel — APPROVED** [review]
> Reviewed 12 of 18 files at r5, 8 of 8 files at r6, 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1321)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
