### PR TITLE
Support datasource external storage

### PR DESCRIPTION
**Pull request by reggev**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1134)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1134)* status: all files reviewed, 10 unresolved discussions (waiting on @reggev)

___
*[core/datasources-service/api/rest-api/routes/v1/datasource.js, line 49 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfoo688PuAWaT3JRy3:-MSfoo688PuAWaT3JRy4:b-rift3o) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/api/rest-api/routes/v1/datasource.js#L49)):*
> ```
> JSON.parse(storage)
> ```
JSON.parse throws an exception if it cannot parse
___
*[core/datasources-service/api/rest-api/swagger/definitions/create.request.yaml, line 21 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfp3sl18pGo31MIl8N:-MSfp3sl18pGo31MIl8O:b68r2ws) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/api/rest-api/swagger/definitions/create.request.yaml#L21)):*
> ```YAML
>         type: object
>         properties:
>             organization:
> ```

just org? no need for user?
___
*[core/datasources-service/config/main/config.base.js, line 85 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfpNrW8ci9ZsKMGFr0:-MSfpNrW8ci9ZsKMGFr1:b-y99gxy) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/config/main/config.base.js#L85)):*
> ```
> GIT_ENDPOINT_URL
> ```
If you require the protocol, we need to change the helm. Just a reminder
___
*[core/datasources-service/config/main/config.base.js, line 90 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfqN4T2gTgoquGtR3j:-MSfqN4T2gTgoquGtR3k:b-tcav22) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/config/main/config.base.js#L90)):*
> ```JavaScript
>     baseDirectory:
>         process.env.BASE_FS_ADAPTER_DIRECTORY || '/var/tmp/fs/storage',
>     baseDatasourcesDirectory:
> ```

why such short lines? In my editor window I can easily fit 120-150 chars. No need to fold the lines at 80
___
*[core/datasources-service/lib/service/downloads.js, line 73 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfrPR6B9T81ueMQAwP:-MSfrPR6B9T81ueMQAwQ:b-r0u97q) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/lib/service/downloads.js#L73)):*
> ```
> `${this.config.directories.prepareForDownload}/${downloadId}`
> ```
path.join()
___
*[core/datasources-service/lib/service/jobs-consumer.js, line 122 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfrcogDttRljzXYg30:-MSfrcogDttRljzXYg31:b3bgeb3) ([raw file](https://github.com/kube-hpc/hkube/blob/d3ebdcb131fabcb4c741c8a11179dcfb90e07b61/core/datasources-service/lib/service/jobs-consumer.js#L122)):*
> ```JavaScript
>             dataSource.name,
>             this.config,
>             `${this.rootDir}/${dataSource.name}/${dataSource.id}`
> ```

path.join()
___
*[core/datasources-service/lib/utils/dvcConfig.js, line 7 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfsmSR-B3QWTJmphHK:-MSfsmSR-B3QWTJmphHL:bqdf28m) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/lib/utils/dvcConfig.js#L7)):*
> ```JavaScript
> /** @param {ExternalStorage} config */
> const S3Config = ({
>     endpoint,
> ```

for user provided S3, we also need bucket name
___
*[core/datasources-service/lib/utils/Repository.js, line 3 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfuH2S2K1wb3F81r6K:-MSfuH2S2K1wb3F81r6L:b-woxtzu) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/lib/utils/Repository.js#L3)):*
> ```
> const { Octokit: GitRestClient } = require('@octokit/rest');
> ```
you need an abstraction over the git client, so you can support both github and gitlab
___
*[core/datasources-service/lib/utils/Repository.js, line 37 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSftGR51S1K36G85zgT:-MSftGR51S1K36G85zgU:b9dsy84) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/lib/utils/Repository.js#L37)):*
> ```
> repositoryName
> ```
Why do you need to pass dir-name separately? Is there a use case where it is not the repo name?
___
*[core/datasources-service/lib/utils/Repository.js, line 63 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSftpia1Fylcgj56ceN:-MSftpib5JwyY5GW_vS0:b-pxahyb) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/lib/utils/Repository.js#L63)):*
> ```JavaScript
>         } else {
>             const url = new URL(value);
>             url.username = this.gitConfig.token;
> ```

You have an implicit precondition, that the token has been set before calling the setter. This is usually unexpected in property setter.
Better create a method that accepts both token and url

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1134)* status: 8 of 27 files reviewed, 10 unresolved discussions (waiting on @yehiyam)

___
*[core/datasources-service/api/rest-api/routes/v1/datasource.js, line 49 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfoo688PuAWaT3JRy3:-MSwbTNh38KW7616Tk05:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/api/rest-api/routes/v1/datasource.js#L49)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> JSON.parse(storage)
> ```
JSON.parse throws an exception if it cannot parse
</blockquote></details>

Done.
___
*[core/datasources-service/api/rest-api/swagger/definitions/create.request.yaml, line 21 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfp3sl18pGo31MIl8N:-MSgZaKcBqEjHVwb93vD:bd17ssl) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/api/rest-api/swagger/definitions/create.request.yaml#L21)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

just org? no need for user?
</blockquote></details>

there's a token property it contains all you need (at least for github)
___
*[core/datasources-service/config/main/config.base.js, line 85 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfpNrW8ci9ZsKMGFr0:-MSgZlqd9but_varw1Td:b-97mefu) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/config/main/config.base.js#L85)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> GIT_ENDPOINT_URL
> ```
If you require the protocol, we need to change the helm. Just a reminder
</blockquote></details>

At this point this is used for testing only, the user sets this endpoint per dataSource on creation
___
*[core/datasources-service/config/main/config.base.js, line 90 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfqN4T2gTgoquGtR3j:-MSgZuPKDbAVjpGY9jPR:b-x43mnq) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/config/main/config.base.js#L90)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why such short lines? In my editor window I can easily fit 120-150 chars. No need to fold the lines at 80
</blockquote></details>

It's not about space, it's because wide lines are just not readable...
___
*[core/datasources-service/lib/service/downloads.js, line 73 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfrPR6B9T81ueMQAwP:-MSgbnYnCNEFQ6pyYtpE:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/lib/service/downloads.js#L73)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> `${this.config.directories.prepareForDownload}/${downloadId}`
> ```
path.join()
</blockquote></details>

Done.
___
*[core/datasources-service/lib/service/jobs-consumer.js, line 122 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfrcogDttRljzXYg30:-MSgbqmIAIqvHnw8P_nE:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/d3ebdcb131fabcb4c741c8a11179dcfb90e07b61/core/datasources-service/lib/service/jobs-consumer.js#L122)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

path.join()
</blockquote></details>

Done.
___
*[core/datasources-service/lib/utils/dvcConfig.js, line 7 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfsmSR-B3QWTJmphHK:-MSwbWh_4H405GbeHBFM:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/lib/utils/dvcConfig.js#L7)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

for user provided S3, we also need bucket name
</blockquote></details>

Done.
___
*[core/datasources-service/lib/utils/Repository.js, line 3 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfuH2S2K1wb3F81r6K:-MSwbXtEAjlIaqGijIa8:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/lib/utils/Repository.js#L3)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> const { Octokit: GitRestClient } = require('@octokit/rest');
> ```
you need an abstraction over the git client, so you can support both github and gitlab
</blockquote></details>

Done.
___
*[core/datasources-service/lib/utils/Repository.js, line 37 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSftGR51S1K36G85zgT:-MSg_F2O8gRNhdzLqg0O:b7en7pf) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/lib/utils/Repository.js#L37)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> repositoryName
> ```
Why do you need to pass dir-name separately? Is there a use case where it is not the repo name?
</blockquote></details>

The cli can have that gap between the repository name and the directory
this is why I added the hkube file to not depend on the directory's name
___
*[core/datasources-service/lib/utils/Repository.js, line 63 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSftpia1Fylcgj56ceN:-MSwb_A36r1ply0HDdDh:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/lib/utils/Repository.js#L63)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

You have an implicit precondition, that the token has been set before calling the setter. This is usually unexpected in property setter.
Better create a method that accepts both token and url
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1134)* status: all files reviewed, 4 unresolved discussions (waiting on @reggev)

___
*[core/datasources-service/api/rest-api/routes/v1/datasource.js, line 49 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSwmtpe-JB6o0t68wAa:-MSwmtpgDmJ3dxr3vxhg:b-h70fi5) ([raw file](https://github.com/kube-hpc/hkube/blob/4a44488cf73a4a0f2551e3ab82c214203189effe/core/datasources-service/api/rest-api/routes/v1/datasource.js#L49)):*
> ```JavaScript
>             let storageConfig;
>             try {
>                 gitConfig = git ? JSON.parse(git) : undefined;
> ```

Is this json in json?
___
*[core/datasources-service/api/rest-api/routes/v1/datasource.js, line 53 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSwl-Wr439cnUh1wonf:-MSwl-Wr439cnUh1wong:bdbgxcz) ([raw file](https://github.com/kube-hpc/hkube/blob/4a44488cf73a4a0f2551e3ab82c214203189effe/core/datasources-service/api/rest-api/routes/v1/datasource.js#L53)):*
> ```JavaScript
>             } catch (error) {
>                 throw new InvalidDataError(
>                     "you provided invalid 'git' or 'storage' settings"
> ```

Don't use "second person (you)"
___
*[core/datasources-service/config/main/config.base.js, line 90 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfqN4T2gTgoquGtR3j:-MSwo2KT0064cwtxQgYP:bbojxkx) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/config/main/config.base.js#L90)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

It's not about space, it's because wide lines are just not readable...
</blockquote></details>

80 lines are not readable as well... everything is split into 2-3 lines
___
*[core/datasources-service/lib/utils/GitRemoteClient/Github.js, line 47 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSwoohs33IIc23BQ_Sf:-MSwoohtAsi4Uhj9D9So:b-kookti) ([raw file](https://github.com/kube-hpc/hkube/blob/4a44488cf73a4a0f2551e3ab82c214203189effe/core/datasources-service/lib/utils/GitRemoteClient/Github.js#L47)):*
> ```JavaScript
> 
>     async deleteRepository() {
>         throw new Error('Github deleteRepository: not implemented!');
> ```

Is there a reason it is not implemented? or not implemented yet?

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1134)* status: 24 of 31 files reviewed, 4 unresolved discussions (waiting on @yehiyam)

___
*[core/datasources-service/api/rest-api/routes/v1/datasource.js, line 49 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSwmtpe-JB6o0t68wAa:-MSwuNtu1qLJlpjyEoZu:b-p8nhsy) ([raw file](https://github.com/kube-hpc/hkube/blob/4a44488cf73a4a0f2551e3ab82c214203189effe/core/datasources-service/api/rest-api/routes/v1/datasource.js#L49)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is this json in json?
</blockquote></details>

yes it is a stringified JSON data sent as form data
___
*[core/datasources-service/api/rest-api/routes/v1/datasource.js, line 53 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSwl-Wr439cnUh1wonf:-MSwvBq0EKqUeTiS_qIH:b-4z8js7) ([raw file](https://github.com/kube-hpc/hkube/blob/4a44488cf73a4a0f2551e3ab82c214203189effe/core/datasources-service/api/rest-api/routes/v1/datasource.js#L53)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Don't use "second person (you)"
</blockquote></details>

I did a search and eliminated all the instances of "you" in the repository
___
*[core/datasources-service/config/main/config.base.js, line 90 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSfqN4T2gTgoquGtR3j:-MSwuY5D33O-s1Gy4etO:b-koapb0) ([raw file](https://github.com/kube-hpc/hkube/blob/46f03ae8db735d842e2fbbd74f0cf0ed9e131d32/core/datasources-service/config/main/config.base.js#L90)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

80 lines are not readable as well... everything is split into 2-3 lines
</blockquote></details>

80 is the common practice and it is much much better than going wide
___
*[core/datasources-service/lib/utils/GitRemoteClient/Github.js, line 47 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1134#-MSwoohs33IIc23BQ_Sf:-MSwuhEE4GpxewJuE_tj:bcrp4hx) ([raw file](https://github.com/kube-hpc/hkube/blob/4a44488cf73a4a0f2551e3ab82c214203189effe/core/datasources-service/lib/utils/GitRemoteClient/Github.js#L47)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is there a reason it is not implemented? or not implemented yet?
</blockquote></details>

it is implemented in another branch and will be merged later on

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1134#-:-MT-nAjPBVxkdDI7gniz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
