### PR TITLE
Support internal kind

### PR DESCRIPTION
**Pull request by reggev**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1148)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 17 of 19 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1148)* status: all files reviewed, 2 unresolved discussions (waiting on @reggev)

___
*[core/datasources-service/bootstrap.js, line 61 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1148#-MTaJHH9CKP1nWb8TPXV:-MTaJHH9CKP1nWb8TPXW:ba1byb7) ([raw file](https://github.com/kube-hpc/hkube/blob/dcd78048fb31fa00245dd3fd663491204d1d0b4c/core/datasources-service/bootstrap.js#L61)):*
> ```
> process.on('beforeExit'
> ```
exit is never called... 
___
*[core/datasources-service/bootstrap.js, line 59 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1148#-MTivrb19icgoOpyHHfF:-MTivrb19icgoOpyHHfG:b-jmepyd) ([raw file](https://github.com/kube-hpc/hkube/blob/17a2d8cc7c4269944f60a6d31454e4204e6fb6b6/core/datasources-service/bootstrap.js#L59)):*
> ```JavaScript
>     }
> 
>     async _handleExit() {
> ```

unused

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1148)* status: 2 of 26 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/datasources-service/bootstrap.js, line 61 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1148#-MTaJHH9CKP1nWb8TPXV:-MTjKtSC9Eu1Hb2De24S:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/dcd78048fb31fa00245dd3fd663491204d1d0b4c/core/datasources-service/bootstrap.js#L61)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> process.on('beforeExit'
> ```
exit is never called... 
</blockquote></details>

Done.
___
*[core/datasources-service/bootstrap.js, line 59 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1148#-MTivrb19icgoOpyHHfF:-MTjKt6REjMx1xg_9TT_:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/17a2d8cc7c4269944f60a6d31454e4204e6fb6b6/core/datasources-service/bootstrap.js#L59)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

unused
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 13 of 18 files at r3, 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1148)* status: all files reviewed, 1 unresolved discussion (waiting on @reggev)

___
*[core/datasources-service/package.json, line 20 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1148#-MTkAkVSAh2uJavPi3em:-MTkAkVT-qI74k9yYITc:b-tvaw9f) ([raw file](https://github.com/kube-hpc/hkube/blob/17d84e9aa8f7c21133cb625ec817cb383c6cd44b/core/datasources-service/package.json#L20)):*
> ```JSON
>         "@hkube/storage-manager": "^2.0.33",
>         "@hkube/uid": "^1.0.4",
>         "@homer0/prettier-plugin-jsdoc": "^2.0.0",
> ```

why not in dev-dependencies
BTW, this package has 200 downloads and 3 stars. I don't think we should use it

**Review by yehiyam — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1148)* status: all files reviewed, 1 unresolved discussion (waiting on @reggev)

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1148#-:-MUI_MvX4gSzpHaGewBT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
