### PR TITLE
Fix concurrent jobs

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1491)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1491)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/api/rest-api/swagger/definitions/pipeline.yaml, line 36 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1491#-MsAhumw1KIR7o-4csE1:-MsAhumw1KIR7o-4csE2:b2ug38c) ([raw file](https://github.com/kube-hpc/hkube/blob/22bce9e3ac9772f9c19314b2b10c6e5e2f8a440c/core/api-server/api/rest-api/swagger/definitions/pipeline.yaml#L36)):*
> ```YAML
>     type: string
>     description: the root job id of the current tree
>   maxExceeded:
> ```

Is this something that the user can add to the pipeline?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1491)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/api-server/api/rest-api/swagger/definitions/pipeline.yaml, line 36 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1491#-MsAhumw1KIR7o-4csE1:-MsAka7yBjM4iWbdkgwp:bgz0rdd) ([raw file](https://github.com/kube-hpc/hkube/blob/22bce9e3ac9772f9c19314b2b10c6e5e2f8a440c/core/api-server/api/rest-api/swagger/definitions/pipeline.yaml#L36)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is this something that the user can add to the pipeline?
</blockquote></details>

No, but for now the re-run is failed without it, and I didn't want to fix the UI.

**Review by yehiyam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1491)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Pull request merged**
