### PR TITLE
add reason to stop,and filter by pause

### PR DESCRIPTION
**Pull request by zivglik**
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1836)

### CODE REVIEW

**Comment by zivglik** [comment]
https://github.com/kube-HPC/hkube/issues/1809

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1836)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zivglik)

**Pull request merged**
