### PR TITLE
Node version algorithem

### PR DESCRIPTION
**Pull request by zivglik**
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1689)

### CODE REVIEW

**Review by golanha — COMMENTED** [review]
> Reviewed 5 of 6 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1689)* status: all files reviewed, 1 unresolved discussion (waiting on @zivglik)

**Review by golanha — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1689#-:-NPziQ0f9NUANHFDtVwo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @zivglik)

**Review by zivglik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1689)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`core/pipeline-driver/lib/tasks/task-runner.js` line 196 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1689#-NPqM3d83quvclxJaS7H:-NQ-lYCc8aP5qn31SL8_:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/3d9d796ef14ddc662c67d1185c93a91ffad3fdfb/core/pipeline-driver/lib/tasks/task-runner.js#L196)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

you don't need this variable, you can set the pipeline.nodes directly
</blockquote></details>

Done.

**Review by golanha — COMMENTED** [review]
> Reviewed 5 of 7 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1689)* status: all files reviewed, 1 unresolved discussion (waiting on @zivglik)

**Pull request merged**
