### PR TITLE
add queue count

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1553)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1553)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @golanha)

___
*[core/openapi-spec/swagger/paths/preferred/preferred_count.yaml, line 25 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1553#-My7U_uVB5Qbvn3co_P5:-My7U_uVB5Qbvn3co_P6:b74i4ki) ([raw file](https://github.com/kube-hpc/hkube/blob/e5ad650113785e52b96399f170c84ffc65420f7e/core/openapi-spec/swagger/paths/preferred/preferred_count.yaml#L25)):*
> ```YAML
>           schema:
>             $ref: "#/components/schemas/error"
> post:
> ```

is this copy-paste error? What is the meaning of post to count



_Code quote:_
```YAML
post
```
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 33 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1553#-My7XBXDBC7m5CoxE1Qb:-My7XBXDBC7m5CoxE1Qc:b-l6mwxj) ([raw file](https://github.com/kube-hpc/hkube/blob/e5ad650113785e52b96399f170c84ffc65420f7e/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L33)):*
> ```JavaScript
>         else filteredList = queueRunner.preferredQueue.queue;
>         return filteredList.map(job => {
>             const { score, calculated, next, maxExceeded, ...rest } = job;
> ```

remove

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1553)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 33 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1553#-My7XBXDBC7m5CoxE1Qb:-My7rX1yDVzJTiynvkP_:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/e5ad650113785e52b96399f170c84ffc65420f7e/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L33)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[core/openapi-spec/swagger/paths/preferred/preferred_count.yaml, line 25 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1553#-My7U_uVB5Qbvn3co_P5:-My7rUQj721QFNsZSVnm:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/e5ad650113785e52b96399f170c84ffc65420f7e/core/openapi-spec/swagger/paths/preferred/preferred_count.yaml#L25)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

is this copy-paste error? What is the meaning of post to count
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1553)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[core/pipeline-driver-queue/api/rest-api/root.js, line 7 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1553#-My80JnM74O1ZEvSy185:-My80JnM74O1ZEvSy186:bfzgngi) ([raw file](https://github.com/kube-hpc/hkube/blob/5ee12dbbab2a55d4145756469e6b8f9d8fa90d05/core/pipeline-driver-queue/api/rest-api/root.js#L7)):*
> ```JavaScript
> const routes = () => {
>     const router = RestServer.router();
>     router.get('/', (req, res) => {
> ```

Why did you add the / path? Isn't there a similar API in /managed

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1553)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/pipeline-driver-queue/api/rest-api/root.js, line 7 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1553#-My80JnM74O1ZEvSy185:-MyBqto5-kST2-P-C2G2:b-bza1q8) ([raw file](https://github.com/kube-hpc/hkube/blob/5ee12dbbab2a55d4145756469e6b8f9d8fa90d05/core/pipeline-driver-queue/api/rest-api/root.js#L7)):*
> managed
No I removed the count api from ".../queue/preferred" and from ".../queue/managed" and put it in shared path ".../queue/"

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1553#-:-MyBukhWAbWonxQjHtUW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

___
*[core/pipeline-driver-queue/api/rest-api/root.js, line 7 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1553#-My80JnM74O1ZEvSy185:-MyBuNWu6F_TlfMVTpMj:b32w0x) ([raw file](https://github.com/kube-hpc/hkube/blob/5ee12dbbab2a55d4145756469e6b8f9d8fa90d05/core/pipeline-driver-queue/api/rest-api/root.js#L7)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> managed
No I removed the count api from ".../queue/preferred" and from ".../queue/managed" and put it in shared path ".../queue/"
</blockquote></details>

OK

**Pull request merged**
