### PR TITLE
Store algorithms update - api call + insert algo

### PR DESCRIPTION
**Pull request by mkkCoder**
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1799)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 4 of 13 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1799)* status: all files reviewed, 2 unresolved discussions (waiting on @mkkCoder)

___
*[`core/api-server/api/rest-api/routes/v1/store.js` line 70 at r2](https://reviewable.io/reviews/kube-HPC/hkube/1799#-NfF2z-o50SuMMmqnaE_:-NfF2z-o50SuMMmqnaEa:b-56zp5h) ([raw file](https://github.com/kube-HPC/hkube/blob/a451140f8775e2dd1e1d2031278ffadf8b1da4f1/core/api-server/api/rest-api/routes/v1/store.js#L70)):*
> ```JavaScript
>                 req.body.map(async (algorithmData) => {
>                     // eslint-disable-next-line no-return-await
>                     return await algorithmStore.insertAlgorithm(algorithmData, listFlag);
> ```

You can simplely sent  <i>true</i> 
No need for the flag



_Code quote:_
```JavaScript
listFlag)
```
___
*[`core/api-server/lib/service/algorithms.js` line 107 at r2](https://reviewable.io/reviews/kube-HPC/hkube/1799#-NfFRBJ56nZnIQud-YlP:-NfFRBJ56nZnIQud-YlQ:b-xnn2ua) ([raw file](https://github.com/kube-HPC/hkube/blob/a451140f8775e2dd1e1d2031278ffadf8b1da4f1/core/api-server/lib/service/algorithms.js#L107)):*
> ```JavaScript
>             const { algorithm } = await this.applyAlgorithm({ payload: options });
>             return algorithm;
>         }
> ```

Validation invokation is can be written once. You can chack the "failOnError" after validation is done, if true throw exception if false return the error.
In any case no need to throw the exception catch it and only then return it.



_Code quote:_
```JavaScript
        if (!listFlag) {
            validator.algorithms.validateAlgorithmName(options);
            const alg = await stateManager.getAlgorithm(options);
            if (alg) {
                throw new ResourceExistsError('algorithm', options.name);
            }
            const { algorithm } = await this.applyAlgorithm({ payload: options });
            return algorithm;
        }
        try {
            validator.algorithms.validateAlgorithmName(options);
            const alg = await stateManager.getAlgorithm(options);
            if (alg) {
                // eslint-disable-next-line no-throw-literal
                throw {
                    code: 409,
                    message: `algorithm ${options.name} already exists`,
                };
            }
            const { algorithm } = await this.applyAlgorithm({ payload: options });
            return algorithm;
        }
```

**Review by mkkCoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1799)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[`core/api-server/api/rest-api/routes/v1/store.js` line 70 at r2](https://reviewable.io/reviews/kube-HPC/hkube/1799#-NfF2z-o50SuMMmqnaE_:-NfKw5-h3CEX_SBEfCSA:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/a451140f8775e2dd1e1d2031278ffadf8b1da4f1/core/api-server/api/rest-api/routes/v1/store.js#L70)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

You can simplely sent  <i>true</i> 
No need for the flag
</blockquote></details>

Done.
___
*[`core/api-server/lib/service/algorithms.js` line 107 at r2](https://reviewable.io/reviews/kube-HPC/hkube/1799#-NfFRBJ56nZnIQud-YlP:-NfKw65y8egKhord6YNf:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/a451140f8775e2dd1e1d2031278ffadf8b1da4f1/core/api-server/lib/service/algorithms.js#L107)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Validation invokation is can be written once. You can chack the "failOnError" after validation is done, if true throw exception if false return the error.
In any case no need to throw the exception catch it and only then return it.
</blockquote></details>

Done.

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1799)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @mkkCoder)

___
*[`core/api-server/api/rest-api/routes/v1/store.js` line 78 at r4](https://reviewable.io/reviews/kube-HPC/hkube/1799#-NfQO4Iz-Ev85COFBhwg:-NfQO4Iz-Ev85COFBhwh:bdmvm7n) ([raw file](https://github.com/kube-HPC/hkube/blob/6b066d46565f095e33834302bc809872bb3c4f20/core/api-server/api/rest-api/routes/v1/store.js#L78)):*
> ```JavaScript
>     router.post('/algorithms', async (req, res) => {
>         if (Array.isArray(req.body)) {
>             const failOnError = false;
> ```

You don't need this variable just send <i>true</i> or don't send any thing since true is default



_Code quote:_
```JavaScript
const failOnError = false;
```

**Review by mkkCoder — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1799)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[`core/api-server/api/rest-api/routes/v1/store.js` line 78 at r4](https://reviewable.io/reviews/kube-HPC/hkube/1799#-NfQO4Iz-Ev85COFBhwg:-NfQQzot3OpvTwxJqSbN:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/6b066d46565f095e33834302bc809872bb3c4f20/core/api-server/api/rest-api/routes/v1/store.js#L78)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

You don't need this variable just send <i>true</i> or don't send any thing since true is default
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1799)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkkCoder)

**Pull request merged**
