### PR TITLE
add support for cyclic graph, streaming custom flow

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1010)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1010)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/lib/service/pipeline-creator.js, line 8 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1010#-MLhfJEqAxJjFVaIS6-p:-MLhfJEr0JsgF0IzFQFh:b-jk92tj) ([raw file](https://github.com/kube-hpc/hkube/blob/7bc91010d762681c10d4d9ffee21ff127c05c3d1/core/api-server/lib/service/pipeline-creator.js#L8)):*
> ```
> buildPipelineOfPipeline
> ```
Is this something that is finished? if so maybe add a feature issue and pass to Tamir for testing
___
*[core/api-server/lib/service/pipeline-creator.js, line 91 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1010#-MLhfyOFA5MgsfZ-mSAI:-MLhfyOFA5MgsfZ-mSAJ:b-m6qa9b) ([raw file](https://github.com/kube-hpc/hkube/blob/7bc91010d762681c10d4d9ffee21ff127c05c3d1/core/api-server/lib/service/pipeline-creator.js#L91)):*
> ```JavaScript
>             const expressions = v.replace(/\s/g, '').split(',');
>             expressions.forEach((e) => {
>                 const parts = e.split('>>');
> ```

Is this the only place where `>>` is mentioned? if not maybe create a constant for that
___
*[core/api-server/tests/exec-raw.js, line 576 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1010#-MLhgKXZ6GVvf4ymcpd-:-MLhgKX_8SH5VBkjnO6x:b8w64dh) ([raw file](https://github.com/kube-hpc/hkube/blob/7bc91010d762681c10d4d9ffee21ff127c05c3d1/core/api-server/tests/exec-raw.js#L576)):*
> ```
> succeed
> ```
fail

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1010)* status: 5 of 17 files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/lib/service/pipeline-creator.js, line 8 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1010#-MLhfJEqAxJjFVaIS6-p:-MLm8inwAkLY8k42GeeP:bhkc42j) ([raw file](https://github.com/kube-hpc/hkube/blob/7bc91010d762681c10d4d9ffee21ff127c05c3d1/core/api-server/lib/service/pipeline-creator.js#L8)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> buildPipelineOfPipeline
> ```
Is this something that is finished? if so maybe add a feature issue and pass to Tamir for testing
</blockquote></details>

Need more tests
___
*[core/api-server/lib/service/pipeline-creator.js, line 91 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1010#-MLhfyOFA5MgsfZ-mSAI:-MLm7Jyj--o16w8MYWOr:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/7bc91010d762681c10d4d9ffee21ff127c05c3d1/core/api-server/lib/service/pipeline-creator.js#L91)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is this the only place where `>>` is mentioned? if not maybe create a constant for that
</blockquote></details>

Done.
___
*[core/api-server/tests/exec-raw.js, line 576 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1010#-MLhgKXZ6GVvf4ymcpd-:-MLm7M1VAKfO5zUbOdrM:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/7bc91010d762681c10d4d9ffee21ff127c05c3d1/core/api-server/tests/exec-raw.js#L576)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> succeed
> ```
fail
</blockquote></details>

Done.

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1010)* status: 5 of 19 files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/lib/service/pipeline-creator.js, line 8 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1010#-MLhfJEqAxJjFVaIS6-p:-MLqSDZwAVSXYMR59uj3:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/7bc91010d762681c10d4d9ffee21ff127c05c3d1/core/api-server/lib/service/pipeline-creator.js#L8)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Need more tests
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1010#-:-MLqTc4y2QThhebAKDE2:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/api/rest-api/swagger/definitions/pipeline.yaml, line 51 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1010#-MLqRPCD4r0NcwiH5GTL:-MLqRPCEEhcp1yP0rG0Q:b-6e4wcc) ([raw file](https://github.com/kube-hpc/hkube/blob/47d535ef6f8df3c3d7f1ad0d62172f452a0901f2/core/api-server/api/rest-api/swagger/definitions/pipeline.yaml#L51)):*
> ```YAML
>         description: define custom streaming flow in simple syntax
>         example: node A stream to B and C, node B stream to D will be like "A >> B&C , B >> D"
>   edges:
> ```

What is the purpose of this? Part of the custom flows? Is it something the user is expected to use?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1010)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/api-server/api/rest-api/swagger/definitions/pipeline.yaml, line 51 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1010#-MLqRPCD4r0NcwiH5GTL:-MLqTqapCX6YXdpVx3EL:brl4cu4) ([raw file](https://github.com/kube-hpc/hkube/blob/47d535ef6f8df3c3d7f1ad0d62172f452a0901f2/core/api-server/api/rest-api/swagger/definitions/pipeline.yaml#L51)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

What is the purpose of this? Part of the custom flows? Is it something the user is expected to use?
</blockquote></details>

This is the API for defining the streaming flow, for users that want dynamic flow during streaming

**Review by yehiyam — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1010)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
