### PR TITLE
count instead of jobs list and expose filter by pipeline and tag

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1513)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1513)* status: all files reviewed, 4 unresolved discussions (waiting on @golanha)

___
*[core/openapi-spec/swagger/paths/managed/list.yaml, line 32 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1513#-MupJMHp2G1Skd-KESCE:-MupJMHp2G1Skd-KESCF:b-k10qpq) ([raw file](https://github.com/kube-hpc/hkube/blob/a2cd4c48f4874e2c2a8b64cb5be84fb733ff70c0/core/openapi-spec/swagger/paths/managed/list.yaml#L32)):*
> ```YAML
>       schema:
>         type: string        
>       description: filter by tag            
> ```

extra spaces



_Code quote:_
```YAML
············
```
___
*[core/openapi-spec/swagger/paths/preferred/list.yaml, line 1 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1513#-MupJZxn-f78f4qfKCsK:-MupJZxn-f78f4qfKCsL:bxnnj7s) ([raw file](https://github.com/kube-hpc/hkube/blob/a2cd4c48f4874e2c2a8b64cb5be84fb733ff70c0/core/openapi-spec/swagger/paths/preferred/list.yaml#L1)):*
> ```YAML
> get:
> ```

is this used? It looks the same as paths/preferred/prefered.yaml
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 118 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1513#-MupJyiR3vkv-v4JPz4G:-MupJyiR3vkv-v4JPz4H:bl5je45) ([raw file](https://github.com/kube-hpc/hkube/blob/a2cd4c48f4874e2c2a8b64cb5be84fb733ff70c0/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L118)):*
> ```JavaScript
>     }
> 
>     async addPreferredJobs(addedJobs) {
> ```

no need for async
___
*[core/pipeline-driver-queue/tests/test-preferred-managed.js, line 10 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1513#-MupItcb4iychbtU7WcF:-MupItcg-dBPkHaGr_te:b-g56zud) ([raw file](https://github.com/kube-hpc/hkube/blob/a2cd4c48f4874e2c2a8b64cb5be84fb733ff70c0/core/pipeline-driver-queue/tests/test-preferred-managed.js#L10)):*
> ```JavaScript
> let producerLib;
> 
> describe.only('Preferred and Managed', () => {
> ```

remove `only`

**Review by nassiharel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1513)* status: all files reviewed, 5 unresolved discussions (waiting on @golanha)

___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 118 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1513#-MupKQf_DvyaZdD_M9zL:-MupKQf_DvyaZdD_M9zM:badp2g0) ([raw file](https://github.com/kube-hpc/hkube/blob/0bccdb84c354c2cf9bdf8daec56fbc10751a47d3/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L118)):*
> ```JavaScript
>     }
> 
>     async addPreferredJobs(addedJobs) {
> ```

There is nothing asynchronous in this function :)



_Code quote:_
```JavaScript
async addPreferredJobs(addedJobs) {
```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1513)* status: 1 of 14 files reviewed, 5 unresolved discussions (waiting on @nassiharel and @yehiyam)

___
*[core/openapi-spec/swagger/paths/managed/list.yaml, line 32 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1513#-MupJMHp2G1Skd-KESCE:-MupR-Z52YWzIac52ODL:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/a2cd4c48f4874e2c2a8b64cb5be84fb733ff70c0/core/openapi-spec/swagger/paths/managed/list.yaml#L32)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

extra spaces
</blockquote></details>

Done.



_Code quote:_
```YAML
description: filter by tag
```
___
*[core/openapi-spec/swagger/paths/preferred/list.yaml, line 1 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1513#-MupJZxn-f78f4qfKCsK:-MupRLaZ95aBBFTGVPzX:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/a2cd4c48f4874e2c2a8b64cb5be84fb733ff70c0/core/openapi-spec/swagger/paths/preferred/list.yaml#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

is this used? It looks the same as paths/preferred/prefered.yaml
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 118 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1513#-MupJyiR3vkv-v4JPz4G:-MupRfJM689amjm2OsBP:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/a2cd4c48f4874e2c2a8b64cb5be84fb733ff70c0/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L118)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

no need for async
</blockquote></details>

Done.



_Code quote:_
```JavaScript
async addPreferredJobs(addedJobs)
```
___
*[core/pipeline-driver-queue/lib/service/preferred-jobs.js, line 118 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1513#-MupKQf_DvyaZdD_M9zL:-MupRyLdEJyzWhPoz0pl:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/0bccdb84c354c2cf9bdf8daec56fbc10751a47d3/core/pipeline-driver-queue/lib/service/preferred-jobs.js#L118)):*
<details><summary><i>Previously, nassiharel (Nassi Harel) wrote…</i></summary><blockquote>

There is nothing asynchronous in this function :)
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/tests/test-preferred-managed.js, line 10 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1513#-MupItcb4iychbtU7WcF:-Mut6f_b58R-GlArqN44:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/a2cd4c48f4874e2c2a8b64cb5be84fb733ff70c0/core/pipeline-driver-queue/tests/test-preferred-managed.js#L10)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

remove `only`
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r3, 2 of 7 files at r4, 1 of 1 files at r5, 5 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1513#-:-MvNbuPj3QQCdadNt4PF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nassiharel)

**Pull request merged**
