### PR TITLE
use internal artifactory at java build

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1040)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1040)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 11 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1040#-MO-yffw1s51ikWRBnRu:-MO-yffw1s51ikWRBnRv:bt05s2g) ([raw file](https://github.com/kube-hpc/hkube/blob/1b290b815161df2b94129f06e1c531a85ceb3baf/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L11)):*
> ```
> mvn-registry
> ```
shouldn't it be artifacts-registry?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1040)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 11 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1040#-MO-yffw1s51ikWRBnRu:-MO0T28C29TZmMXSZekH:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/1b290b815161df2b94129f06e1c531a85ceb3baf/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L11)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> mvn-registry
> ```
shouldn't it be artifacts-registry?
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1040#-:-MO5t1Hm87pIPdEDsRwb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
