### PR TITLE
feat: add logger

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1205)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1205)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/algorithm-builder/environments/nodejs/wrapper/app.js, line 3 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1205#-MX7dzuQ3ixD6t-EeCWo:-MX7dzuQ3ixD6t-EeCWp:b-1gl50q) ([raw file](https://github.com/kube-hpc/hkube/blob/76eac67e4010f10b4780d72631ac3c4b1cb3442d/core/algorithm-builder/environments/nodejs/wrapper/app.js#L3)):*
> ```JavaScript
> const Logger = require('@hkube/logger');
> const config = require('./config');
> const log = new Logger(config.serviceName, config.logger);
> ```

what will happen if a user builds its own app.js (with `NodejsWrapper.run();`) but doesn't create the logger. I think that `GetLoggerFromContainer` will return null.
Isn't it better to create the logger inside of the wrapper (like in python) and not here?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1205)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/algorithm-builder/environments/nodejs/wrapper/app.js, line 3 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1205#-MX7dzuQ3ixD6t-EeCWo:-MX7fUhF2Hya5OfFnRUa:bcqiwpl) ([raw file](https://github.com/kube-hpc/hkube/blob/76eac67e4010f10b4780d72631ac3c4b1cb3442d/core/algorithm-builder/environments/nodejs/wrapper/app.js#L3)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

what will happen if a user builds its own app.js (with `NodejsWrapper.run();`) but doesn't create the logger. I think that `GetLoggerFromContainer` will return null.
Isn't it better to create the logger inside of the wrapper (like in python) and not here?
</blockquote></details>

This was the first implementation (like python), but I was doing this in each constructor,
`log = logger.GetLogFromContainer();`

and because the wrapper requires the `@hkube/nodejs-wrapper` that requires the `@hkube/worker-data-adapter`
it was super complex and not work well..... I will try again.....

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1205)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/algorithm-builder/environments/nodejs/wrapper/app.js, line 3 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1205#-MX7dzuQ3ixD6t-EeCWo:-MX7ik6V6Sz5fI_Ox-EM:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/76eac67e4010f10b4780d72631ac3c4b1cb3442d/core/algorithm-builder/environments/nodejs/wrapper/app.js#L3)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

This was the first implementation (like python), but I was doing this in each constructor,
`log = logger.GetLogFromContainer();`

and because the wrapper requires the `@hkube/nodejs-wrapper` that requires the `@hkube/worker-data-adapter`
it was super complex and not work well..... I will try again.....
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1205#-:-MX7nhdm3HZyvjZY-jBZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Pull request merged**
