### PR TITLE
Cli endpoint

### PR DESCRIPTION
**Pull request by reggev**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1121)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1121)* status: all files reviewed, 4 unresolved discussions (waiting on @reggev)

___
*[core/datasources-service/api/rest-api/swagger/paths/sync.yaml, line 11 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1121#-MSaqqzd9m1mWa9LbH_O:-MSaqqzd9m1mWa9LbH_P:b-e6gu3w) ([raw file](https://github.com/kube-hpc/hkube/blob/f9018808bdff468cdc069ee2aab65c6c68091be9/core/datasources-service/api/rest-api/swagger/paths/sync.yaml#L11)):*
> ```YAML
>             application/json:
>                 schema:
>                     $ref: '#/components/schemas/syncRequest'
> ```

What will be the name of the version? the name of the latest git commit?
___
*[core/datasources-service/lib/utils/Repository.js, line 5 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1121#-MSasewg1vF8757jw134:-MSasewg1vF8757jw135:begzusw) ([raw file](https://github.com/kube-hpc/hkube/blob/f9018808bdff468cdc069ee2aab65c6c68091be9/core/datasources-service/lib/utils/Repository.js#L5)):*
> ```JavaScript
> const {
>     glob,
>     Repository: _Repository,
> ```

Why not `BaseRepository`?
___
*[core/datasources-service/lib/utils/Shell.js, line 0 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1121#-MSatGic4R6HJbumBYsT:-MSatGic4R6HJbumBYsU:bxijp75) ([raw file](https://github.com/kube-hpc/hkube/blob/f9018808bdff468cdc069ee2aab65c6c68091be9/core/datasources-service/lib/utils/Shell.js#L0)):*
I noticed that in the package (https://github.com/kube-HPC/datasource-utils/blob/main/lib/Shell.js#L18) it has `cmd.on('close')` and not `exit`
I know you have another PR for that, but the other PR is in hkube and not the package
___
*[core/datasources-service/tests/setup.js, line 37 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1121#-MSauMzP4Sqr8stPsAQj:-MSauMzP4Sqr8stPsAQk:by3d5pg) ([raw file](https://github.com/kube-hpc/hkube/blob/f9018808bdff468cdc069ee2aab65c6c68091be9/core/datasources-service/tests/setup.js#L37)):*
> ```JavaScript
>     // fse.removeSync('temp/');
>     // fse.removeSync('uploads/');
>     // fse.removeSync(STORAGE_DIR);
> ```

delete comments

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1121)* status: 30 of 32 files reviewed, 4 unresolved discussions (waiting on @yehiyam)

___
*[core/datasources-service/api/rest-api/swagger/paths/sync.yaml, line 11 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1121#-MSaqqzd9m1mWa9LbH_O:-MSb-cUt1vmLCAv78xKx:b6ucp5w) ([raw file](https://github.com/kube-hpc/hkube/blob/f9018808bdff468cdc069ee2aab65c6c68091be9/core/datasources-service/api/rest-api/swagger/paths/sync.yaml#L11)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

What will be the name of the version? the name of the latest git commit?
</blockquote></details>

it'll pull the log from git and take the comment from the latest commit
___
*[core/datasources-service/lib/utils/Repository.js, line 5 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1121#-MSasewg1vF8757jw134:-MSb-zmlAPIjNGT-HaY9:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/f9018808bdff468cdc069ee2aab65c6c68091be9/core/datasources-service/lib/utils/Repository.js#L5)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Why not `BaseRepository`?
</blockquote></details>

Done.
___
*[core/datasources-service/lib/utils/Shell.js, line  at r2](https://reviewable.io/reviews/kube-hpc/hkube/1121#-MSatGic4R6HJbumBYsT:-MSb0dXu305R5FHXYC7p:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/f9018808bdff468cdc069ee2aab65c6c68091be9/core/datasources-service/lib/utils/Shell.js#L)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I noticed that in the package (https://github.com/kube-HPC/datasource-utils/blob/main/lib/Shell.js#L18) it has `cmd.on('close')` and not `exit`
I know you have another PR for that, but the other PR is in hkube and not the package
</blockquote></details>

Done.
___
*[core/datasources-service/tests/setup.js, line 37 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1121#-MSauMzP4Sqr8stPsAQj:-MSb0e0M4HpQh7lgMfpY:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/f9018808bdff468cdc069ee2aab65c6c68091be9/core/datasources-service/tests/setup.js#L37)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

delete comments
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1121)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)

**Review by yehiyam — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1121)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yehiyam — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1121)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yehiyam — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1121#-:-MScf3WnCyxNN5cHoRmc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
