### PR TITLE
adding stopping command

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1097)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1097)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[core/worker/lib/states/stateManager.js, line 23 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1097#-MQwNPQkALbYbuc43xWY:-MQwNPQl31585ybalb4P:b-tpi56g) ([raw file](https://github.com/kube-hpc/hkube/blob/37a44e29bcfa77d9603dfc9aba358467c5b59ed7/core/worker/lib/states/stateManager.js#L23)):*
> ```
> this._forceStop = true;
> ```

Here it's true by default
___
*[core/worker/lib/states/stateManager.js, line 169 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1097#-MQwNZ6R9HZ3sMQJW4To:-MQwNZ6R9HZ3sMQJW4Tp:b-3pjx8u) ([raw file](https://github.com/kube-hpc/hkube/blob/37a44e29bcfa77d9603dfc9aba358467c5b59ed7/core/worker/lib/states/stateManager.js#L169)):*
> ```
> forceStop = true
> ```
And here it's also true by default
___
*[core/worker/lib/states/stateManager.js, line 220 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1097#-MQwNV710ZfBeoIMw_vJ:-MQwNV710ZfBeoIMw_vK:b-2kr6df) ([raw file](https://github.com/kube-hpc/hkube/blob/37a44e29bcfa77d9603dfc9aba358467c5b59ed7/core/worker/lib/states/stateManager.js#L220)):*
> ```
> this._forceStop = false;
> ```
And here it's false by default

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1097)* status: all files reviewed, 4 unresolved discussions (waiting on @golanha)

___
*[core/worker/lib/worker.js, line 19 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1097#-MQwNgW3BxJUvGH39HY0:-MQwNgW4AxTke6JZWYiU:b-i0k997) ([raw file](https://github.com/kube-hpc/hkube/blob/37a44e29bcfa77d9603dfc9aba358467c5b59ed7/core/worker/lib/worker.js#L19)):*
> ```
> const DEFAULT_STOPPING_INTERVAL = 200;
> ```
200 ?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1097)* status: all files reviewed, 4 unresolved discussions (waiting on @NassiHarel)

___
*[core/worker/lib/worker.js, line 19 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1097#-MQwNgW3BxJUvGH39HY0:-MQwXRWv1uxHBAaIiqyF:b-mj0pso) ([raw file](https://github.com/kube-hpc/hkube/blob/37a44e29bcfa77d9603dfc9aba358467c5b59ed7/core/worker/lib/worker.js#L19)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const DEFAULT_STOPPING_INTERVAL = 200;
> ```
200 ?
</blockquote></details>

About 3 minutes, the wrapper sends stopping every second.
___
*[core/worker/lib/states/stateManager.js, line 23 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1097#-MQwNPQkALbYbuc43xWY:-MQwXQUq9iaTZ79USAfn:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/37a44e29bcfa77d9603dfc9aba358467c5b59ed7/core/worker/lib/states/stateManager.js#L23)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> this._forceStop = true;
> ```

Here it's true by default
</blockquote></details>

Done.
___
*[core/worker/lib/states/stateManager.js, line 169 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1097#-MQwNZ6R9HZ3sMQJW4To:-MQwXQ95-Sgv3Z4PMXDp:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/37a44e29bcfa77d9603dfc9aba358467c5b59ed7/core/worker/lib/states/stateManager.js#L169)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> forceStop = true
> ```
And here it's also true by default
</blockquote></details>

Done.
___
*[core/worker/lib/states/stateManager.js, line 220 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1097#-MQwNV710ZfBeoIMw_vJ:-MQwXLcmDtCdrKNBnBYk:bn6uhxm) ([raw file](https://github.com/kube-hpc/hkube/blob/37a44e29bcfa77d9603dfc9aba358467c5b59ed7/core/worker/lib/states/stateManager.js#L220)):*
> this._forceStop = fals
True is the default I meant

**Review by NassiHarel — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1097)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
