### PR TITLE
support log message from debug algorithm

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1342)

### CODE REVIEW

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1342)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1342)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

*[a discussion](https://reviewable.io/reviews/kube-hpc/hkube/1342#-MfbuoR-DNnuXRRN1U75:-MfbuoR-DNnuXRRN1U76:b-jlcvgh) (no related file):*
blocked until nodejs wrapper is published

---

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1342)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

*[a discussion](https://reviewable.io/reviews/kube-hpc/hkube/1342#-MfbuoR-DNnuXRRN1U75:-Mfgdb3u5MRWv68e2vEI:b-896fix) (no related file):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

blocked until nodejs wrapper is published
</blockquote></details>

Done.

---

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1342#-:-MfgpJ5o9aKtOW7sMaBU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
