### PR TITLE
add optional api-server prefix

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1126)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1126)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/api-server/config/main/config.base.js, line 56 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1126#-MSSwSGuClOMUCGsgcaX:-MSSwSGv-QyVEDZBVt0x:b13ew0s) ([raw file](https://github.com/kube-hpc/hkube/blob/d8373d3ba911a46e76f52750f75ac8616703ee5f/core/api-server/config/main/config.base.js#L56)):*
> ```
>  path: process.env.BASE_URL_PATH? path.join(config.ingressPrefix, process.env.BASE_URL_PATH): config.ingressPrefix
> ```

Writing this is the same?
`path: path.join(config.ingressPrefix, process.env.BASE_URL_PATH || '')`

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1126)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/config/main/config.base.js, line 56 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1126#-MSSwSGuClOMUCGsgcaX:-MSaof0-1bDjZV8tLlM7:bw46rz0) ([raw file](https://github.com/kube-hpc/hkube/blob/d8373d3ba911a46e76f52750f75ac8616703ee5f/core/api-server/config/main/config.base.js#L56)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  path: process.env.BASE_URL_PATH? path.join(config.ingressPrefix, process.env.BASE_URL_PATH): config.ingressPrefix
> ```

Writing this is the same?
`path: path.join(config.ingressPrefix, process.env.BASE_URL_PATH || '')`

</blockquote></details>

if both ingressPath and BASE_URL are empty your option returns `.` and not empty string. Added tests to verify

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1126#-:-MSh7PRk8im31lErdYuS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/api-server/config/main/config.base.js, line 56 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1126#-MSSwSGuClOMUCGsgcaX:-MSh7EspCFmPt-tJBHf-:b-76t1gs) ([raw file](https://github.com/kube-hpc/hkube/blob/d8373d3ba911a46e76f52750f75ac8616703ee5f/core/api-server/config/main/config.base.js#L56)):*
> ```
>  path.join
> ```

Yes
"If the joined path string is a zero-length string then '.' will be returned, representing the current working directory."

https://nodejs.org/api/path.html#path_path_join_paths

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1126)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/config/main/config.base.js, line 56 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1126#-MSSwSGuClOMUCGsgcaX:-MShBpjm0n2qqywkfzgS:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/d8373d3ba911a46e76f52750f75ac8616703ee5f/core/api-server/config/main/config.base.js#L56)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  path.join
> ```

Yes
"If the joined path string is a zero-length string then '.' will be returned, representing the current working directory."

https://nodejs.org/api/path.html#path_path_join_paths
</blockquote></details>

Done.

**Pull request merged**
