### PR TITLE
feat: graceful-shutdown

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1470)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
Test in the CI are failing

> Reviewed 10 of 10 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1470#-:-Mqx3_Ck0Ns9w_xPX1oz:bb5uqpr)* status: all files reviewed, 6 unresolved discussions (waiting on @NassiHarel)

___
*[core/algorithm-operator/config/main/config.base.js, line 50 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MqwzGun8tYjD0tVoLxk:-MqwzGun8tYjD0tVoLxl:b2j2vox) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/algorithm-operator/config/main/config.base.js#L50)):*
> ```JavaScript
>     maxDiff: process.env.HEALTHCHECK_MAX_DIFF || '30000',
>     logExternalRequests: formatter.parseBool(process.env.LOG_EXTERNAL_REQUESTS, true),
>     enabled: formatter.parseBool(process.env.HEALTHCHECK_ENABLE, true)
> ```

is this used?
___
*[core/pipeline-driver/lib/tasks/task-runner.js, line 207 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MqwxiVl9RmiB4Ol67RD:-MqwxiVl9RmiB4Ol67RE:b2xsp4j) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/pipeline-driver/lib/tasks/task-runner.js#L207)):*
> ```JavaScript
> 
>         await this._progressStatus({ status: DriverStates.ACTIVE });
>         await this._stateManager.setJobStatus({ jobId: this._jobId, queueTime: pipeline.startTime, startTime: Date.now() },);
> ```

We agreed to remove the setJobStatus that caused a race condition with the etcd transactions
___
*[core/pipeline-driver/lib/tasks/task-runner.js, line 276 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MqwxXhbDdI_MPulD1BL:-MqwxXhbDdI_MPulD1BM:b2xsp4j) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/pipeline-driver/lib/tasks/task-runner.js#L276)):*
> ```JavaScript
>         }
>         await this._progressStatus({ status, error, nodeName });
>         await this._stateManager.setJobStatus({ jobId: this._jobId }, true);
> ```

We agreed to remove the setJobStatus that caused a race condition with the etcd transactions
___
*[core/pipeline-driver-queue/bootstrap.js, line 26 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MqwxrUX-AGeXutG8kIx:-MqwxrUX-AGeXutG8kIy:bf1nbs0) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/pipeline-driver-queue/bootstrap.js#L26)):*
> ```JavaScript
>             monitor.on('close', (data) => {
>                 log.error(data.error.message, { component });
>                 process.exit(1);
> ```

doesn't the pipeline-driver-queue need graceful shutdown to save its persistency?
___
*[core/pipeline-driver-queue/lib/queue-runner.js, line 29 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-Mqx-V4T6jvvh7UzaRGD:-Mqx-V4T6jvvh7UzaRGE:bdx7jt7) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/pipeline-driver-queue/lib/queue-runner.js#L29)):*
> ```JavaScript
>         this.queue.on(queueEvents.POP, job => this._jobRemoved(job));
>         this.queue.on(queueEvents.REMOVE, job => this._jobRemoved(job));
>         // await this.queue.persistencyLoad();
> ```

No need to load the persistency? how will it recover itself incase of a crash?
___
*[core/pipeline-driver-queue/lib/jobs/consumer.js, line 37 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-Mqx1s3ABM809GKmQIVa:-Mqx1s3BDcoybF8ZydNY:b-xutm3i) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/pipeline-driver-queue/lib/jobs/consumer.js#L37)):*
> ```JavaScript
>     }
> 
>     async _handleJob(job) {
> ```

What will happen if this throws? Just unhandledRejection and exit?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1470)* status: all files reviewed, 6 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-operator/config/main/config.base.js, line 50 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MqwzGun8tYjD0tVoLxk:-MqxicZu3kO5yuCMP8ru:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/algorithm-operator/config/main/config.base.js#L50)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

is this used?
</blockquote></details>

Done.
___
*[core/pipeline-driver/lib/tasks/task-runner.js, line 207 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MqwxiVl9RmiB4Ol67RD:-Mqxim919BffChK7AoBt:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/pipeline-driver/lib/tasks/task-runner.js#L207)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

We agreed to remove the setJobStatus that caused a race condition with the etcd transactions
</blockquote></details>

Done.
___
*[core/pipeline-driver/lib/tasks/task-runner.js, line 276 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MqwxXhbDdI_MPulD1BL:-Mqxir3XAr92Uvv7kBBQ:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/pipeline-driver/lib/tasks/task-runner.js#L276)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

We agreed to remove the setJobStatus that caused a race condition with the etcd transactions
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/bootstrap.js, line 26 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MqwxrUX-AGeXutG8kIx:-Mqxj49E62kFa3a9QkRD:b-tkgypc) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/pipeline-driver-queue/bootstrap.js#L26)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

doesn't the pipeline-driver-queue need graceful shutdown to save its persistency?
</blockquote></details>

The persistency is done using `redis`, so....
___
*[core/pipeline-driver-queue/lib/queue-runner.js, line 29 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-Mqx-V4T6jvvh7UzaRGD:-MqxjO9cBZUShe8cXgGy:b-8122a8) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/pipeline-driver-queue/lib/queue-runner.js#L29)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

No need to load the persistency? how will it recover itself incase of a crash?
</blockquote></details>

we will call `job.done` only after finishing with the job (dequeue)
so in case of failure, we will auto recover jobs from `bull` (redis)
___
*[core/pipeline-driver-queue/lib/jobs/consumer.js, line 37 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1470#-Mqx1s3ABM809GKmQIVa:-MqxkFxE1kSUzfUlxb4J:b2nhswy) ([raw file](https://github.com/kube-hpc/hkube/blob/bb20f03221be935749f6d199cc93be24de55a8f9/core/pipeline-driver-queue/lib/jobs/consumer.js#L37)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

What will happen if this throws? Just unhandledRejection and exit? 
</blockquote></details>

Yes

**Review by yehiyam — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1470)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1470)* status: all files reviewed, 5 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/package.json, line 10 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1470#-Mrvf8H87s2AjFd4bEWv:-Mrvf8H87s2AjFd4bEWw:b-5bsfab) ([raw file](https://github.com/kube-hpc/hkube/blob/ec8b051a7f0b6b8f6057d56515950046bab5b26d/core/api-server/package.json#L10)):*
> ```JSON
>         "@hkube/consts": "^1.0.22",
>         "@hkube/dag": "^2.0.0",
>         "@hkube/etcd": "^5.0.38",
> ```

the downgrade from v5.0.38 isn't important here?
___
*[core/api-server/package.json, line 10 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MrvfPeDBLD8ErULVNFQ:-MrvfPeDBLD8ErULVNFR:b6e49i7) ([raw file](https://github.com/kube-hpc/hkube/blob/bc47a93e744aeb738483ad76ee703bd7431d6e26/core/api-server/package.json#L10)):*
> ```JSON
>         "@hkube/consts": "^1.0.22",
>         "@hkube/dag": "^2.0.0",
>         "@hkube/etcd": "^5.0.37-active-a",
> ```

Did you create a tag `5.0.37-active-a` in the etcd package repo?
___
*[core/pipeline-driver-queue/config/main/config.base.js, line 24 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MrvihBH06JHpduOJqjv:-MrvihBH06JHpduOJqjw:blwrc1c) ([raw file](https://github.com/kube-hpc/hkube/blob/bc47a93e744aeb738483ad76ee703bd7431d6e26/core/pipeline-driver-queue/config/main/config.base.js#L24)):*
> ```JavaScript
>     jobType: 'pipeline-job',
>     concurrency: 10000,
>     maxStalledCount: 3
> ```

What will happen when the limit is reached?
___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 88 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MrvkWyGAm6HirOK7qLt:-MrvkWyGAm6HirOK7qLu:bmy63p2) ([raw file](https://github.com/kube-hpc/hkube/blob/bc47a93e744aeb738483ad76ee703bd7431d6e26/core/pipeline-driver-queue/lib/jobs/producer.js#L88)):*
> ```JavaScript
>             const pipelinesNames = Object.keys(groupQueue);
>             const storedPipelines = await persistence.getStoredPipelines({ pipelinesNames });
>             const pipelines = storedPipelines.filter(p => p.options && p.options.concurrentPipelines.amount);
> ```

this is not 0 by default. Maybe it is better to check if `rejectOnFailure` is false



_Code quote:_
```JavaScript
p.options.concurrentPipelines.amount
```
___
*[core/pipeline-driver-queue/tests/test.js, line 14 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MrvlvLc1zU7UfUI_25t:-MrvlvLc1zU7UfUI_25u:b1c1k3w) ([raw file](https://github.com/kube-hpc/hkube/blob/bc47a93e744aeb738483ad76ee703bd7431d6e26/core/pipeline-driver-queue/tests/test.js#L14)):*
> ```JavaScript
> const queueRunner = require('../lib/queue-runner');
> const persistence = require('../lib/persistency/persistence');
> const setting = { prefix: 'pipeline-driver-queue' }
> ```

Is it possible to add some tests for the new functionality?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1470)* status: 19 of 35 files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/api-server/package.json, line 10 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MrvfPeDBLD8ErULVNFQ:-Ms00jov8ecxi9EhVWyc:b-ad29rj) ([raw file](https://github.com/kube-hpc/hkube/blob/bc47a93e744aeb738483ad76ee703bd7431d6e26/core/api-server/package.json#L10)):*
> 5.0.37-active-a
I created a new package `5.0.38-active-a` and pushed the tags to git, please confirm.
___
*[core/pipeline-driver-queue/config/main/config.base.js, line 24 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MrvihBH06JHpduOJqjv:-Ms00zu547vmLHAWktHg:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/bc47a93e744aeb738483ad76ee703bd7431d6e26/core/pipeline-driver-queue/config/main/config.base.js#L24)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

What will happen when the limit is reached?
</blockquote></details>

Done.
___
*[core/pipeline-driver-queue/tests/test.js, line 14 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MrvlvLc1zU7UfUI_25t:-Ms05rnA9Qr_q7Sz_RMt:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/bc47a93e744aeb738483ad76ee703bd7431d6e26/core/pipeline-driver-queue/tests/test.js#L14)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Is it possible to add some tests for the new functionality?
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 14 of 16 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1470)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel)

___
*[core/pipeline-driver/lib/consumer/jobs-consumer.js, line 67 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1470#-Ms0WUsY06LiMo2T6JsS:-Ms0WUsY06LiMo2T6JsT:br31a6o) ([raw file](https://github.com/kube-hpc/hkube/blob/13a23e8c1e9a93e68eb14c3edb6235a11073f325/core/pipeline-driver/lib/consumer/jobs-consumer.js#L67)):*
> ```JavaScript
>         this._inactiveTimer = setTimeout(() => {
>             log.info(`driver is inactive for more than ${this._formatSec()}`, { component });
>             if (this._taskRunner && !this._taskRunner._active) {
> ```

how is this going to be active?

**Review by yehiyam — COMMENTED** [review]
> Reviewed 3 of 5 files at r8, 1 of 2 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1470)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel)

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1470)* status: all files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/package.json, line 10 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1470#-Mrvf8H87s2AjFd4bEWv:-Ms4sYauBWo4eEKkWsmS:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ec8b051a7f0b6b8f6057d56515950046bab5b26d/core/api-server/package.json#L10)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

the downgrade from v5.0.38 isn't important here?
</blockquote></details>

Done.
___
*[core/pipeline-driver/lib/consumer/jobs-consumer.js, line 67 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1470#-Ms0WUsY06LiMo2T6JsS:-Ms4seR96yVpqr9i_ve8:b-a88uxg) ([raw file](https://github.com/kube-hpc/hkube/blob/13a23e8c1e9a93e68eb14c3edb6235a11073f325/core/pipeline-driver/lib/consumer/jobs-consumer.js#L67)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

how is this going to be active?
</blockquote></details>

The `task-executor` can send `stop` while the driver is working
___
*[core/pipeline-driver-queue/lib/jobs/producer.js, line 88 at r4](https://reviewable.io/reviews/kube-hpc/hkube/1470#-MrvkWyGAm6HirOK7qLt:-Ms4s9Gh3tm5R-44-Ex7:bc3p00w) ([raw file](https://github.com/kube-hpc/hkube/blob/bc47a93e744aeb738483ad76ee703bd7431d6e26/core/pipeline-driver-queue/lib/jobs/producer.js#L88)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

this is not 0 by default. Maybe it is better to check if `rejectOnFailure` is false
</blockquote></details>

I filtering only the stored pipelines that have amount > 0

**Review by yehiyam — APPROVED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1470)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Pull request merged**
