### PR TITLE
add more logs

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1361)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1361)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/pipeline-driver/lib/producer/jobs-producer.js, line 77 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1361#-Mgf3vkl6n9OOZLudZey:-Mgf3vkl6n9OOZLudZez:b-vh879k) ([raw file](https://github.com/kube-hpc/hkube/blob/963cdc60b0f6b9d73e9eb7395610bef3df16efb2/core/pipeline-driver/lib/producer/jobs-producer.js#L77)):*
> ```JavaScript
>             };
>             if (this._queueLogging.tasks) {
>                 tasks.forEach(t => log.info(`task ${t.taskId} created`, { component, jobId, taskId: t.taskId, algorithmName: options.node.algorithmName }));
> ```

Do you really want to log a large batch? for example 5000 tasks
___
*[core/worker/lib/code-api/algorithm-execution/algorithm-execution.js, line 204 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1361#-Mgf61219JDHaagYAFrd:-Mgf61219JDHaagYAFre:b-cfcg33) ([raw file](https://github.com/kube-hpc/hkube/blob/963cdc60b0f6b9d73e9eb7395610bef3df16efb2/core/worker/lib/code-api/algorithm-execution/algorithm-execution.js#L204)):*
> ```JavaScript
>             const taskId = producer.createTaskID();
>             log.info(`startAlgorithmExecution for ${algorithmName} with ${taskId}`, { component });
>             this._executions.set(taskId, { taskId, execId, includeResult });
> ```

I think that if the worker is down, all the tasks are lost for good. that is one issue.
second, I think that we need to update the driver for each task creation, so we could do`/graph/{jobId}`
and get a clear image of our algorithms created by the code-api.

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1361)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/pipeline-driver/lib/producer/jobs-producer.js, line 77 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1361#-Mgf3vkl6n9OOZLudZey:-MgfADgX51-72Fau814k:bhmepy) ([raw file](https://github.com/kube-hpc/hkube/blob/963cdc60b0f6b9d73e9eb7395610bef3df16efb2/core/pipeline-driver/lib/producer/jobs-producer.js#L77)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Do you really want to log a large batch? for example 5000 tasks
</blockquote></details>

yes. It can be switched off, but if there is a problem we need to see all of the logs
___
*[core/worker/lib/code-api/algorithm-execution/algorithm-execution.js, line 204 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1361#-Mgf61219JDHaagYAFrd:-MgirsDv0JKJKAqPoh_t:birlkqb) ([raw file](https://github.com/kube-hpc/hkube/blob/963cdc60b0f6b9d73e9eb7395610bef3df16efb2/core/worker/lib/code-api/algorithm-execution/algorithm-execution.js#L204)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I think that if the worker is down, all the tasks are lost for good. that is one issue.
second, I think that we need to update the driver for each task creation, so we could do`/graph/{jobId}`
and get a clear image of our algorithms created by the code-api.
</blockquote></details>

If the worker is down then the tasks are irrelevant. If there is a retry then all of the tasks will be recreated.
Doesn't the driver update the graph?

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1361)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/worker/lib/code-api/algorithm-execution/algorithm-execution.js, line 204 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1361#-Mgf61219JDHaagYAFrd:-MgpEDEs3I3AOIxCFwQk:b-qo4zjr) ([raw file](https://github.com/kube-hpc/hkube/blob/963cdc60b0f6b9d73e9eb7395610bef3df16efb2/core/worker/lib/code-api/algorithm-execution/algorithm-execution.js#L204)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

If the worker is down then the tasks are irrelevant. If there is a retry then all of the tasks will be recreated.
Doesn't the driver update the graph? 
</blockquote></details>

Now the worker writes 'creating' status when it creates the code-api algorithm. It will be added to the graph before the algorithm is running

**Review by NassiHarel — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1361#-:-MgpgTzp8DJ1jYQr_zZq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
