### PR TITLE
Pdq-fixes

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1549)

### CODE REVIEW

**Review by golanha — DISMISSED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1549#-:-MxnNTgJEztvFDKDzuld:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Review by golanha — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1549#-:-MxnjMqA2lhPuCvbeO2x:bnfp4nl)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @golanha)

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1549)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[core/pipeline-driver-queue/package.json, line 3 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1549#-MxoQpWA-9g7sPDUvmHJ:-MxoQpWA-9g7sPDUvmHK:bgd52zf) ([raw file](https://github.com/kube-hpc/hkube/blob/15dfbe451c732b94f468b0a82d05e8cdb896895d/core/pipeline-driver-queue/package.json#L3)):*
> ```JSON
> {
>   "name": "pipeline-driver-queue",
>   "version": "2.3.1-aaa",
> ```

version  2.3.1-aaa

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1549)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[core/pipeline-driver-queue/package.json, line 3 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1549#-MxoQpWA-9g7sPDUvmHJ:-MxoRmjL8yog3VllO1Fi:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/15dfbe451c732b94f468b0a82d05e8cdb896895d/core/pipeline-driver-queue/package.json#L3)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

version  2.3.1-aaa
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1549#-:-MxoS1fXEYrC1lJUH0pK:bnfp4nl)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @golanha)

**Review by golanha — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1549#-:-MxoS3QW2SwLsp1oOIkw:bnfp4nl)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @golanha)

**Review by golanha — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1549#-:-MxoS6C3D04ulv1UD4z3:bnfp4nl)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
