### PR TITLE
Update producer consumer version

### PR DESCRIPTION
**Pull request by Adir111**
Updated package.json dependencies - @hkube/producer-consumer version updated.
Issue: kube-HPC/hkube#1737

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1948)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1948)* status: all files reviewed, 1 unresolved discussion (waiting on @Adir111)

*[a discussion](https://reviewable.io/reviews/kube-HPC/hkube/1948#-O07norg23uPDW9jxddD:-O07norg23uPDW9jxddE:b-mmeqne) (no related file):*
You need to update the generated  package.json.lock file with the new version of producer-consumer

___

**Review by Adir111 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1948)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @golanha)

*[a discussion](https://reviewable.io/reviews/kube-HPC/hkube/1948#-O07norg23uPDW9jxddD:-O0s6THM6_euVNTs81Wl:bb6un1j) (no related file):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

You need to update the generated  package.json.lock file with the new version of producer-consumer
</blockquote></details>

Done

___

**Comment by Adir111** [comment]
> > Reviewed 2 of 2 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1948)_ status: all files reviewed, 1 unresolved discussion (waiting on @Adir111)
> 
> _[a discussion](https://reviewable.io/reviews/kube-HPC/hkube/1948#-O07norg23uPDW9jxddD:-O07norg23uPDW9jxddE:b-mmeqne) (no related file):_ You need to update the generated package.json.lock file with the new version of producer-consumer

Done.

**Review by golanha — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1948)* status: all files reviewed, 1 unresolved discussion (waiting on @Adir111)

**Review by golanha — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1948)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Adir111)

**Pull request merged**
