### PR TITLE
Updated States, and reorganised file for better readability

### PR DESCRIPTION
**Pull request by Adir111**
Update `States` Type in `job-schema` and File Reorganisation

Updated the `States` type in `job-schema` to include the `FailedScheduling` property for UI purposes.
Additionally, reorganised the file to improve structure and readability.

Issue: kube-HPC/hkube#1961

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1964)

### CODE REVIEW

**Comment by Adir111** [comment]
Tested in dev environment to check if the property is defined.

**Review by golanha — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1964)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Adir111 and @RonShvarz)

___
*[`core/api-server/api/graphql/schemas/job-schema.js` line 130 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1964#-O2tESZm6ZmNz8Jcm_vn:-O2tESZm6ZmNz8Jcm_vo:bimo0dg) ([raw file](https://github.com/kube-HPC/hkube/blob/406d781cad8071c387300059c30da95262e51d03/core/api-server/api/graphql/schemas/job-schema.js#L130)):*
> ```JavaScript
>     stalled: Int
>     warning: Int
>     FailedScheduling: Int
> ```

Should be lower case



_Code quote:_
```JavaScript
FailedSchedulin
```

**Review by golanha — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1964)* status: all files reviewed, 1 unresolved discussion (waiting on @Adir111 and @RonShvarz)

**Review by golanha — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1964#-:-O37O_Xm8BAW6uOPPjfd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Adir111 and @RonShvarz)

**Review by Adir111 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1964)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`core/api-server/api/graphql/schemas/job-schema.js` line 130 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1964#-O2tESZm6ZmNz8Jcm_vn:-O37QP0_4DZ81FyKjL9D:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/406d781cad8071c387300059c30da95262e51d03/core/api-server/api/graphql/schemas/job-schema.js#L130)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Should be lower case
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1964)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Adir111)

**Review by golanha — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1964#-:-O37Xe43CcO2nPcylel2:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Adir111)

**Pull request merged**
