### PR TITLE
queues snapshot

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1387)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 19 of 22 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1387)* status: 20 of 24 files reviewed, 7 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-operator/lib/deployments/algorithm-queue.js, line 60 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJMYKh1R-tHrT10oDB:-MhJMYKh1R-tHrT10oDC:b-cuxqed) ([raw file](https://github.com/kube-hpc/hkube/blob/c510e9b6a059ee4288d33ae2a457a74902594822/core/algorithm-operator/lib/deployments/algorithm-queue.js#L60)):*
> ```JavaScript
>     spec = applyJaeger(spec, CONTAINERS.ALGORITHM_QUEUE, options);
>     spec = applyNodeSelector(spec, clusterOptions);
>     spec = applyStorage(spec, options.defaultStorage, CONTAINERS.PIPELINE_DRIVER, 'algorithm-operator-configmap');
> ```

pipeline-driver? shouldn't it be algorithm-queue?
___
*[core/algorithm-queue/processed.txt, line 1 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJJUJZ8UEDqwfmf2Fi:-MhJJUJZ8UEDqwfmf2Fj:b-7ilvym) ([raw file](https://github.com/kube-hpc/hkube/blob/08adc30e06073e4d69b0f7691dbcd740b61a8021/core/algorithm-queue/processed.txt#L1)):*
> ```help
> Statistical profiling result from isolate-0x6184770-19866-v8.log, (15921 ticks, 10408 unaccounted, 0 excluded).
> ```

no need to commit this
___
*[core/algorithm-queue/config/main/config.base.js, line 69 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJJaFr7RhfD3CGCWW8:-MhJJaFr7RhfD3CGCWW9:b-3l9n09) ([raw file](https://github.com/kube-hpc/hkube/blob/08adc30e06073e4d69b0f7691dbcd740b61a8021/core/algorithm-queue/config/main/config.base.js#L69)):*
> ```JavaScript
>     [heuristicsNames.ENTRANCE_TIME]: 0.2,
>     [heuristicsNames.BATCH]: 0.2,
>     // [heuristicsNames.CURRENT_BATCH_PLACE]: 0.1
> ```

why did you change that?
___
*[core/algorithm-queue/lib/queue.js, line 183 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJMjl42RmEsGvElELM:-MhJMjl42RmEsGvElELN:b-8942yb) ([raw file](https://github.com/kube-hpc/hkube/blob/136461bfab15ef04be32fd24a45ca2c2810ee5a7/core/algorithm-queue/lib/queue.js#L183)):*
> ```JavaScript
> 
>     _orderQueue() {
>         this.queue = orderBy(this.queue, j => j.calculated.score, 'desc');
> ```

the `calculated` was never used?
___
*[core/algorithm-queue/lib/queue.js, line 211 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJR8JJEf9CKE-sBbcO:-MhJR8JJEf9CKE-sBbcP:bfcm7qw) ([raw file](https://github.com/kube-hpc/hkube/blob/136461bfab15ef04be32fd24a45ca2c2810ee5a7/core/algorithm-queue/lib/queue.js#L211)):*
> ```JavaScript
>         }
>         const pendingAmount = await this._producer.getWaitingCount();
>         this.enrichmentRunner(this.queue);
> ```

not needed?
___
*[core/algorithm-queue/lib/queue-runner.js, line 34 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJRAgVCsnUFsXGHalT:-MhJRAgVCsnUFsXGHalU:bs2xlqx) ([raw file](https://github.com/kube-hpc/hkube/blob/136461bfab15ef04be32fd24a45ca2c2810ee5a7/core/algorithm-queue/lib/queue-runner.js#L34)):*
> ```JavaScript
> 
>     _taskRemoved(task) {
>         aggregationMetricFactory.getMetric(metricsName.TIME_IN_QUEUE)(task, metricsTypes.HISTOGRAM_OPERATION.end);
> ```

did you. move the prometheus metrics someplace else?
___
*[core/resource-manager/lib/store/algorithms-flat/store.js, line 9 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJMMx_7UabOJOd7_st:-MhJMMxaBmd8teeaUILs:b-gfk9nl) ([raw file](https://github.com/kube-hpc/hkube/blob/08adc30e06073e4d69b0f7691dbcd740b61a8021/core/resource-manager/lib/store/algorithms-flat/store.js#L9)):*
> ```JavaScript
>     async setData(data) {
>         this._log(data);
>         // do we want to limit our scoring array?
> ```

I think we can do it because the task executor will cut it anyway

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1387)* status: 5 of 25 files reviewed, 7 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-operator/lib/deployments/algorithm-queue.js, line 60 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJMYKh1R-tHrT10oDB:-MhODGwz8FqWpXi-_dC5:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/c510e9b6a059ee4288d33ae2a457a74902594822/core/algorithm-operator/lib/deployments/algorithm-queue.js#L60)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

pipeline-driver? shouldn't it be algorithm-queue?
</blockquote></details>

Done.
___
*[core/algorithm-queue/config/main/config.base.js, line 69 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJJaFr7RhfD3CGCWW8:-MhODIgcEryVKRDkoYMd:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/08adc30e06073e4d69b0f7691dbcd740b61a8021/core/algorithm-queue/config/main/config.base.js#L69)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why did you change that?
</blockquote></details>

Done.
___
*[core/algorithm-queue/lib/queue.js, line 183 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJMjl42RmEsGvElELM:-MhODJyq3mBuljyOyYsO:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/136461bfab15ef04be32fd24a45ca2c2810ee5a7/core/algorithm-queue/lib/queue.js#L183)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

the `calculated` was never used?
</blockquote></details>

Done.
___
*[core/algorithm-queue/lib/queue.js, line 211 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJR8JJEf9CKE-sBbcO:-MhODKq_EilgYVoguaet:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/136461bfab15ef04be32fd24a45ca2c2810ee5a7/core/algorithm-queue/lib/queue.js#L211)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

not needed?
</blockquote></details>

Done.
___
*[core/algorithm-queue/lib/queue-runner.js, line 34 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJRAgVCsnUFsXGHalT:-MhODMZqByjm8WnOKgQ2:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/136461bfab15ef04be32fd24a45ca2c2810ee5a7/core/algorithm-queue/lib/queue-runner.js#L34)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

did you. move the prometheus metrics someplace else?
</blockquote></details>

Done.
___
*[core/algorithm-queue/processed.txt, line 1 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJJUJZ8UEDqwfmf2Fi:-MhODNAyDASDG4m_95XJ:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/08adc30e06073e4d69b0f7691dbcd740b61a8021/core/algorithm-queue/processed.txt#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

no need to commit this
</blockquote></details>

Done.
___
*[core/resource-manager/lib/store/algorithms-flat/store.js, line 9 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MhJMMx_7UabOJOd7_st:-MhODPMG43RtL62zjEql:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/08adc30e06073e4d69b0f7691dbcd740b61a8021/core/resource-manager/lib/store/algorithms-flat/store.js#L9)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I think we can do it because the task executor will cut it anyway
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1, 1 of 1 files at r4, 13 of 18 files at r5, 3 of 10 files at r7, 25 of 27 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/algorithm-queue/lib/persistency/snapshot.js, line 10 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MiRPkSVCZZILqm6GhjC:-MiRPkSWEmE2SY215mon:bfbjhem) ([raw file](https://github.com/kube-hpc/hkube/blob/d9c4654cbb0a5b6e1b0f16c931a2de8db1f3ebac/core/algorithm-queue/lib/persistency/snapshot.js#L10)):*
> ```JavaScript
>             const start = now();
>             onStart({ key, length: data.length });
>             await storageManager.hkubePersistency.put({ type: TYPE, name: key, data });
> ```

you need to add volume and volumeMount to the algorithm-queue (in code) and pipeline-driver-queue (in helm)

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1387)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/algorithm-queue/lib/persistency/snapshot.js, line 10 at r9](https://reviewable.io/reviews/kube-hpc/hkube/1387#-MiRPkSVCZZILqm6GhjC:-MiVEr5J0qoSE2-WLAfm:b-g0cwo3) ([raw file](https://github.com/kube-hpc/hkube/blob/cd9a7f132074830443e9cc341039cd120f7d61c7/core/algorithm-queue/lib/persistency/snapshot.js#L10)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

you need to add volume and volumeMount to the algorithm-queue (in code) and pipeline-driver-queue (in helm)
</blockquote></details>

Already did :)

**Pull request merged**
