### PR TITLE
add algorithm memory as environment variable

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 241 at r1](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ1dHFvEt4zH-tLHBAd:-MJ1dHFvEt4zH-tLHBAe:b-ikuwll) ([raw file](https://github.com/kube-hpc/hkube/blob/9957c0a80e93370a86fe639e92f131fb396acc51/core/task-executor/lib/jobs/jobCreator.js#L241)):*
> ```JavaScript
>     spec = applyWorkerImage(spec, workerImage);
>     spec = applyEnvToContainer(spec, CONTAINERS.ALGORITHM, algorithmEnv);
>     spec = applyEnvToContainer(spec, CONTAINERS.ALGORITHM, { 'ALGORITHM_MEMORY': resourceRequests.requests.memory })
> ```

There is no need for ' '

**Review by yehiyam — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 241 at r1](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ1dHFvEt4zH-tLHBAd:-MJ1pRSx9EHCk44y1T_a:b-gnjtxc) ([raw file](https://github.com/kube-hpc/hkube/blob/9957c0a80e93370a86fe639e92f131fb396acc51/core/task-executor/lib/jobs/jobCreator.js#L241)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

There is no need for ' '
</blockquote></details>

The `resourceRequests.requests.memory` value is a string with the units, e.g. '2Gi'. Make sure to parse is correctly

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 241 at r1](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ1dHFvEt4zH-tLHBAd:-MJ2EEsD74jXA03QzV6E:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/9957c0a80e93370a86fe639e92f131fb396acc51/core/task-executor/lib/jobs/jobCreator.js#L241)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

The `resourceRequests.requests.memory` value is a string with the units, e.g. '2Gi'. Make sure to parse is correctly 
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-builder/environments/java/runJava.sh, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ60fMs8Icqv7CM3auZ:-MJ60fMtC4bxgvNuFzw1:b-cl7wdz) ([raw file](https://github.com/kube-hpc/hkube/blob/b4dbeb29865e38f5de28a291643ced51084030d9/core/algorithm-builder/environments/java/runJava.sh#L1)):*
> ```Shell
> ALGORITHM_MEMORY=${ALGORITHM_MEMORY/Ki/K}
> ```

I think it is better to do it in javascript in the task-executor, even if it is strictly for JAVA today
___
*[core/algorithm-builder/environments/java/runJava.sh, line 13 at r3](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ5ymIM7MClVV-Lqsq2:-MJ5ymIM7MClVV-Lqsq3:bf9c0q9) ([raw file](https://github.com/kube-hpc/hkube/blob/b4dbeb29865e38f5de28a291643ced51084030d9/core/algorithm-builder/environments/java/runJava.sh#L13)):*
> ```
> 7 / 4)
> ```
why 7/4? 
___
*[core/algorithm-builder/environments/java/runJava.sh, line 23 at r3](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ5yTxJ5QnPfnPUTvMF:-MJ5yTxJ5QnPfnPUTvMG:b8vczbv) ([raw file](https://github.com/kube-hpc/hkube/blob/b4dbeb29865e38f5de28a291643ced51084030d9/core/algorithm-builder/environments/java/runJava.sh#L23)):*
> ```Shell
>   MIN_MEM="${JAVA_MIN_MEM}"
> fi
> ```

This code is not consistant
for 512Mi I get min=256M max=896G
for 1Gi I get min=0G max=1G

**Review by NassiHarel — CHANGES_REQUESTED** [review]
<deleted>

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @golanha)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 241 at r3](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ66kODA5_3cKAG8X_Y:-MJ66kODA5_3cKAG8X_Z:be7e8gs) ([raw file](https://github.com/kube-hpc/hkube/blob/b4dbeb29865e38f5de28a291643ced51084030d9/core/task-executor/lib/jobs/jobCreator.js#L241)):*
> ```
> spec = applyEnvToContainer(spec, CONTAINERS.ALGORITHM, { ALGORITHM_MEMORY: resourceRequests.requests.memory })
> ```

Why not pass the original `memory` to this function, this will always be in `int` (MB).
spec = applyEnvToContainer(spec, CONTAINERS.ALGORITHM, { ALGORITHM_MEMORY: memory })

and then do in `runJava.sh` something like:
MIN_MEM="${ALGORITHM_MEMORY}m"
MAX_MEM="${ALGORITHM_MEMORY}m"

That's it, 3 lines of code...

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @golanha)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 287 at r4](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ7aChx6YkzSf9zKAWi:-MJ7aChy0YbBshe_Ixob:b-5sq048) ([raw file](https://github.com/kube-hpc/hkube/blob/b35118d44fa7e9c5d8c4fb2464aa9297311b8f25/core/task-executor/lib/jobs/jobCreator.js#L287)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> const getJavaMaxMem = (memory) => {
>     const { val, unit } = parse.parseUnitObj(memory);
>     javaValue = Math.round(val * 0.8)
>     javaMemUnit = unit[0]
>     if (unit in ['P', 'Pi']) {
>         javaValue = javaValue * 1000
>         javaMemUnit = 'T'
>     }
>     if (unit in ['E', 'Ei']) {
>         javaValue = javaValue * 1000 * 1000
>         javaMemUnit = 'T'
>     }
>     return javaValue + javaMemUnit;
> }
> ```
</details>


WTF?
You can't use just one unit? Megabyte? (`M`)

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @golanha)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 224 at r4](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJLMUjf3Db2INIaceHv:-MJLMUjf3Db2INIaceHw:b-f6bs4e) ([raw file](https://github.com/kube-hpc/hkube/blob/b35118d44fa7e9c5d8c4fb2464aa9297311b8f25/core/task-executor/lib/jobs/jobCreator.js#L224)):*
> ```
> env
> ```
where is this set? 
___
*[core/task-executor/lib/jobs/jobCreator.js, line 241 at r4](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJLMa160KL6mHcGjB2p:-MJLMa160KL6mHcGjB2q:bym1ifa) ([raw file](https://github.com/kube-hpc/hkube/blob/b35118d44fa7e9c5d8c4fb2464aa9297311b8f25/core/task-executor/lib/jobs/jobCreator.js#L241)):*
> ```
> 'java'
> ```
Use a const
___
*[core/task-executor/lib/jobs/jobCreator.js, line 290 at r4](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJLNkrt4Od7nvjyYIp_:-MJLNkrt4Od7nvjyYIpa:b-wegv5e) ([raw file](https://github.com/kube-hpc/hkube/blob/b35118d44fa7e9c5d8c4fb2464aa9297311b8f25/core/task-executor/lib/jobs/jobCreator.js#L290)):*
> ```JavaScript
>     javaValue = Math.round(val * 0.8)
>     javaMemUnit = unit[0]
>     if (unit in ['P', 'Pi']) {
> ```

This is not python :-)
`The in operator returns true if the specified property is in the specified object or its prototype chain`
I also agree with @nassiharel. use `parse.getMemoryInMi` and use megabytes only

**Review by yehiyam — COMMENTED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: all files reviewed, 7 unresolved discussions (waiting on @golanha)

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/algorithm-builder/environments/java/runJava.sh, line 1 at r3](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ60fMs8Icqv7CM3auZ:-MJM1GGZAbW9RH_7JV4y:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b4dbeb29865e38f5de28a291643ced51084030d9/core/algorithm-builder/environments/java/runJava.sh#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I think it is better to do it in javascript in the task-executor, even if it is strictly for JAVA today
</blockquote></details>

Done.
___
*[core/algorithm-builder/environments/java/runJava.sh, line 13 at r3](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ5ymIM7MClVV-Lqsq2:-MJM1GyD5SCQz2VToJq3:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b4dbeb29865e38f5de28a291643ced51084030d9/core/algorithm-builder/environments/java/runJava.sh#L13)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> 7 / 4)
> ```
why 7/4? 
</blockquote></details>

Done.
___
*[core/algorithm-builder/environments/java/runJava.sh, line 23 at r3](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ5yTxJ5QnPfnPUTvMF:-MJM1IWZBTpOAty3Y3qx:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b4dbeb29865e38f5de28a291643ced51084030d9/core/algorithm-builder/environments/java/runJava.sh#L23)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This code is not consistant
for 512Mi I get min=256M max=896G
for 1Gi I get min=0G max=1G

</blockquote></details>

Done.
___
*[core/task-executor/lib/jobs/jobCreator.js, line 224 at r4](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJLMUjf3Db2INIaceHv:-MJRBo2T10sP4BL2mzEx:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b35118d44fa7e9c5d8c4fb2464aa9297311b8f25/core/task-executor/lib/jobs/jobCreator.js#L224)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> env
> ```
where is this set? 
</blockquote></details>

Done.
___
*[core/task-executor/lib/jobs/jobCreator.js, line 241 at r4](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJLMa160KL6mHcGjB2p:-MJRYx895C4g6TQ0IbG_:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b35118d44fa7e9c5d8c4fb2464aa9297311b8f25/core/task-executor/lib/jobs/jobCreator.js#L241)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> 'java'
> ```
Use a const
</blockquote></details>

Done.
___
*[core/task-executor/lib/jobs/jobCreator.js, line 287 at r4](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJ7aChx6YkzSf9zKAWi:-MJRZJCL4dk2vi2H41nA:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b35118d44fa7e9c5d8c4fb2464aa9297311b8f25/core/task-executor/lib/jobs/jobCreator.js#L287)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const getJavaMaxMem = (memory) => {
>     const { val, unit } = parse.parseUnitObj(memory);
>     javaValue = Math.round(val * 0.8)
>     javaMemUnit = unit[0]
>     if (unit in ['P', 'Pi']) {
>         javaValue = javaValue * 1000
>         javaMemUnit = 'T'
>     }
>     if (unit in ['E', 'Ei']) {
>         javaValue = javaValue * 1000 * 1000
>         javaMemUnit = 'T'
>     }
>     return javaValue + javaMemUnit;
> }
> ```

WTF?
You can't use just one unit? Megabyte? (`M`)

</blockquote></details>

Done.
___
*[core/task-executor/lib/jobs/jobCreator.js, line 289 at r4](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJM3F5O-2Lj5kUJQvKB:-MJM3F5O-2Lj5kUJQvKC:b-szvloz) ([raw file](https://github.com/kube-hpc/hkube/blob/b35118d44fa7e9c5d8c4fb2464aa9297311b8f25/core/task-executor/lib/jobs/jobCreator.js#L289)):*
> ```
>     javaValue = Math.round(val * 0.8)
>     javaMemUnit = unit[0]
> ```
___
*[core/task-executor/lib/jobs/jobCreator.js, line 290 at r4](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJLNkrt4Od7nvjyYIp_:-MJRZkQM6IZAGkOfojaW:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/b35118d44fa7e9c5d8c4fb2464aa9297311b8f25/core/task-executor/lib/jobs/jobCreator.js#L290)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This is not python :-)
`The in operator returns true if the specified property is in the specified object or its prototype chain`
I also agree with @nassiharel. use `parse.getMemoryInMi` and use megabytes only
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
The build of the PR failed the linting stage.
Also, the code will not run because a file is missing

> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963#-:-MJSB7xY5cMhjG0Ii5Xc:b-vcv333)* status: all files reviewed, 8 unresolved discussions (waiting on @golanha, @NassiHarel, and @yehiyam)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 5 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJS96W848aMT5F1fQIa:-MJS96W848aMT5F1fQIb:b-84h8oh) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/lib/jobs/jobCreator.js#L5)):*
> ```JavaScript
> const log = require('@hkube/logger').GetLogFromContainer();
> const objectPath = require('object-path');
> const { JAVA } = require('../consts/envs')
> ```

File is missing
___
*[core/task-executor/lib/jobs/jobCreator.js, line 242 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJSARIB1O8S0r3e8q-e:-MJSARIB1O8S0r3e8q-f:b-do1hzk) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/lib/jobs/jobCreator.js#L242)):*
> ```JavaScript
>     spec = applyWorkerImage(spec, workerImage);
>     spec = applyEnvToContainer(spec, CONTAINERS.ALGORITHM, algorithmEnv);
>     if (env == JAVA) {
> ```

===
also, this doesn't pass linting. you don't have the precommit hook set up?
___
*[core/task-executor/lib/jobs/jobCreator.js, line 243 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJSAi3a8JhbM1k8cPFJ:-MJSAi3a8JhbM1k8cPFK:b71qc3i) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/lib/jobs/jobCreator.js#L243)):*
> ```JavaScript
>     spec = applyEnvToContainer(spec, CONTAINERS.ALGORITHM, algorithmEnv);
>     if (env == JAVA) {
>         spec = applyEnvToContainer(spec, CONTAINERS.ALGORITHM, { JAVA_DERIVED_MEMORY: getJavaMaxMem(resourceRequests.limits.memory) })
> ```

'getJavaMaxMem' was used before it was defined.
again - linting
___
*[core/task-executor/lib/jobs/jobCreator.js, line 289 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJSAtZZC3Gu0quyoxP2:-MJSAtZZC3Gu0quyoxP3:b-lnha4o) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/lib/jobs/jobCreator.js#L289)):*
> ```JavaScript
> const getJavaMaxMem = (memory) => {
>     const val = parse.getMemoryInMi(memory);
>     javaValue = Math.round(val * 0.8)
> ```

javaValue is not defined ( this is not python :-) )
___
*[core/task-executor/tests/reconcilerTests.js, line 387 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJS9ANCBqcWEeip38hW:-MJS9ANCBqcWEeip38hX:b-hrjl4a) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/tests/reconcilerTests.js#L387)):*
> ```JavaScript
>             expect(callCount('createJob')[0][0].spec.spec.template.spec.containers[1].image).to.eql('hkube/algorithm-example');
>         });
>         it('should work with env', async () => {
> ```

You didn't change the name of the test

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: 2 of 6 files reviewed, 8 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 5 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJS96W848aMT5F1fQIa:-MJSOZVu1eJ5ZE7EpPMc:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/lib/jobs/jobCreator.js#L5)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

File is missing
</blockquote></details>

Done.
___
*[core/task-executor/lib/jobs/jobCreator.js, line 242 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJSARIB1O8S0r3e8q-e:-MJSOgWU4uvOLZIBJc2c:b-ewe4jp) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/lib/jobs/jobCreator.js#L242)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

===
also, this doesn't pass linting. you don't have the precommit hook set up?
</blockquote></details>

Had a problem with node version, so i bypassed hooks. Sorry about that.
___
*[core/task-executor/lib/jobs/jobCreator.js, line 243 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJSAi3a8JhbM1k8cPFJ:-MJSSsu71LO9-QlqxUzQ:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/lib/jobs/jobCreator.js#L243)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

'getJavaMaxMem' was used before it was defined.
again - linting
</blockquote></details>

Done.
___
*[core/task-executor/lib/jobs/jobCreator.js, line 289 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJSAtZZC3Gu0quyoxP2:-MJSSvrW9WH5c4gEpqT3:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/lib/jobs/jobCreator.js#L289)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

javaValue is not defined ( this is not python :-) )
</blockquote></details>

Done.
___
*[core/task-executor/tests/reconcilerTests.js, line 387 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJS9ANCBqcWEeip38hW:-MJSV6g-7BCSuGv124dN:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/tests/reconcilerTests.js#L387)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

You didn't change the name of the test
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/963)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/task-executor/tests/jobCreatorTests.js, line 182 at r5](https://reviewable.io/reviews/kube-hpc/hkube/963#-MJVNABk8yxykK6XF4qa:-MJVNABk8yxykK6XF4qb:bcqha8a) ([raw file](https://github.com/kube-hpc/hkube/blob/ab51639813c915fcca9bf271f3e55ffd0afa82c2/core/task-executor/tests/jobCreatorTests.js#L182)):*
> ```JavaScript
>             expect(res.spec.template.spec.containers[1].env).to.deep.include({ name: 'JAVA_DERIVED_MEMORY', value: '160' })
>         });
>         it('should apply java memory G', () => {
> ```

You should leave the test (just fix the expect). You should test also with units other than Mi

**Pull request merged**
