### PR TITLE
fix log redirect command

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1584)

### CODE REVIEW

**Review by golanha — COMMENTED** [review]
Why did you need to fix the log log redirect?

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1584#-:-N0e6-uXD1MkUqTTXhO2:b-11qxm1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Review by yehiyam — COMMENTED** [review]
see https://github.com/kube-HPC/hkube/issues/1297
changed the way logs are redirected to file to help with stuck algorithm after seg-fault

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1584#-:-N0iqn9xEA1FNu3oUmmG:b-5g35hs)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Review by golanha — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1584)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
