### PR TITLE
handle large queue size when persisting to redis

### PR DESCRIPTION
**Pull request by yehiyam**
handle etcd unhandled rejections
fix deployment selector for algorithm-queue

---
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/907)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 2 files at r5, 4 of 4 files at r6, 22 of 24 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/907)* status: all files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-queue/lib/persistency/persistence.js, line 35 at r8](https://reviewable.io/reviews/kube-hpc/hkube/907#-MFUPTN06OvOQ7GESuRr:-MFUPTN06OvOQ7GESuRs:b-1xsoku) ([raw file](https://github.com/kube-hpc/hkube/blob/8890e9f4407fb40ea7094bf50a73bd22c22622e2/core/algorithm-queue/lib/persistency/persistence.js#L35)):*
> ```JavaScript
>         }
>         catch (error) {
>             log.error(`failed to store persistency ${error.message}`, { component: components.ETCD_PERSISTENT }, error);
> ```

use log.throttle
___
*[core/algorithm-queue/lib/persistency/redis-storage-adapter.js, line 44 at r8](https://reviewable.io/reviews/kube-hpc/hkube/907#-MFUQ6lp8feGmmNGo0vQ:-MFUQ6lp8feGmmNGo0vR:b-aayfgx) ([raw file](https://github.com/kube-hpc/hkube/blob/8890e9f4407fb40ea7094bf50a73bd22c22622e2/core/algorithm-queue/lib/persistency/redis-storage-adapter.js#L44)):*
> ```JavaScript
>         const size = jsonArray.reduce((prev, cur) => prev + cur.length, 0);
>         if (this._maxPersistencySize && size > this._maxPersistencySize) {
>             log.warning(`persistency length is ${size} which is larger than ${this._maxPersistencySize}`, { component: components.ETCD_PERSISTENT });
> ```

throttle
___
*[core/algorithm-queue/lib/persistency/redis-storage-adapter.js, line 48 at r8](https://reviewable.io/reviews/kube-hpc/hkube/907#-MFVIcbw2b3Jt4yVF-dz:-MFVIcbx2EcxR2VZMfjt:bylmnnd) ([raw file](https://github.com/kube-hpc/hkube/blob/8890e9f4407fb40ea7094bf50a73bd22c22622e2/core/algorithm-queue/lib/persistency/redis-storage-adapter.js#L48)):*
> ```JavaScript
>         }
>         for (const json of jsonArray) {
>             await this._clientAsync.rpush(this.path, json);
> ```

single rpush

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/907)* status: 30 of 33 files reviewed, 3 unresolved discussions (waiting on @NassiHarel)

___
*[core/algorithm-queue/lib/persistency/persistence.js, line 35 at r8](https://reviewable.io/reviews/kube-hpc/hkube/907#-MFUPTN06OvOQ7GESuRr:-MFVJxrC4lUvxove6g3c:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/8890e9f4407fb40ea7094bf50a73bd22c22622e2/core/algorithm-queue/lib/persistency/persistence.js#L35)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

use log.throttle
</blockquote></details>

Done.
___
*[core/algorithm-queue/lib/persistency/redis-storage-adapter.js, line 44 at r8](https://reviewable.io/reviews/kube-hpc/hkube/907#-MFUQ6lp8feGmmNGo0vQ:-MFVK0KmB68Dv-YTbAnV:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/8890e9f4407fb40ea7094bf50a73bd22c22622e2/core/algorithm-queue/lib/persistency/redis-storage-adapter.js#L44)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

throttle
</blockquote></details>

Done.
___
*[core/algorithm-queue/lib/persistency/redis-storage-adapter.js, line 48 at r8](https://reviewable.io/reviews/kube-hpc/hkube/907#-MFVIcbw2b3Jt4yVF-dz:-MFVK0evB8AhxKOThyWN:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/8890e9f4407fb40ea7094bf50a73bd22c22622e2/core/algorithm-queue/lib/persistency/redis-storage-adapter.js#L48)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

single rpush
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/907#-:-MFVKQRN5O_xLjP15-XX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
