### PR TITLE
Added error or warning facilitation for unscheduled algs.

### PR DESCRIPTION
**Pull request by RonShvarz**
kube-HPC/hkube#1638

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1734)

### CODE REVIEW

**Comment by RonShvarz** [comment]
Error or warning distinction, format fixes, node graph object updates concerning batch use-case.

**Comment by RonShvarz** [comment]
Error or warning distinction, format fixes, node graph object updates concerning batch use-case.

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1734)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @RonShvarz)

___
*[`core/pipeline-driver/lib/datastore/graph-store.js` line 128 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1734#-NX5U18B9zgDAxILnpAt:-NX5U18B9zgDAxILnpAu:b-dn3dd4) ([raw file](https://github.com/kube-HPC/hkube/blob/a7e4c39f4d6d05d4e0487ea25719f66078563c41/core/pipeline-driver/lib/datastore/graph-store.js#L128)):*
> ```JavaScript
> 
>     _handleBatch(n) {
>         const isAnyBatchFailed = n.batch.any(b => b.status === 'FailedScheduling');
> ```

anyFailedScheduling



_Code quote:_
```JavaScript
isAnyBatchFailed 
```
___
*[`core/pipeline-driver/lib/state/state-manager.js` line 121 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1734#-NX5Utpk0jRSWgzqpgh8:-NX5Utpk0jRSWgzqpgh9:bbsa8nw) ([raw file](https://github.com/kube-HPC/hkube/blob/a7e4c39f4d6d05d4e0487ea25719f66078563c41/core/pipeline-driver/lib/state/state-manager.js#L121)):*
> ```JavaScript
>                 if (resources && resources[0] && resources[0].unScheduledAlgorithms) {
>                     const algorithms = { ...resources[0].unScheduledAlgorithms, ...resources[0].ignoredUnscheduledAlgorithms };
>                     const nodesFromEtcd = resources[0].nodes;
> ```

clusterNodes



_Code quote:_
```JavaScript
nodesFromEtcd
```
___
*[`core/pipeline-driver/lib/tasks/task-runner.js` line 123 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1734#-NX5W1n29epqqCevtKOe:-NX5W1n29epqqCevtKOf:b-29ho76) ([raw file](https://github.com/kube-HPC/hkube/blob/a7e4c39f4d6d05d4e0487ea25719f66078563c41/core/pipeline-driver/lib/tasks/task-runner.js#L123)):*
> ```JavaScript
>             n.status = event.reason;
>             n.warnings = n.warnings || [];
>             const { resourceMessage, isError } = this._nodeResourceMessageBuilder(event, nodesFromEtcd);
> ```

buildNodeRe....



_Code quote:_
```JavaScript
_nodeResourceMessageBuilder
```
___
*[`core/pipeline-driver/lib/tasks/task-runner.js` line 156 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1734#-NX5W9yK6kRosfOroYfo:-NX5W9yK6kRosfOroYfp:bwzxjb5) ([raw file](https://github.com/kube-HPC/hkube/blob/a7e4c39f4d6d05d4e0487ea25719f66078563c41/core/pipeline-driver/lib/tasks/task-runner.js#L156)):*
> ```JavaScript
>             else {
>                 resourceMessage += `${unScheduledAlg.complexResourceDescriptor.numUnmatchedNodesBySelector} nodes don't match node selector: '${selectors}',\n`;
>                 ({ resourceMessage, isError } = this._specificNodesResourceMessageBuilder(unScheduledAlg, resourceMessage, isError, nodesFromEtcd));
> ```

buildSpecif....



_Code quote:_
```JavaScript
specificNodesResourceMessageBuilde
```

**Review by golanha — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1734)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @RonShvarz)

___
*[`core/pipeline-driver/lib/tasks/task-runner.js` line 191 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1734#-NX5cYxm0N7PYTYEbBDA:-NX5cYxm0N7PYTYEbBDB:b-1p4yge) ([raw file](https://github.com/kube-HPC/hkube/blob/a7e4c39f4d6d05d4e0487ea25719f66078563c41/core/pipeline-driver/lib/tasks/task-runner.js#L191)):*
> ```JavaScript
>                     resourceMessage += `${k} ,\n`;
>                     const currentValue = resourceIdentifier.get(k);
>                     resourceIdentifier.set(k, currentValue + 1);
> ```

BreachCountPerResource



_Code quote:_
```JavaScript
resourceIdentifier
```

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1734)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @golanha)

___
*[`core/pipeline-driver/lib/datastore/graph-store.js` line 128 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1734#-NX5U18B9zgDAxILnpAt:-NX5fBED3c7XzVOvyft0:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/a7e4c39f4d6d05d4e0487ea25719f66078563c41/core/pipeline-driver/lib/datastore/graph-store.js#L128)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

anyFailedScheduling
</blockquote></details>

Done.
___
*[`core/pipeline-driver/lib/state/state-manager.js` line 121 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1734#-NX5Utpk0jRSWgzqpgh8:-NX5fCKj1eABP8P5oyuF:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/a7e4c39f4d6d05d4e0487ea25719f66078563c41/core/pipeline-driver/lib/state/state-manager.js#L121)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

clusterNodes
</blockquote></details>

Done.
___
*[`core/pipeline-driver/lib/tasks/task-runner.js` line 123 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1734#-NX5W1n29epqqCevtKOe:-NX5ezLYEb5sS7lOYFym:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/a7e4c39f4d6d05d4e0487ea25719f66078563c41/core/pipeline-driver/lib/tasks/task-runner.js#L123)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

buildNodeRe....
</blockquote></details>

Done.
___
*[`core/pipeline-driver/lib/tasks/task-runner.js` line 156 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1734#-NX5W9yK6kRosfOroYfo:-NX5ewli16KTrdUNNzkQ:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/a7e4c39f4d6d05d4e0487ea25719f66078563c41/core/pipeline-driver/lib/tasks/task-runner.js#L156)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

buildSpecif....
</blockquote></details>

Done.
___
*[`core/pipeline-driver/lib/tasks/task-runner.js` line 191 at r5](https://reviewable.io/reviews/kube-HPC/hkube/1734#-NX5cYxm0N7PYTYEbBDA:-NX5fACp-yiTLbqfslv6:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/a7e4c39f4d6d05d4e0487ea25719f66078563c41/core/pipeline-driver/lib/tasks/task-runner.js#L191)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

BreachCountPerResource
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> Reviewed 2 of 6 files at r3, 3 of 4 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1734)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RonShvarz)

**Pull request merged**
