### PR TITLE
Delete folder on job end and change paths to dvc directories

### PR DESCRIPTION
**Pull request by awesomecakex**
changed the way dvc directories are handeled within the datasources-storage volume 
the git-repositories for upload are now save in 'git-repositories/{repo name}/complete
the path to the dvc directory of a given datasources is 'datasources-storage/datasources-in-use/{dsName}
and within this directory there will be a folder named 'complete' where the full version of the datasource the user chose to use is and all the snapshots he is using are under files labeled by the snapshot name.

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1776)

### CODE REVIEW

**Comment by awesomecakex** [comment]
#1777

**Review by golanha — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @awesomecakex)

**Pull request merged**
