### PR TITLE
Autoscaler stateless count changes

### PR DESCRIPTION
**Pull request by RonShvarz**
- Handle min and max auto-scaling limits, including logs throttling ( process.env.SCALE_INTERVENTION_LOG_THROTTLE_TIME )

- Updated graph schema
- Added pipeline store validation for stateless count.

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1783)

### CODE REVIEW

**Comment by RonShvarz** [comment]
kube-HPC/hkube#1765

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1783)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @golanha)

___
*[`core/worker/config/main/config.base.js` line 47 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1783#-NcRD_Z2-5F4XiHc5KpI:-NcROQnDCx7dqItg-l68:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/6068f9d5b994c555675d7bd46ed90deafd2e016a/core/worker/config/main/config.base.js#L47)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

scaleIntervention
</blockquote></details>

Done.
___
*[`core/worker/lib/streaming/services/auto-scaler.js` line 220 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1783#-NcREHpD-yvnc0EkU6Ls:-NcRONqg0Rpwt0_k0ulG:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/6068f9d5b994c555675d7bd46ed90deafd2e016a/core/worker/lib/streaming/services/auto-scaler.js#L220)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

remove todo
</blockquote></details>

Done.
___
*[`core/worker/lib/streaming/services/auto-scaler.js` line 379 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1783#-NcRE3We9nRFIogCcbn0:-NcROOoU80GrHPLNulNH:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/6068f9d5b994c555675d7bd46ed90deafd2e016a/core/worker/lib/streaming/services/auto-scaler.js#L379)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`core/worker/test/streaming.js` line 387 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1783#-NcREe9f5KdVPLi9nLie:-NcRORus1fnRQDamRlET:bb6un1j) ([raw file](https://github.com/kube-HPC/hkube/blob/6068f9d5b994c555675d7bd46ed90deafd2e016a/core/worker/test/streaming.js#L387)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Test is excluded
</blockquote></details>

Done

**Review by golanha — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1783#-:-Nc_wQ5K0XFz7ck_SPyA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @RonShvarz)

**Pull request merged**
