### PR TITLE
Upload data source mid pipeline

### PR DESCRIPTION
**Pull request by awesomecakex**
adding the ability to updated a datasource version mid pipeline

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1785)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1785)* status: all files reviewed, 5 unresolved discussions (waiting on @awesomecakex)

___
*[`core/datasources-service/lib/service/dataSource.js` line 209 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1785#-NfKJ-5zEsJ9wu7Mx2fS:-NfKJ-5zEsJ9wu7Mx2fT:bo0yi12) ([raw file](https://github.com/kube-HPC/hkube/blob/e18f798f9f18e88a998b275be7121d268f061a06/core/datasources-service/lib/service/dataSource.js#L209)):*
> ```JavaScript
>     }
> 
>     async dvcYamlObj(directory) {
> ```

filePath



_Code quote:_
```JavaScript
directory)
```
___
*[`core/datasources-service/lib/service/dataSource.js` line 209 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1785#-NfKJ8J4-qofNw3pahWh:-NfKJ8J4-qofNw3pahWi:blv4pud) ([raw file](https://github.com/kube-HPC/hkube/blob/e18f798f9f18e88a998b275be7121d268f061a06/core/datasources-service/lib/service/dataSource.js#L209)):*
> ```JavaScript
>     }
> 
>     async dvcYamlObj(directory) {
> ```

getDvcFileAsYaml



_Code quote:_
```JavaScript
 dvcYamlObj(
```
___
*[`core/datasources-service/lib/service/dataSource.js` line 248 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1785#-NfKLavy1Asxj86TRYWn:-NfKLavy1Asxj86TRYWo:b-7rwlzd) ([raw file](https://github.com/kube-HPC/hkube/blob/e18f798f9f18e88a998b275be7121d268f061a06/core/datasources-service/lib/service/dataSource.js#L248)):*
> ```JavaScript
>     async commitJobDs({ repository, versionDescription }) {
>         await this.handleUntrackedFiles(repository, repository.cwd);
>         // const commit = await repository.commitMidPipeline(versionDescription);
> ```

remove remark



_Code quote:_
```JavaScript
 // const commit = await repository.commitMidPipeline(versionDescription);
```
___
*[`core/datasources-service/lib/service/dataSource.js` line 298 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1785#-NfK1YF9Ae4j7tpE91Nt:-NfK1YF9Ae4j7tpE91Nu:b2ni2sk) ([raw file](https://github.com/kube-HPC/hkube/blob/e18f798f9f18e88a998b275be7121d268f061a06/core/datasources-service/lib/service/dataSource.js#L298)):*
> ```JavaScript
>         }
>         else {
>             throw new ActionNotAllowed('Mid pipeline saving is an action reserved to working on latest version of a DataSource');
> ```

for



_Code quote:_
```JavaScript
to
```
___
*[`core/datasources-service/lib/utils/Repository.js` line 129 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1785#-NfKLFCNCsmgbTQn57RB:-NfKLFCNCsmgbTQn57RC:bdext98) ([raw file](https://github.com/kube-HPC/hkube/blob/e18f798f9f18e88a998b275be7121d268f061a06/core/datasources-service/lib/utils/Repository.js#L129)):*
> ```JavaScript
>         const { commit } = await this.gitClient.commit(commitMessage);
>         return commit;
>     }
> ```

Couldn't find where is this in use.commitMidPipeline



_Code quote:_
```JavaScript
    async commitMidPipeline(commitMessage) {
        try {
            await this.gitClient.add('./data/');
        }
        catch (error) {
            return error;
        }
        const { commit } = await this.gitClient.commit(commitMessage);
        return commit;
    }
```

**Review by awesomecakex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1785)* status: all files reviewed, 5 unresolved discussions (waiting on @golanha)

___
*[`core/datasources-service/lib/service/dataSource.js` line 209 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1785#-NfKJ8J4-qofNw3pahWh:-NfKRKpHD1wbGCaRRoHn:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/e18f798f9f18e88a998b275be7121d268f061a06/core/datasources-service/lib/service/dataSource.js#L209)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

getDvcFileAsYaml
</blockquote></details>

Done.
___
*[`core/datasources-service/lib/service/dataSource.js` line 209 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1785#-NfKJ-5zEsJ9wu7Mx2fS:-NfKT0u17dPy9BGNXwjv:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/e18f798f9f18e88a998b275be7121d268f061a06/core/datasources-service/lib/service/dataSource.js#L209)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

filePath
</blockquote></details>

Done.
___
*[`core/datasources-service/lib/service/dataSource.js` line 248 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1785#-NfKLavy1Asxj86TRYWn:-NfKQzoO9dZ5RtbhchKi:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/e18f798f9f18e88a998b275be7121d268f061a06/core/datasources-service/lib/service/dataSource.js#L248)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

remove remark
</blockquote></details>

Done.
___
*[`core/datasources-service/lib/service/dataSource.js` line 298 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1785#-NfK1YF9Ae4j7tpE91Nt:-NfKR5jd8O46GqmynQd6:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/e18f798f9f18e88a998b275be7121d268f061a06/core/datasources-service/lib/service/dataSource.js#L298)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

for
</blockquote></details>

Done.
___
*[`core/datasources-service/lib/utils/Repository.js` line 129 at r1](https://reviewable.io/reviews/kube-HPC/hkube/1785#-NfKLFCNCsmgbTQn57RB:-NfKR6kI7R-CVSJdnreG:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/e18f798f9f18e88a998b275be7121d268f061a06/core/datasources-service/lib/utils/Repository.js#L129)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Couldn't find where is this in use.commitMidPipeline
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1785)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @awesomecakex)

**Review by golanha — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/1785)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @awesomecakex)

**Pull request merged**
