### PR TITLE
Pipeline drivers scale

### PR DESCRIPTION
**Pull request by NassiHarel**
- [x] phase 1 - make driver handle multiple jobs
- [x] phase 2 - the driver will decide when it's ready to go down
- [x] phase 3 - algorithm-operator will handle the scale
- [x] phase 4 - update helm envs
- [ ] phase 5 - update UI
- [x] phase 6 - deploy and test

---
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1259)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 11 of 28 files at r1, 1 of 1 files at r2, 47 of 55 files at r5, 9 of 9 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1259)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/algorithm-operator/lib/reconcile/createOptions.js, line 13 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1259#-MaSIEig9BGC68gvIyFL:-MaSIEig9BGC68gvIyFM:b76kb0p) ([raw file](https://github.com/kube-hpc/hkube/blob/dd234ba0a981fc1cddc2c241b3159ee09bb3c2d7/core/algorithm-operator/lib/reconcile/createOptions.js#L13)):*
> ```JavaScript
>     const cpuFactored = (cpu || 0.1) * factor;
>     const memory = `${(mem || 4) * factor}Mi`;
>     const gpus = gpu ? { [gpuVendors.NVIDIA]: gpu } : null;
> ```

I don't think the pipeline-driver needs GPU :-)
___
*[core/algorithm-operator/lib/reconcile/createOptions.js, line 19 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1259#-MaSIxz1EvQoiuGuVG0q:-MaSIxz1EvQoiuGuVG0r:bo4ezee) ([raw file](https://github.com/kube-hpc/hkube/blob/dd234ba0a981fc1cddc2c241b3159ee09bb3c2d7/core/algorithm-operator/lib/reconcile/createOptions.js#L19)):*
> ```JavaScript
> const createContainerResource = (template) => {
>     const requests = _createContainerResourceByFactor(template || {}, 1);
>     const limitFactor = settings.useResourceLimits ? 1 : 2;
> ```

you are missing the useResourceLimits setting
https://github.com/kube-HPC/hkube/blob/878b249e37d778ea18dd74d9460f84754c8cd0a5/core/task-executor/lib/helpers/settings.js#L4

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1259)* status: 66 of 69 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/algorithm-operator/lib/reconcile/createOptions.js, line 13 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1259#-MaSIEig9BGC68gvIyFL:-MaTHuG09VS__dwHTgy3:b-ghc21f) ([raw file](https://github.com/kube-hpc/hkube/blob/dd234ba0a981fc1cddc2c241b3159ee09bb3c2d7/core/algorithm-operator/lib/reconcile/createOptions.js#L13)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I don't think the pipeline-driver needs GPU :-)
</blockquote></details>

Done.

Anyway, I forgot to add the const `gpuVendors`  :-)
___
*[core/algorithm-operator/lib/reconcile/createOptions.js, line 19 at r6](https://reviewable.io/reviews/kube-hpc/hkube/1259#-MaSIxz1EvQoiuGuVG0q:-MaTKHhE7MuId0r55npx:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/dd234ba0a981fc1cddc2c241b3159ee09bb3c2d7/core/algorithm-operator/lib/reconcile/createOptions.js#L19)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

you are missing the useResourceLimits setting
https://github.com/kube-HPC/hkube/blob/878b249e37d778ea18dd74d9460f84754c8cd0a5/core/task-executor/lib/helpers/settings.js#L4
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Pull request merged**
