### PR TITLE
feat: add reservedMemory

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1197)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1197)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/api-server/config/main/config.base.js, line 14 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1197#-MW3pSkQ8cXp5ebjm-bh:-MW3pSkQ8cXp5ebjm-bi:bxvn4g8) ([raw file](https://github.com/kube-hpc/hkube/blob/ef2570ba1ddc52ff077230a4c56a223b2c55e1a3/core/api-server/config/main/config.base.js#L14)):*
> ```
> DEFAULT_ALGORITHM_RESERVED_MEMORY
> ```
DEFAULT_ALGORITHM_RESERVED_MEMORY_RATIO?

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1197)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/lib/service/algorithms.js, line 186 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1197#-MW3psin19rqfM2mvPRd:-MW3psin19rqfM2mvPRe:b-85u6lp) ([raw file](https://github.com/kube-hpc/hkube/blob/ef2570ba1ddc52ff077230a4c56a223b2c55e1a3/core/api-server/lib/service/algorithms.js#L186)):*
> ```JavaScript
>         if (!newAlgorithm.reservedMemory) {
>             const mem = unitsConverter.getMemoryInMi(newAlgorithm.mem);
>             const reservedMemory = mem * this._defaultAlgorithmReservedMemory;
> ```

round to closest Mi? Even to closest 10Mi

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1197)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/config/main/config.base.js, line 14 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1197#-MW3pSkQ8cXp5ebjm-bh:-MW3ybwH3wvGwvJVeQpS:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ef2570ba1ddc52ff077230a4c56a223b2c55e1a3/core/api-server/config/main/config.base.js#L14)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> DEFAULT_ALGORITHM_RESERVED_MEMORY
> ```
DEFAULT_ALGORITHM_RESERVED_MEMORY_RATIO?
</blockquote></details>

Done.
___
*[core/api-server/lib/service/algorithms.js, line 186 at r1](https://reviewable.io/reviews/kube-hpc/hkube/1197#-MW3psin19rqfM2mvPRd:-MW3ye2yEbtofIB5k8ov:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/ef2570ba1ddc52ff077230a4c56a223b2c55e1a3/core/api-server/lib/service/algorithms.js#L186)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

round to closest Mi? Even to closest 10Mi
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1197#-:-MW42Z6PEAFH-kiWnJK-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Pull request merged**
