### PR TITLE
Algorithm queue balancer

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1251)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1251)* status: all files reviewed, 4 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-queue/lib/persistency/etcd.js, line 10 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1251#-M_PjB1C43Q0450d6zQQ:-M_QQv8o2Pk74pli-4N1:b-d12s6c) ([raw file](https://github.com/kube-hpc/hkube/blob/9b7306da9c21541eef972b31d8ac3076a9e47bbd/core/algorithm-queue/lib/persistency/etcd.js#L10)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

why? performance issues?
</blockquote></details>

it's one less promise.

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1251)* status: 38 of 42 files reviewed, 4 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[core/algorithm-operator/lib/reconcile/algorithm-queue.js, line 110 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1251#-M_KuLMw0pY5eYzE4UHz:-M_Vr1dJB3xIVEHQwciL:b-osgmfb) ([raw file](https://github.com/kube-hpc/hkube/blob/9b7306da9c21541eef972b31d8ac3076a9e47bbd/core/algorithm-operator/lib/reconcile/algorithm-queue.js#L110)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This is not going to change. Why not validate it one time and exit the process?
</blockquote></details>

I think the original idea was to allow defining invalid limit for "tests reasons"
___
*[core/algorithm-operator/lib/reconcile/algorithm-queue.js, line 131 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1251#-M_KtJbHCkm8QR6-ELvz:-M_VsxhV9pM-U0jF2Yh0:b-70aiw8) ([raw file](https://github.com/kube-hpc/hkube/blob/9b7306da9c21541eef972b31d8ac3076a9e47bbd/core/algorithm-operator/lib/reconcile/algorithm-queue.js#L131)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

`reconcile` and `reconcileDevMode` are almost the same. The only difference is the reconcile has a few more steps. Maybe combine them with a flag?
</blockquote></details>

Yes, I considered that... Done.
___
*[core/algorithm-queue/lib/jobs/consumer.js, line 16 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1251#-M_PiVA8AwYD-MKW7n6d:-M_VtIma-6ZL_WBsYgjE:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/9b7306da9c21541eef972b31d8ac3076a9e47bbd/core/algorithm-queue/lib/jobs/consumer.js#L16)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> _getWaitingCount 
> ```
not used
</blockquote></details>

Done.
___
*[core/algorithm-queue/lib/persistency/etcd.js, line 10 at r7](https://reviewable.io/reviews/kube-hpc/hkube/1251#-M_PjB1C43Q0450d6zQQ:-M_VtOHy-kGy1DN-FrSl:b-ds0l3l) ([raw file](https://github.com/kube-hpc/hkube/blob/9b7306da9c21541eef972b31d8ac3076a9e47bbd/core/algorithm-queue/lib/persistency/etcd.js#L10)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

it's one less promise.
</blockquote></details>

Maybe... the drawback is you don't know if this method is async or not

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1251)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @NassiHarel)

___
*[core/algorithm-operator/lib/reconcile/algorithm-queue.js, line 118 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1251#-M_Vx3KI9nuYXGINwXsV:-M_Vx3KJ6O1yAQbRVDnY:b-4p12wu) ([raw file](https://github.com/kube-hpc/hkube/blob/168cec9d04a6cdf31a9e438d65f037ed118690d0/core/algorithm-operator/lib/reconcile/algorithm-queue.js#L118)):*
> ```JavaScript
>     const { algorithmsToQueue, queueToAlgorithms, duplicateAlgorithms } = normalizeQueuesDiscovery(discovery);
>     const normAlgorithms = normalizeAlgorithms(algorithms);
>     const normDeployments = normalizeQueuesDeployments(deployments);
> ```

can this line run in devMode? you didn't have this line in the original DevMode

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1251)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[core/algorithm-operator/lib/reconcile/algorithm-queue.js, line 118 at r8](https://reviewable.io/reviews/kube-hpc/hkube/1251#-M_Vx3KI9nuYXGINwXsV:-M_W1BZ-E8YXVnysLPJf:b-wtviob) ([raw file](https://github.com/kube-hpc/hkube/blob/168cec9d04a6cdf31a9e438d65f037ed118690d0/core/algorithm-operator/lib/reconcile/algorithm-queue.js#L118)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

can this line run in devMode? you didn't have this line in the original DevMode
</blockquote></details>

Yes, I had this line, with a minor change `duplicateAlgorithms`, this are the cons of duplicate code. now it's better

**Review by yehiyam — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1251#-:-M_ZPl4S1e5YC8jcWLJr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
