### PR TITLE
execute copy on docker

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1103)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1103)* status: all files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 8 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1103#-MRFHc_j5Fxm7xU7S8fM:-MRFHc_j5Fxm7xU7S8fN:byfzdvn) ([raw file](https://github.com/kube-hpc/hkube/blob/3d3b14d214820aefee7556abe416a33538ff26ea/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L8)):*
> ```
> //
> ```
double /

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1103)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate, line 8 at r3](https://reviewable.io/reviews/kube-hpc/hkube/1103#-MRFHc_j5Fxm7xU7S8fM:-MRFJpFyDbfFsy5YlFTv:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/3d3b14d214820aefee7556abe416a33538ff26ea/core/algorithm-builder/environments/java/dockerfile/DockerfileTemplate#L8)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> //
> ```
double /
</blockquote></details>

Done.

**Pull request merged**
