### PR TITLE
add emptyDir and configMap mounts

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1379)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1379#-:-MhNvesaAAWJmk51eDyy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 104 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1379#-MhO2HHi0eYHQ4jdFIuA:-MhO2HHi0eYHQ4jdFIuB:b-tge671) ([raw file](https://github.com/kube-hpc/hkube/blob/93d20e2bed6d1755f628070efe0f3806f26ca78e/core/task-executor/lib/jobs/jobCreator.js#L104)):*
> ```
>                 [volumes.configMap]: {
>                     name: m.pvcName
>                 }
> ```
This is mount to the entire config map?
How the user will use it? he need to have ConfigMap, right?
How can I mount to a specific entry in the ConfigMap?
```
configMap:
        name: name
        items:
          - key: key
            path: path
```

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1379)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[core/task-executor/lib/jobs/jobCreator.js, line 104 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1379#-MhO2HHi0eYHQ4jdFIuA:-MhOBDO02qNQ3_qcyCWh:b-b7az6v) ([raw file](https://github.com/kube-hpc/hkube/blob/93d20e2bed6d1755f628070efe0f3806f26ca78e/core/task-executor/lib/jobs/jobCreator.js#L104)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>                 [volumes.configMap]: {
>                     name: m.pvcName
>                 }
> ```
This is mount to the entire config map?
How the user will use it? he need to have ConfigMap, right?
How can I mount to a specific entry in the ConfigMap?
```
configMap:
        name: name
        items:
          - key: key
            path: path
```

</blockquote></details>

you can only mount the entire CM for now. Each key will be a file in the `path`

**Review by NassiHarel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1379)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
