### PR TITLE
update logger and config for fluentbit

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1403)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 99 of 101 files at r1, 11 of 12 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1403)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[core/openapi-spec/package.json, line 7 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1403#-MiFr8TX6BqO7jTVCffd:-MiFr8TX6BqO7jTVCffe:bdrfn0a) ([raw file](https://github.com/kube-hpc/hkube/blob/5a714db1ba4777cd3290538ef175f19c0eff954b/core/openapi-spec/package.json#L7)):*
> ```
> "@hkube/logger": "^2.0.1",
> ```
an auto script mistake?
___
*[core/worker/package.json, line 3 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1403#-MiFrG8R0XNYivM30jQX:-MiFrG8R0XNYivM30jQY:bg5wujh) ([raw file](https://github.com/kube-hpc/hkube/blob/5a714db1ba4777cd3290538ef175f19c0eff954b/core/worker/package.json#L3)):*
> ```
> "version": "2.1.10-b",
> ```
mistake?

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1403)* status: 110 of 115 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[core/worker/package.json, line 3 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1403#-MiFrG8R0XNYivM30jQX:-MiFun5b2bn7qXLturrp:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/5a714db1ba4777cd3290538ef175f19c0eff954b/core/worker/package.json#L3)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> "version": "2.1.10-b",
> ```
mistake?
</blockquote></details>

Done.
___
*[core/openapi-spec/package.json, line 7 at r5](https://reviewable.io/reviews/kube-hpc/hkube/1403#-MiFr8TX6BqO7jTVCffd:-MiFullQ0Y2RdJxpE0S7:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/5a714db1ba4777cd3290538ef175f19c0eff954b/core/openapi-spec/package.json#L7)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> "@hkube/logger": "^2.0.1",
> ```
an auto script mistake?
</blockquote></details>

Done.

**Review by NassiHarel — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 101 files at r1, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1403#-:-MiFxEXFBzIYnWW4s9_J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Review by NassiHarel — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
