### PR TITLE
custom worker resources from algorith spec

### PR DESCRIPTION
**Pull request by RonShvarz**
kube-HPC/hkube#2031

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/2037)

### CODE REVIEW

**Comment by RonShvarz** [comment]
Without workerCustomResources:
image

with workerCustomResources:
image

Must set in helm deployment:
.Values.task_executor.env.resources_enable = true
spec expects :
"workerCustomResources": {
        "limits": {
            "cpu": "X",
            "memory": "Y"
        },
        "requests": {
            "cpu": "Z",
            "memory": "W"
        }
    }
    in the algorithm template

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/2037)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @RonShvarz)

___
*[`core/openapi-spec/swagger/definitions/algorithms/algorithm.yaml` line 63 at r2](https://reviewable.io/reviews/kube-HPC/hkube/2037#-OE9BCWFCJXL6w0ohOBn:-OE9BCWFCJXL6w0ohOBo:b-gkth0s) ([raw file](https://github.com/kube-HPC/hkube/blob/4c8f8558fc712e16b833aa698dea5abaffbb6f88/core/openapi-spec/swagger/definitions/algorithms/algorithm.yaml#L63)):*
> ```YAML
>         required:
>           - cpu
>           - memory
> ```

I don't think we should make them both mandatory. If we just want to set a value to the memory this should be possible, and handled later on in task executor.



_Code quote:_
```YAML
          - cpu
          - memory
```
___
*[`core/task-executor/lib/jobs/jobCreator.js` line 383 at r2](https://reviewable.io/reviews/kube-HPC/hkube/2037#-OE9AgXB-DJrK8ZlnNQh:-OE9AgXCBa5_jn9xDwZ1:bjwvzu7) ([raw file](https://github.com/kube-HPC/hkube/blob/4c8f8558fc712e16b833aa698dea5abaffbb6f88/core/task-executor/lib/jobs/jobCreator.js#L383)):*
> ```JavaScript
>     spec = applyEnvToContainer(spec, CONTAINERS.WORKER, { WORKER_IMAGE: workerImage });
>     spec = applyAlgorithmResourceRequests(spec, resourceRequests, node);
>     if (settings.applyResources) {
> ```

In case worker setting are set in algorithm, values should be set no matter whats in applyResources.



_Code quote:_
```JavaScript
    if (settings.applyResources) {
```

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/2037)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[`core/openapi-spec/swagger/definitions/algorithms/algorithm.yaml` line 63 at r2](https://reviewable.io/reviews/kube-HPC/hkube/2037#-OE9BCWFCJXL6w0ohOBn:-OESk6A_1tpNTAwseQRY:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/4c8f8558fc712e16b833aa698dea5abaffbb6f88/core/openapi-spec/swagger/definitions/algorithms/algorithm.yaml#L63)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

I don't think we should make them both mandatory. If we just want to set a value to the memory this should be possible, and handled later on in task executor.
</blockquote></details>

Done.
___
*[`core/task-executor/lib/jobs/jobCreator.js` line 383 at r2](https://reviewable.io/reviews/kube-HPC/hkube/2037#-OE9AgXB-DJrK8ZlnNQh:-OESk8Li5rHfrz5dMp3j:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/4c8f8558fc712e16b833aa698dea5abaffbb6f88/core/task-executor/lib/jobs/jobCreator.js#L383)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

In case worker setting are set in algorithm, values should be set no matter whats in applyResources.
</blockquote></details>

Done.

**Comment by golanha** [comment]
*[`core/api-server/lib/service/algorithms.js` line 342 at r4](https://reviewable.io/reviews/kube-HPC/hkube/2037#-OESki_Y6w0PVswfWazg:-OESki_Z74SweIgrw30H:b-zaz3da) ([raw file](https://github.com/kube-HPC/hkube/blob/a54e99d70440cc3783941b07011e69d2fd1b2f51/core/api-server/lib/service/algorithms.js#L342)):*
> ```JavaScript
>         if ((resources.requests?.cpu && !resources.limits?.cpu) || (resources.limits?.cpu && !resources.requests?.cpu)) {
>             errors.push('If requests.cpu is defined, limits.cpu must also be defined, and vice versa');
>         }
> ```

give specific problem description limit/request



_Code quote:_
```JavaScript
        if ((resources.requests?.memory && !resources.limits?.memory) || (resources.limits?.memory && !resources.requests?.memory)) {
            errors.push('If requests.memory is defined, limits.memory must also be defined, and vice versa');
        }
        if ((resources.requests?.cpu && !resources.limits?.cpu) || (resources.limits?.cpu && !resources.requests?.cpu)) {
            errors.push('If requests.cpu is defined, limits.cpu must also be defined, and vice versa');
        }
```

**Review by golanha — COMMENTED** [review]
> Reviewed 3 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/2037)* status: 3 of 12 files reviewed, 1 unresolved discussion (waiting on @RonShvarz)

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/2037)* status: 3 of 12 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`core/api-server/lib/service/algorithms.js` line 342 at r4](https://reviewable.io/reviews/kube-HPC/hkube/2037#-OESki_Y6w0PVswfWazg:-OETJMD8AwOx6nmzva6S:b-896fix) ([raw file](https://github.com/kube-HPC/hkube/blob/a54e99d70440cc3783941b07011e69d2fd1b2f51/core/api-server/lib/service/algorithms.js#L342)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

give specific problem description limit/request
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 8 files at r2, 3 of 6 files at r3, 2 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/hkube/2037)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RonShvarz)

**Pull request merged**
