### PR TITLE
use new graph store

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1198)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1198)* status: all files reviewed, 5 unresolved discussions (waiting on @yehiyam)

___
*[core/api-server/lib/examples/pipelines-updater.js, line 6 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIgjYk1vFowS82kHi2:-MWIgjYl4IEiK-wBjVGg:b-c09vad) ([raw file](https://github.com/kube-hpc/hkube/blob/67e72502b72cd1e946811698dbfdf318d699d683/core/api-server/lib/examples/pipelines-updater.js#L6)):*
> ```JavaScript
> const algorithms = require('./algorithms.json');
> const pipelines = require('./pipelines.json');
> const drivers = require('./drivers.json');
> ```

Please format all files...

(We will need a`lite prettier`)
___
*[core/api-server/lib/examples/pipelines-updater.js, line 49 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIcv684aWbKhcb9YxS:-MWIcv684aWbKhcb9YxT:b-9y6l3v) ([raw file](https://github.com/kube-hpc/hkube/blob/67e72502b72cd1e946811698dbfdf318d699d683/core/api-server/lib/examples/pipelines-updater.js#L49)):*
> ```
> _db.jobs.search
> ```
You have function `stateManager.searchJobs`
___
*[core/api-server/lib/examples/pipelines-updater.js, line 115 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIdS3y90D0obx0a5ZT:-MWIdS3y90D0obx0a5ZU:b8ispit) ([raw file](https://github.com/kube-hpc/hkube/blob/67e72502b72cd1e946811698dbfdf318d699d683/core/api-server/lib/examples/pipelines-updater.js#L115)):*
> ```
> is
> ```
I probably meant `there are no jobs to sync`
___
*[core/pipeline-driver/tests/setup.js, line 6 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIihho0_Z7UVHxnI_j:-MWIihho0_Z7UVHxnI_k:b52uknw) ([raw file](https://github.com/kube-hpc/hkube/blob/67e72502b72cd1e946811698dbfdf318d699d683/core/pipeline-driver/tests/setup.js#L6)):*
> ```
> const db = require('../lib/state/db');
> ```
?
___
*[core/pipeline-driver/tests/setup.js, line 15 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIhtfeBPW2e0El4ZCr:-MWIhtfeBPW2e0El4ZCs:b-pitn9q) ([raw file](https://github.com/kube-hpc/hkube/blob/babbeec90a39a7a1703d73d0dadf246da16b1dc8/core/pipeline-driver/tests/setup.js#L15)):*
> ```
> await redis.flushall();
> ```
Sometimes it's necessary to remove all "redis jobs" that can affect the tests

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1198)* status: all files reviewed, 5 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/lib/examples/pipelines-updater.js, line 6 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIgjYk1vFowS82kHi2:-MWIknr114QiRXHnE6F9:b-dgiuxi) ([raw file](https://github.com/kube-hpc/hkube/blob/67e72502b72cd1e946811698dbfdf318d699d683/core/api-server/lib/examples/pipelines-updater.js#L6)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Please format all files...

(We will need a`lite prettier`)
</blockquote></details>

We don't need prettier. Thats what lint is for. If the rules are not good, change them, but don't add another tool
___
*[core/api-server/lib/examples/pipelines-updater.js, line 49 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIcv684aWbKhcb9YxS:-MWIlx6k90_9-ziVOE14:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/67e72502b72cd1e946811698dbfdf318d699d683/core/api-server/lib/examples/pipelines-updater.js#L49)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> _db.jobs.search
> ```
You have function `stateManager.searchJobs`
</blockquote></details>

Done.
___
*[core/api-server/lib/examples/pipelines-updater.js, line 115 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIdS3y90D0obx0a5ZT:-MWIm2Qz6NvqhIASQ3Q1:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/67e72502b72cd1e946811698dbfdf318d699d683/core/api-server/lib/examples/pipelines-updater.js#L115)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> is
> ```
I probably meant `there are no jobs to sync`
</blockquote></details>

Done.
___
*[core/pipeline-driver/tests/setup.js, line 6 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIihho0_Z7UVHxnI_j:-MWImrE5CGLLac53ur71:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/67e72502b72cd1e946811698dbfdf318d699d683/core/pipeline-driver/tests/setup.js#L6)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> const db = require('../lib/state/db');
> ```
?
</blockquote></details>

Done.
___
*[core/pipeline-driver/tests/setup.js, line 15 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIhtfeBPW2e0El4ZCr:-MWImryb5so3gw6pJbKN:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/babbeec90a39a7a1703d73d0dadf246da16b1dc8/core/pipeline-driver/tests/setup.js#L15)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> await redis.flushall();
> ```
Sometimes it's necessary to remove all "redis jobs" that can affect the tests 
</blockquote></details>

Done.

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1198)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @NassiHarel)

___
*[core/api-server/lib/examples/pipelines-updater.js, line 6 at r2](https://reviewable.io/reviews/kube-hpc/hkube/1198#-MWIgjYk1vFowS82kHi2:-MWIoy-i-FYzMvTHuf9X:b-896fix) ([raw file](https://github.com/kube-hpc/hkube/blob/67e72502b72cd1e946811698dbfdf318d699d683/core/api-server/lib/examples/pipelines-updater.js#L6)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

We don't need prettier. Thats what lint is for. If the rules are not good, change them, but don't add another tool
</blockquote></details>

Done.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/hkube/1198#-:-MWIu7wVDpFvgW7Z5fPq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
